Artemis-xyz/dbt

- models/dimensions/apps/dim_apps_silver.sql
- models/dimensions/contracts/dim_contracts_silver.sql
- models/staging/sui/__sui__sources.yml
- models/staging/sui/dim_sui_contracts.sql
- models/staging/sui/dim_sui_namespaces.sql
- models/staging/sui/fact_sui_contracts_silver.sql
Built support for sui contract labels.
> Added Support for Sui Contract labels

- models/staging/cosmoshub/fact_cosmoshub_daa.sql
- models/staging/cosmoshub/fact_cosmoshub_daa_gold.sql
- models/staging/cosmoshub/fact_cosmoshub_fees_and_revenue.sql
- models/staging/cosmoshub/fact_cosmoshub_txns.sql
- models/staging/cosmoshub/fact_cosmoshub_txns_gold.sql
1. Cosmos data was stale, switching to numia data instead of bitquery
> Customer 911: Updating cosmos models

- models/metrics/stablecoins/metrics/agg_daily_stablecoin_metrics_silver.sql
1. Removing blast from agg_stablecoin_metrics_silver
To do:
1. Update the api in gokustats and front end
> Short Term Stablecoin fix

- macros/agg_chain_stablecoin_metrics.sql
- macros/agg_chain_stablecoin_transfers.sql
- macros/metrics/get_mau_metrics.sql
- macros/metrics/get_stablecoin_metrics.sql
- models/metrics/stablecoins/metrics/agg_daily_stablecoin_metrics.sql
- models/projects/arbitrum/core/ez_arbitrum_metrics.sql
- models/projects/avalanche/core/ez_avalanche_metrics.sql
- models/projects/base/core/ez_base_metrics.sql
- models/projects/blast/core/ez_blast_metrics.sql
- models/projects/bsc/core/ez_bsc_metrics.sql
- models/projects/celo/core/ez_celo_metrics.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/projects/optimism/core/ez_optimism_metrics.sql
- models/projects/polygon/core/ez_polygon_metrics.sql
- models/projects/solana/core/ez_solana_metrics.sql
- models/projects/tron/core/ez_tron_metrics.sql
MAU
1. `ethereum`, `base`, `polygon`, `tron`, `optimism`, `arbitrum`
Deduped_Stablecoin_transfer_volume
1. All chains that support stablecoins
> BCC: MAU and Deduped Stablecoin Volumes

- .github/workflows/compile.yml
- .github/workflows/show_changed_models.yml
I think this handles what was originally intended: one build per PR + one for master. Previously it'd cancel PR builds if master was pushed.
> fix build cancellation grouping

- models/projects/celo/core/ez_celo_metrics.sql
1. Removing `MAU` from CELO ez_metric table
> Fixing celo ez_metric table

- models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql
- models/projects/rainbow_bridge/core/ez_rainbow_bridge_metrics.sql
- models/projects/rainbow_bridge/core/ez_rainbow_bridge_metrics_by_chain.sql
- models/staging/rainbow_bridge/_test_fact_rainbow_bridge_bridge_dau.yml
- models/staging/rainbow_bridge/_test_fact_rainbow_bridge_bridge_volume.yml
- models/staging/rainbow_bridge/fact_rainbow_bridge_bridge_dau.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_bridge_volume.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_flows.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
1. Adding Near Rainbow Bridge through `ez_metrics`
> Bridges: Adding Rainbow Bridge

- macros/forward_fill.sql
- macros/lst/calc_staked_eth.sql
- macros/transform/raw_partioned_array_to_fact_table_many_columns.sql
- models/data_hubs/fact_daily_app_datahub.sql
- models/staging/binance_staked_eth/__binance_staked_eth__sources.yml
- models/staging/binance_staked_eth/fact_binance_staked_eth_count.sql
- models/staging/binance_staked_eth/fact_binance_staked_eth_count_with_usd_and_change.sql
Added following macros:
- `forward_fill` - more forward any nulls / empties in range
- `raw_partitioned_array_to_fact_table_many_columns` - takes a partioned array of data in a table with many columns and plops into fact table
- `calc_staked_eth` - dollarizes + calcs net change for staked ETH
Used these to calculate Binance Staked ETH - should make the rest of them a lot easier
> Add Binance Staked ETH (+macros to get the rest more easily!)

- models/projects/ton/core/ez_ton_metrics.sql
- models/staging/ton/__ton__sources.yml
- models/staging/ton/_test_fact_ton_daa_txns_gas_gas_usd_revenue_revenue_native.yml
- models/staging/ton/fact_ton_dex_volumes.sql
1. Updating Ton DEX Volume data to pull from Ton Stats
> Ton Dex Volumes Data

- macros/staking/calc_staked_eth.sql
- models/projects/etherfi/ez_etherfi_metrics_by_chain.sql
- models/projects/puffer_finance/ez_puffer_finance_metrics_by_chain.sql
- models/projects/renzo_protocol/ez_renzo_protocol_metrics_by_chain.sql
- models/staging/etherfi/_test_fact_etherfi_staked_eth_count_with_USD_and_change.yml
- models/staging/etherfi/fact_etherfi_restaked_eth_count.sql
- models/staging/etherfi/fact_etherfi_restaked_eth_count_with_usd_and_change.sql
- models/staging/puffer_finance/_test_fact_puffer_finance_staked_eth_count_with_USD_and_change.yml
- models/staging/puffer_finance/fact_puffer_finance_restaked_eth_count.sql
- models/staging/puffer_finance/fact_puffer_finance_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/_test_fact_renzo_protocol_arbitrum_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_base_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_blast_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_bsc_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_ethereum_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_linea_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/_test_fact_renzo_protocol_mode_restaked_eth_count_with_usd_and_change.yml
- models/staging/renzo_protocol/fact_renzo_protocol_arbitrum_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_base_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_blast_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_bsc_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_ethereum_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_linea_restaked_eth_count_with_usd_and_change.sql
- models/staging/renzo_protocol/fact_renzo_protocol_mode_restaked_eth_count_with_usd_and_change.sql
1. Creating ez_metric_by_chain tables for Etherfi, Puffer Finance, Renzo Protocol. We are currently tracking the same metrics as liquid staking
> LRT: Create EZ Metrics Tables

- models/staging/flow/fact_flow_daa_txns.sql
Flow uses a model similar to Solana where the user need not be the fee payer.
Current methodology undercounts dApps by Dapper labs - NBA Topshot, NFL ALL DAY, LiveNation, Joyride - b/c they all use 1 fee payer.
New numbers are in line with most Flow block explorers.
> Flow Payers -> Authorizers for DAA

- macros/staking/calc_staked_eth.sql
- Pull in latest CoinGecko data with macro instead of referencing table directly to fix not having latest data
> Fix LST Pricing Issue

- dbt_scripts/show_changed.sh
- Only run first-order children of modified models instead of all downstreams
- Only run models via (`--resource-type model`)
> Only Run Modified Model Children

- models/projects/internet_computer/core/ez_internet_computer_metrics.sql
- models/staging/internet_computer/__internet_computer__sources.yml
- models/staging/internet_computer/_test_fact_internet_computer_canister_total_state.yml
- models/staging/internet_computer/_test_fact_internet_computer_neuron_funds.yml
- models/staging/internet_computer/fact_internet_computer_canister_total_state_silver.sql
- models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
- models/staging/internet_computer/fact_internet_computer_neuron_funds_silver.sql
Added New ICP metrics:
Neuron Community Fund Size
Total Canister State
> Added Neuron Community Fund and other data sets

- models/projects/sei/core/ez_sei_metrics.sql
Sei update with EVM chain borked ez sei metrics dau, txns, and fees which is no a summation of both v1 and v2.
> Fix Sei all null metrics

- .github/workflows/show_changed_models.yml
1. Our Current Setup for when Show Changed Models runs every time a user submits a PR or merges to main. This ends up using an unnecessary about of snowflake credits as members apart of the Artemis Team can test the models in dagster. See [here](https://artemisxyz.slack.com/archives/C064A3GBYJ2/p1717390935288159) for amount of credits used last week.
2. For users who are in the Artemis [All](https://github.com/orgs/Artemis-xyz/teams/all) team do not run the show changed models GH action.
> Show Changed Models GH Action: Update to only run on open source contributors

- .github/workflows/show_changed_models.yml
1. Updating Github actions permission to allow a read to [members](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-actions) -- `/orgs/{org}/teams`
> Updating Github Action permissions

- models/staging/injective/__injective__sources.yml
- models/staging/injective/fact_injective_fees_native_silver.sql
- models/staging/injective/fact_injective_fees_usd_silver.sql
- Aligning this definition with our convention for other `source`s
- Renaming sources used by injective to not have a `.` so we don't have to add more custom logic via `CustomDagsterDbtTranslator`
- Updated `.yml` file as well as `source` macro callsites
`dbt compile`
> Update Injective Source Name

- macros/p2p/filter_p2p_token_transfers.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/staging/ethereum/fact_ethereum_p2p_transfer_volume.sql
- models/staging/osmosis/_test_fact_osmosis_gas_gas_usd_fees_revenue.yml
1. Fixing Osmosis Test to not include native gas
2. Fixing Ethereum_p2p_token_transfers to filter based on positive dex volumes
> Customer 911: Fixing Ethereum and Osmosis

- models/staging/scroll/fact_scroll_gas_gas_usd_revenue.sql
- models/staging/zora/fact_zora_gas_gas_usd_revenue.sql
Prevents nulls from the current day from getting into zora + scroll gold tables.
> Fixed current day nulls in Zora + Scroll

- macros/set_query_tag.sql
Attribute query runs to the corresponding dbt model
https://docs.getdbt.com/reference/resource-configs/snowflake-configs#query-tags
```
dbt parse
dbt run --select fact_compound_lending_v2_ethereum
```
```
SELECT
query_tag,
database_name
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
query_tag = 'fact_compound_v2_lending_ethereum'
```
Old query tags for tests + `CREATE TABLE` statements are all rolled up into `DEV`
New tags allow us to attribute the query to the specific dbt model + test
> Set Model Name as Query Tag

- macros/decentralized_exchanges/fact_curve_trading_vol_trading_fees_trading_revenue.sql
- macros/decentralized_exchanges/fact_curve_tvl.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v2_fork_trading_vol_and_fees.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v2_fork_tvl.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v2_fork_tvl_by_pool.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v3_fork_trading_vol_and_fees.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v3_fork_tvl.sql
- macros/decentralized_exchanges/fact_daily_uniswap_v3_fork_tvl_by_pool.sql
- macros/decentralized_exchanges/fact_uniswap_v2_fork_dex_swaps.sql
- macros/decentralized_exchanges/fact_uniswap_v3_fork_dex_swaps.sql
- models/staging/across/fact_across_flows.sql
- models/staging/arbitrum_one_bridge/fact_arbitrum_one_bridge_flows.sql
- models/staging/avalanche_bridge/fact_avalanche_bridge_flows.sql
- models/staging/base_bridge/fact_base_bridge_flows.sql
- models/staging/optimism_bridge/fact_optimism_bridge_flows.sql
- models/staging/polygon_pos_bridge/fact_polygon_pos_bridge_flows.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
- models/staging/starknet_bridge/fact_starknet_bridge_flows.sql
- models/staging/synapse/fact_synapse_flows.sql
- models/staging/wormhole/fact_wormhole_transfers.sql
- models/staging/zksync_era_bridge/fact_zksync_era_bridge_flows.sql
1. Flipside pricing changed their table name. We are porting over to the new pricing table. The schema is the same.
> Flipside Pricing: porting over to pricing

- models/staging/frax/fact_frax_staked_eth_count_with_USD_and_change.sql
- models/staging/lido/fact_lido_staked_eth_count_with_USD_and_change.sql
- models/staging/mantle/fact_meth_staked_eth_count_with_USD_and_change.sql
- models/staging/rocketpool/fact_rocketpool_staked_eth_count_with_USD_and_change.sql
- models/staging/stakewise/fact_stakewise_staked_eth_count_with_USD_and_change.sql
1. LST Data is usually stale. The issue was coming from an inner joining on the pricing table that does not have complete data for the next day. It is important to use the following macro to have the most up to date pricing data `get_coingecko_price_with_latest`
> C911: Fixing LST Staleness

- macros/metrics/get_stablecoin_metrics.sql
- models/data_hubs/fact_daily_chain_datahub.sql
- models/metrics/revenue/agg_daily_ethereum_revenue.sql
- models/metrics/revenue/agg_daily_gnosis_revenue.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/staging/gnosis/fact_gnosis_daa_txns_gas_gas_usd.sql
- models/staging/zksync/fact_zksync_revenue.sql
Needed to add ez_ethereum_metrics to the datahub to prevent datahub data chain level from being borked. 
Also migrated to new flipside easy pricing data.
> Fix Ethereum Datahub

- macros/rolling_active_addresses.sql
Added refs to the rolling data macro so that rolling wau and mau is done after ez_transaction table is finished.
> Add References into macros for rolling wau + mau

- macros/agg_chain_stablecoin_transfers.sql
- models/metrics/stablecoins/transfers/fact_solana_stablecoin_transfers.sql
- Logic rework. Previously we were assuming mints/burns could only happen in premints, so we were tracking net outflow from premints as supply.
- However, we discovered the above assumption is not true. 
- Consequently, new formula works as follows: 
`CIRC_SUPPLY = TOTAL MINTS OUTSIDE OF PRE-MINTS - TOTAL BURNS OUTSIDE OF PRE-MINTS + NET OUTFLOW OUT OF PRE-MINTS TO EOAs`
> Fix Solana Stablecoins

- models/projects/aevo/core/ez_aevo_metrics_by_chain.sql
- models/projects/apex/core/ez_apex_metrics_by_chain.sql
- models/projects/avantis/core/ez_avantis_metrics_by_chain.sql
- models/projects/bluefin/core/ez_bluefin_metrics_by_chain.sql
- models/projects/drift/core/ez_drift_metrics_by_chain.sql
- models/projects/dydx/core/ez_dydx_metrics_by_chain.sql
- models/projects/dydx_v4/core/ez_dydx_v4_metrics_by_chain.sql
- models/projects/gmx/core/ez_gmx_metrics_by_chain.sql
- models/projects/gmx/core/ez_gmx_metrics_by_version.sql
- models/projects/holdstation/core/ez_holdstation_metrics_by_chain.sql
- models/projects/hyperliquid/core/ez_hyperliquid_metrics_by_chain.sql
- models/projects/ktx_finance/core/ez_ktx_finance_metrics_by_chain.sql
- models/projects/level_finance/core/ez_level_finance_metrics_by_chain.sql
- models/projects/perpetual_protocol/core/ez_perpetual_protocol_metrics_by_chain.sql
- models/projects/rabbit_x/core/ez_rabbit_x_metrics_by_chain.sql
- models/projects/synthetix/core/ez_synthetix_metrics_by_chain.sql
- models/projects/vertex/core/ez_vertex_metrics_by_chain.sql
1. Create the ez_metric_tables for most of the perpetual protocols. The following list are the perpetual protocols that do NOT have an ez_metric table yet:
`gains`
`mux`
> Perpetuals

- models/projects/gains_network/core/ez_gains_network_metrics_by_chain.sql
- models/projects/mux/core/ez_mux_metrics_by_chain.sql
1. Creating separate ez_metric tables for `mux` and `gains`
> Perps: Mux and Gains

- requirements.txt
- Numpy `2.0` was released today ([pypi history](https://pypi.org/project/numpy/#history))
- Having the unpinned dependency causes an issue with the dbt snowflake adapter ([dbt slack](https://getdbt.slack.com/archives/CJN7XRF1B/p1718637552783169?thread_ts=1718637120.186429&cid=CJN7XRF1B)), this causes our CI runs to fail at the `dbt deps` step
- `dbt deps` succeeds off of a fresh CI run
> pin numpy version to 1.26.4

- models/projects/frax/core/ez_frax_metrics_by_chain.sql
- models/projects/frax/core/ez_frax_metrics_by_pool.sql
- models/projects/quickswap/core/ez_quickswap_metrics_by_chain.sql
- models/projects/quickswap/core/ez_quickswap_metrics_by_pool.sql
- models/staging/pancakeswap/fact_pancakeswap_v2_bsc_dex_swaps.sql
Fixing bugs in `pancakeswap`, `quickswap` and `frax`
> DEX: Fix Bugs 

- models/projects/frax/raw/ez_frax_dex_swaps.sql
- models/projects/quickswap/raw/ez_quickswap_dex_swaps.sql
- models/projects/sushiswap/raw/ez_sushiswap_dex_swaps.sql
- models/projects/trader_joe/raw/ez_trader_joe_dex_swaps.sql
There was an extra comma in the ez_swap table for the following dex's:
`quickswap`
`frax`
`sushiswap`
`trader_joe`
> DEX Models: Fixing Compliation Bugs in ez_swap tables

- models/data_hubs/fact_daily_app_datahub.sql
> rm tables from app datathub

- .github/workflows/docs.yml
- Necessary for https://github.com/Artemis-xyz/dbt/pull/216 to enable partial parsing
- Partial parse file is around 1/2 the size of the dbt manifest so should be fine to upload 
- File is generated by `dbt docs generate` command. 
- Ran `rm -rf target/` and then `dbt docs generate` and file was present within a fresh `target` folder
> Upload partial_parse.msgpack to docsite

- .github/actions/init-dbt/action.yml
- .github/workflows/compile.yml
- .github/workflows/docs.yml
- .github/workflows/show_changed_models.yml
- Enable partial parsing on dbt steps 
- Get latest dbt manifest from docsite
- Abstract repeated pip + manifest download code into `init-dbt` workflow
- Turn on python dependency [caching](https://github.com/actions/setup-python/tree/main?tab=readme-ov-file#caching-packages-dependencies) like we have in the BE repo
- Deleted `target` folder 
- `dbt parse` and "no saved manifest found" 
- Ran commands to download from GH pages, partial parsing works
> Enable partial parsing in all actions workflows

- models/metrics/contracts/fact_arbitrum_contracts_gold.sql
- models/metrics/contracts/fact_avalanche_contracts_gold.sql
- models/metrics/contracts/fact_base_contracts_gold.sql
- models/metrics/contracts/fact_blast_contracts_gold.sql
- models/metrics/contracts/fact_bsc_contracts_gold.sql
- models/metrics/contracts/fact_ethereum_contracts_gold.sql
- models/metrics/contracts/fact_linea_contracts_gold.sql
- models/metrics/contracts/fact_optimism_contracts_gold.sql
- models/metrics/contracts/fact_polygon_contracts_gold.sql
- models/metrics/contracts/fact_scroll_contracts_gold.sql
- models/metrics/contracts/fact_zora_contracts_gold.sql
- models/staging/fantom/fact_fantom_contracts_gold.sql
- models/staging/near/fact_near_contracts_gold.sql
- models/staging/solana/fact_solana_contracts_gold.sql
1. Gold tables are orphaned and we can now remove
https://github.com/Artemis-xyz/gokustats-back-end/pull/2090
2. These assets are all daily metrics on contracts created like daily deploys
> rm contracts_gold

- models/metrics/revenue/agg_daily_ethereum_revenue_gold.sql
- models/metrics/revenue/agg_daily_polygon_revenue_gold.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/projects/near/core/ez_near_metrics.sql
- models/projects/polygon/core/ez_polygon_metrics.sql
- models/staging/near/fact_near_revenue_gold.sql
Since we are no longer use the gold tables, I am updating the dependency to be on the "silver" table rather than the gold in the ez metric models.
> Update Ez Metric Dependencies: Polygon, Ethereum, Near

- .github/actions/init-dbt/action.yml
- .github/workflows/compile.yml
- Makefile
- Porting over `pip` commands to `uv` ([github](https://github.com/astral-sh/uv?tab=readme-ov-file)), a drop-in replacement package manager + dependency resolver in order to improve build performance 
- Use of a virtualenv is typically required, but the `--system` Astral/uv team mentions in the [docs](https://github.com/astral-sh/uv?tab=readme-ov-file#installing-into-arbitrary-python-environments) that doing a system-level install is fine within a CI environment
- Increase # of threads used in the `dbt compile` step in CI from 4 -> 16 
- Executed commands locally 
- dbt is installed + commands work in the CI environment for this PR
> Switch from pip -> uv

- macros/metrics/get_fundamental_data_for_chain.sql
- models/projects/near/core/ez_near_metrics.sql
> Count delegate txn in NEAR DAU

- macros/stablecoins/agg_daily_stablecoin_metrics_breakdown.sql
- models/staging/ethereum/agg_ethereum_daily_stablecoin_metrics_breakdown.sql
1. Adding Artemis metrics 
2. Making metric table incremental
> Stablecoins: Add Artemis Metrics, Make Incremental

- macros/stablecoins/agg_daily_stablecoin_metrics_breakdown.sql
1. Stablecoin metrics table joins on balances table but the balances table has a row for every address that has every interacted with stablecoins
2. This blows up the size of the metrics table and make it difficult to use in the API. what to remove all rows that do not add any metrics
> Stablecoins: Remove Dummy Rows from Table

- models/staging/optimism/agg_optimism_stablecoin_balances.sql
- models/staging/polygon/agg_polygon_stablecoin_balances.sql
- models/staging/tron/agg_tron_stablecoin_balances.sql
> Use new warehouses for balances computation so we don't max out warehouse concurrency limit

- macros/stablecoins/agg_chain_stablecoin_metrics.sql
- models/metrics/stablecoins/metrics/agg_ton_stablecoin_metrics.sql
- models/projects/ton/raw/ez_ton_stablecoin_transfers.sql
- models/staging/ton/__ton__sources.yml
- models/staging/ton/_test_fact_ton_stablecoin_transfers.yml
- models/staging/ton/fact_ton_stablecoin_contracts.sql
- models/staging/ton/fact_ton_stablecoin_transfers.sql
Created an ez_ton_stablecoin_transfers to use to build balances and aggregated data.
> Added Ton Stablecoin Transfers + Aggregated Data

- macros/stablecoins/agg_daily_stablecoin_metrics_breakdown.sql
- models/staging/ethereum/agg_ethereum_daily_stablecoin_metrics_breakdown.sql
1. Change ethereum unique key from symbol to `contract_address`
2. use `ref` in stablecoin marco for `dim_contracts_gold`
> Stablecoins: Fix Ethereum Unique Key and use ref

- models/projects/chainlink/prod_core/ez_chainlink_metrics_by_chain.sql
1. Fixing the chainlink ez_metric by chain table to have one row per chain per date
> Updating chainlink ez metric by chain

- models/staging/arbitrum/fact_arbitrum_p2p_stablecoin_transfers.sql
- models/staging/avalanche/fact_avalanche_p2p_stablecoin_transfers.sql
- models/staging/base/fact_base_p2p_stablecoin_transfers.sql
- models/staging/ethereum/fact_ethereum_p2p_stablecoin_transfers.sql
- models/staging/near/fact_near_p2p_stablecoin_transfers.sql
- models/staging/optimism/fact_optimism_p2p_stablecoin_transfers.sql
- models/staging/polygon/fact_polygon_p2p_stablecoin_transfers.sql
- models/staging/solana/fact_solana_p2p_stablecoin_transfers.sql
- models/staging/tron/fact_tron_p2p_stablecoin_transfers.sql
1. There is an issue with the current lineage for stablecoins where the p2p transfers should rely on the transfers table: https://artemisxyz.slack.com/archives/C04EJTAAYQK/p1719952728832099
2. Forcing the dependency so that dagster is aware
> P2P Stablecoins

- models/dimensions/dim_chain_ids.sql
- models/staging/across/fact_across_transfers.sql
Across is currently testing the support of `lisk` (chain id 1135). Though the support has not been implemented by across yet. We also don't currently support `Lisk` as a chain. Instead of having 1/2 of the volume we explicitly remove support for `lisk`, so that we can have complete support for across over the current chains supported. 
Once Across has officially added support for `lisk` we will need to add an extraction step similar to `zksync` or `linea`.
Tested the materialization of the files changed.
> Across: Remove support for Lisk

- macros/chainlink/chainlink_vrf_request_fulfilled_logs.sql
1. `chainlink_vrf_log` incremental runs is slightly different than the other chainlink log runs. The final table does not have `block_timestamp` instead it has `evt_block_time`. We need to use this for an incremental run
To test I ran the lineage for avalanche.
> Chainlink: Fixing VRF Incremental Run

- macros/stablecoins/agg_chain_stablecoin_transfers.sql
- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_premint_addresses.sql
- models/metrics/stablecoins/contracts/fact_tron_stablecoin_premint_addresses.sql
- models/metrics/stablecoins/transfers/fact_ethereum_stablecoin_transfers.sql
- models/metrics/stablecoins/transfers/fact_tron_stablecoin_transfers.sql
Stablecoin supply for Ethereum and Tron are being over counted for USDT. Supply is bridged to other L2s and BSC. We are over counting by not subtracting the bridges supply from Ethereum and Tron. 
https://artemisxyz.slack.com/archives/C061BU21THQ/p1720717489473519
> USDT Stablecoin Supply: Ethereum and Tron

- macros/stablecoins/agg_daily_stablecoin_metrics_breakdown.sql
- macros/stablecoins/agg_foward_filled_stablecoin_balances_by_addresses.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_premint_addresses.sql
- models/staging/arbitrum/agg_arbitrum_daily_stablecoin_metrics_breakdown.sql
- models/staging/avalanche/agg_avalanche_daily_stablecoin_metrics_breakdown.sql
- models/staging/base/agg_base_daily_stablecoin_metrics_breakdown.sql
- models/staging/blast/agg_blast_daily_stablecoin_metrics_breakdown.sql
- models/staging/bsc/agg_bsc_daily_stablecoin_metrics_breakdown.sql
- models/staging/ethereum/agg_ethereum_daily_stablecoin_metrics_breakdown.sql
- models/staging/optimism/agg_optimism_daily_stablecoin_metrics_breakdown.sql
- models/staging/tron/agg_tron_daily_stablecoin_metrics_breakdown.sql
1. Runnin the lineage `stablecoin_balances` --> `daily_stablecoin_metrics_breakdown` for the following chains:
`ethereum`
`bsc`
`arbitrum`
`avalanche`
`base`
`blast`
`optimism`
`polygon`
`tron`
2. Create 2 new warehouses for the new stablecoin jobs. This will help us track the currently spend of stablecoin v2
3. Update the Stablecoin v2 macros to no longer rely on flipside's tags
1. The backfill for the `daily_stablecoin_metrics_breakdown` tables for each chain can take >15 hours (ex. `bsc`). For solana this will need to be optimized.
2. Stablecoin balances by sector currently don't add up to the correct supply (ex. Optimism). This issue is coming from the underlying balanances table. It may be worth it to create separate stablecoin balances tables as there is `n` know cases to take into …
> Stablecoin V2: EVM Models

- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
- macros/stablecoins/stablecoin_metrics_p2p.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/projects/base/core/ez_base_stablecoin_metrics_by_address.sql
- models/staging/base/fact_base_stablecoin_balances.sql
- models/staging/base/fact_base_stablecoin_metrics_all.sql
- models/staging/base/fact_base_stablecoin_metrics_artemis.sql
- models/staging/base/fact_base_stablecoin_metrics_p2p.sql
1. The marcos on the stablecoin v2 pipeline are not robust. If there is an issue with the data it can take > 15hrs to backfill. By splitting up the marcos it is also easier to edit the models and fix issues with different chains. 
2. i.e. Known issues of the old monolithic model: Stablecoin supply doesn't add up properly, Incremental run on macro table borks old data. 
These this structure relies on 5 models for each chain. We split up each filter to have its own macro (`all`, `artemis`, `p2p`) as well as give stablecoin supply and the final metrics its own marco. This makes is more robust to edit specific sections of the data.
I test these macros with `base`: https://app.artemis.xyz/stablecoins-v2. 
1. The marcos will need to be incremental, I will build this functionality out when we …
> Stablecoin V2: Split up macros and Test with Base 

- macros/stablecoins/stablecoin_metrics.sql
- models/projects/arbitrum/core/ez_arbitrum_stablecoin_metrics_by_address.sql
- models/projects/base/core/ez_base_stablecoin_metrics_by_address.sql
- models/staging/arbitrum/fact_arbitrum_stablecoin_balances.sql
- models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_all.sql
- models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_artemis.sql
- models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_p2p.sql
1. Create the arbitrum lineage for the new stablecoin pipeline
2. Make the `stablecoin_metrics` macro incremental
> Stablecoin V2: Create Arbitrum Lineage, incremental `stablecoin_metrics`

- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_metrics.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
1. Remove Intra-CEX from p2p Transfers. 
2. Also want Exchange to be more clear, change tagging to CEX rather than Exchange
> Stablecoin V2: Tagging to Exchange --> CEX, Update P2P to Remove Intra-CEX

- macros/stablecoins/stablecoin_metrics.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
- macros/stablecoins/stablecoin_metrics_p2p.sql
1. Incremental run for base and arbitrum is borked switch `block_timestamp` to `date`
> Stablecoin V2: Fix Incremental Run

- models/projects/tron/core/ez_tron_stablecoin_metrics_by_address.sql
- models/staging/tron/fact_tron_stablecoin_balances.sql
- models/staging/tron/fact_tron_stablecoin_metrics_all.sql
- models/staging/tron/fact_tron_stablecoin_metrics_artemis.sql
- models/staging/tron/fact_tron_stablecoin_metrics_p2p.sql
1. The new stablecoin data relies on 5 different macros and files per chain.
1. The filtered metric files: `stablecoin_metrics_p2p`, `stablecoin_metrics_artemis`, `stablecoin_metrics_all`
2. The forward filled balances file: `stablecoin_balances`
3. The final aggregated metric file: `stablecoin_metrics`
Stablecoin Pipeline:
> Stablecoin V2: Tron

- models/staging/tron/fact_tron_p2p_native_transfers.sql
- models/staging/tron/fact_tron_p2p_stablecoin_transfers.sql
- models/staging/tron/fact_tron_p2p_token_transfers_silver.sql
1. Tron P2P transfer tables are doing a full refresh every time and taking > 1hr to run. These tables should be incremental.
> P2P Tranfers: Tron

- models/projects/ton/core/ez_ton_metrics.sql
- models/staging/ton/fact_ton_daa_txns_gas_gas_usd_revenue_revenue_native.sql
Switch from Ton Apps to just regularly named metrics in dbt model.
> Update naming of TON Metrics

- macros/stablecoins/stablecoin_metrics_artemis.sql
1. There was a complication error in the `stablecoin_metrics_artemis` macro.
> Stablecoin V2: Artemis Filter

- macros/address_balances/address_credits.sql
- macros/address_balances/address_debits.sql
All of our balances tables have duplicate rows. I have re-run op with a complete refresh and still today there are duplicate rows existing in the table. DBT does not allow for a column that creates a unique key to be null, otherwise it is not able to determine the unique rows
This shows how the balances table for base has duplicate rows:
2. In order to fix this I change the nulls in the credit and debits tables to empty strings. Going forward for all incremental tables it may be worth it to start using a single row representing the unique key (i.e. md5(<column1> || <column2> || ...) ) or using surrogate keys (https://docs.getdbt.com/blog/sql-surrogate-keys) (https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#generate_surrogate_key-source). This will ensure that there is a single …
> Balances: Replace Nulls with Empty Strings

- macros/address_balances/address_credits.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
1. Add `ethereum` to final stablecoin v2 metrics table
2. Fix Polygon address credits:
Polygon deposits of the wrapped token are already included in the ez_token_transfers. Run sql below to verify:
```
select 
block_timestamp
,tx_hash
,event_index
, contract_address
, decoded_log
, null from_address
,null to_address
,null amount
,null amount_precise
from polygon_flipside.core.ez_decoded_event_logs 
where event_name ='Deposit' and  tx_hash = '0xe3542014a72ed6ce39f3678aaa49aeb0a92c094492e1f3b702372b61c6814981'
union all
select 
block_timestamp
,tx_hash
,event_index
, contract_address
, null as decoded_log
, from_address
,to_address
,amount
,amount_precise
from polygon_flipside.core.ez_token_transfers
where tx_hash = '0xe3542014a72ed6ce39f3678aaa49aeb0a92c094492e1f3b702372b61c6814981'
and …
```
> Stablecoin V2: Polygon Address Credits and Ethereum

- macros/address_balances/address_balances_by_token.sql
- macros/address_balances/address_credits_allium.sql
- macros/address_balances/address_debits_allium.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/staging/tron/fact_tron_address_credit_by_token.sql
- models/staging/tron/fact_tron_address_debit_by_token.sql
1. Tron credits and debits tables had duplicates. In order to fix this I changed how dbt recognized the unique key and full refreshed all the tron tables
2. DAI within the maker protocol does not follow the traditional ERC20 standard. Instead the account system is done in the `vat`. This is the supply that is in the Dai Savings in this query: https://dune.com/queries/54599/108371. We have historically been under counting the total supply of DAI by about 2 billion. 
3. I am also removing ethereum from the final metric table because I have to re-backfill the balances which will most likely not be done by the time the job runs tonight.
> Stablecoin V2: Tron and Ethereum Balances

- models/staging/ton/fact_ton_stablecoin_transfers.sql
Ton apps sometimes does not have symbols. Using url instead to verify that its tether.
> added ton stablecoin transfers symbol using url

- models/projects/maker/prod_raw/fact_maker_pnl.sql
Removing spaces from Maker column names for better internal Snowflake script compatibility.
There are no assets downstream of this one.
> removing spaces for snowflake script compatibility

- models/projects/sui/core/ez_sui_metrics.sql
- models/projects/sui/core/ez_sui_metrics_by_application.sql
- models/projects/sui/core/ez_sui_metrics_by_category.sql
- models/projects/sui/core/ez_sui_metrics_by_contract.sql
We still look at failed transactions to count for fees + revenue.
> Fixed Sui to not count failed transactions in DAU and transaction counts

- macros/address_balances/address_balances_by_token.sql
- models/staging/solana/fact_solana_address_balances_by_token.sql
- models/staging/solana/fact_solana_stablecoin_balances.sql
1. A single `tron` address has a negative balance of about $10 at maximum. This is because its first transfer is out rather than in. In order to fix this, I am adding 100000/1E6 to `THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC` 
2. Solana Token Balances are very far off. Instead of doing digging into what is causing it (Not sure it is worth the time), I am switching us over to rely on `flipside` similar to what we do for Ethereum. For stablecoins see the image below but we are over counting by a significant amount.  <img width="771" alt="Screenshot 2024-07-31 at 2 15 03 PM" src="https://github.com/user-attachments/assets/6ea3bcf0-53c6-4f3c-9ecf-ca087ad5534e">
> Stablecoin V2: Tron and Solana

- macros/address_balances/address_balances_by_token.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/projects/solana/core/ez_solana_stablecoin_metrics_by_address.sql
- models/staging/solana/fact_solana_stablecoin_metrics_all.sql
- models/staging/solana/fact_solana_stablecoin_metrics_artemis.sql
- models/staging/solana/fact_solana_stablecoin_metrics_p2p.sql
1. Adding `solana` stablecoin models
2. Adding clustering to the final Stablecoin Table. This should help with response times on the frontend. If this does not speed it up fast enough then we may want to create new breakdown tables or cluster by other keys:
https://docs.snowflake.com/en/user-guide/tables-clustering-keys#benefits-of-defining-clustering-keys-for-very-large-tables
> Stablecoin V2: Solana and Clustering

- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
- models/staging/bsc/fact_bsc_p2p_stablecoin_transfers.sql
- models/staging/bsc/fact_bsc_stablecoin_balances.sql
- models/staging/bsc/fact_bsc_stablecoin_metrics_all.sql
- models/staging/bsc/fact_bsc_stablecoin_metrics_artemis.sql
- models/staging/bsc/fact_bsc_stablecoin_metrics_p2p.sql
1. Fix Stablecoin Pricing by using historical coingecko pricing table rather than real time table
2. Add BSC balances, and metric tables. 
To do: 
1. Finish backing filling BSC on prod
2. create `ez_bsc_stablecoin` table
> Stablecoin V2: BSC and Pricing

- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
I recently updated the pricing data to fix a bug but created a complication error because I am pulling from and different table. [This](https://artemis.dagster.cloud/prod/runs/68a1d0e8-3045-40a1-9c4a-0f85f79ae9ef) should not be fixed
> Stablecoin V2: Fixing Macros

- models/projects/aave/raw/ethereum/fact_aave_dao_safety_incentives.sql
1. Fixing type that caused this error: https://artemis.dagster.cloud/prod/runs/bf9751be-207c-4d6a-985b-035c486079f3?logFileKey=uhbgxfdt&selection=%22run_dbt_d2c55_2%22&logs=query%3A%22run_dbt_d2c55_2%22
> Fidelity: AAVE Fix Safety Incentives

- models/common/__common__sources.yml
- models/common/daily_market_data.sql
- models/common/ez_stablecoin_metrics.sql
- models/common/realtime_market_data.sql
1. The data is a day off because of an issue with the lineage.
> Fixing Art Share Coingecko Lineage

- models/data_hubs/fact_coingecko_token_realtime_datahub.sql
- models/staging/coingecko/fact_coingecko_token_realtime_data.sql
- Comparing row counts between new and old queries 
- Switch `PROD_REALTIME_DATAHUB` wh to `XS`
- Can delete this warehouse as well
Old vs. new query
> Optimize Coingecko Realtime Query

- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/projects/bsc/core/ez_bsc_stablecoin_metrics_by_address.sql
1. Adding BSC final table to silver table
To do:
1. Run `ez_bsc_table`
> Stablecoin V2: BSC

- models/staging/sui/_test_fact_sui_transactions.yml
> Turned Data Freshness to error instead of warn

- macros/decode/token_transfer_events.sql
- models/dimensions/contracts/dim_celo_contract_addresses.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
- models/metrics/stablecoins/contracts/fact_celo_stablecoin_contracts.sql
- models/projects/celo/core/ez_celo_stablecoin_metrics_by_address.sql
- models/staging/celo/fact_celo_p2p_stablecoin_transfers.sql
- models/staging/celo/fact_celo_stablecoin_balances.sql
- models/staging/celo/fact_celo_stablecoin_metrics_all.sql
- models/staging/celo/fact_celo_stablecoin_metrics_artemis.sql
- models/staging/celo/fact_celo_stablecoin_metrics_p2p.sql
Celo has a unique architecture where you can pay for a transaction in any of the major stablecoins. These count as transfers and the amount transferred goes to the miner. In order to take this into account we need to get this data from the transactions not the transfers as it is not released as a transfer event.
> Stablecoin V2: Celo

- models/metrics/stablecoins/breakdowns/daily/agg_blast_stablecoin_breakdown_daily.sql
- models/metrics/stablecoins/breakdowns/daily/agg_stablecoin_breakdown_daily.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_blast_stablecoin_breakdown_monthly.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_stablecoin_breakdown_monthly.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_blast_stablecoin_breakdown_weekly.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_stablecoin_breakdown_weekly.sql
- models/metrics/stablecoins/metrics/agg_blast_stablecoin_metrics.sql
- models/metrics/stablecoins/metrics/agg_daily_stablecoin_metrics_silver.sql
- models/projects/blast/core/ez_blast_metrics.sql
- models/staging/blast/agg_blast_daily_stablecoin_metrics_breakdown.sql
Remove Blast Stablecoin from our Stablecoin v2 pipeline:
daily, weekly, monthly breakdown
aggregated daily blast data
we will still have the fact_blast_stablecoin_transfers + fact_blast_address_balances if we ever want to build v2. 
Data will be stale until we put it back in our stablecoin pipeline. 
production is affected (no data is showing) but it doesnt crash the front end! 
https://app.artemis.xyz/stablecoins?chain=blast
> Remove Blast stablecoin from data pipeline

- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
1. cKES does not have pricing for every day. This is an issue because based on our stablecoin logic we assume when no price the value is 1 dollar. In order to fix this, i make cKES set to the average price for all the days that we have data for. This is hardcoded for now. As we add more stablecoins we may be able to calculate this dynamically. I would say this is not worth it to do it now.
> Stablecoin V2: Fixing cKES metrics

- macros/stablecoins/agg_chain_stablecoin_breakdown.sql
- macros/stablecoins/agg_chain_stablecoin_metrics.sql
1. Added cKES to stablecoin v1 but pricing does not exist everyday
2. In order to fix this we calculated the average over the entire time range manually. Going forward we can change this from a hard code to more dynamic
> Fixing cKES pricing on v1 tables

- models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql
Because of across sometimes the destination chain can equal the source chain. This should be removed from the flows page because the value is not leaving a particular chain.
> C911: Removing Same Chain Inflows and outflows

- macros/p2p/filter_p2p_token_transfers.sql
Flipside is updating their schema's and deprecating solana `fact_swaps`. We need to switch to `ez_dex_swaps`. https://artemisxyz.slack.com/archives/C065QUZV6L8/p1721939110265129
> C911: Updating Solana Schema's

- models/common/dim_contracts.sql
1. Paypal is using hex and needs access for dim_contracts_gold. Adding a view in the common database
> Paypal: Adding Dim Contracts to Art Share 

- macros/p2p/filter_p2p_token_transfers.sql
1. Fixing sql errors in solana p2p token transfers filter after flipside changed the schema
> Solana P2P Token Transfers

- models/staging/optimism/fact_optimism_flows.sql
> added Optimism chain sankey dbt

- models/projects/maker/prod_core/ez_maker_metrics.sql
- models/projects/maker/prod_core/ez_maker_metrics_by_chain.sql
- models/projects/maker/prod_core/ez_maker_metrics_by_token.sql
Add ez metrics by chain to work better with our backend adapter which requires DimensionType.CHAIN
Also changed name of `net_deposit` column to `net_deposits` with an `s`.
> Maker: ez metrics by chain

- models/projects/ton/core/ez_ton_metrics.sql
- models/staging/ton/__ton__sources.yml
- models/staging/ton/fact_ton_fundamental_metrics.sql
- models/staging/ton/fact_ton_transactions.sql
We now can use ton apps raw transaction data from snowflake instead of via a postgres connection. 
Still need to test models downstream.
> Updated Ton to use Raw Transaction 

- models/staging/aptos/fact_aptos_daa_txns_gas_gas_usd_revenue.sql
> Converted Aptos data to incremental

- macros/transfers/get_token_transfer_filtered.sql
- models/projects/ethereum/raw/ez_ethereum_token_transfers.sql
- models/projects/solana/raw/ez_solana_token_transfers.sql
1. Updating filtered token transfers to have full data including mint and burns
2. Adding `ez_token_transfers` for ethereum and solana
> Paypal: EZ Token Transfers Solana and Ethereum

- models/staging/starknet/fact_starknet_transactions.sql
1. Starknet incremental run is borked because it is looking at a column that does not exist: `block_timestamp`
https://artemis.dagster.cloud/prod/runs/8d3d6051-dd72-406a-bcc8-3074efbdff4a?logFileKey=moyhrvtu&selection=%22run_dbt_d2c55%22&logs=query%3A%22run_dbt_d2c55%22
> Fixing Starknet

- macros/stablecoins/agg_chain_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_metrics.sql
- models/metrics/stablecoins/contracts/fact_celo_stablecoin_premint_addresses.sql
There are two issue with the celo stablecoin supply:
1. cUSD is borked (Came from a borked `dim_celo_current_balances` table
2. USDT has a significant premint (Created a `fact_celo_stablecoin_premint_addresses`)
This PR fixes both of these issues
> Stablecoin V2: Celo Stablecoin Supply

- macros/stablecoins/agg_chain_stablecoin_transfers.sql
Fixing stablecoin DQ issue for celo. When changing the transfers table I forgot to divide by 10**decimals
> Stablecoin DQ Issue: Celo

- macros/stablecoins/stablecoin_breakdown.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_category_symbol.sql
1. Create a stablecoin breakdown for Stablecoin and Sector to allow for someone to choose a specific stablecoin(s) when on the all chains page
> Stablecoin V2.5: Stablecoin and Sector Breakdown 

- macros/stablecoins/stablecoin_breakdown.sql
1. Removing the date param from stablecoin breakdown macro
> Stablecoin V2.5: Clean up stablecoin breakdown

- macros/coingecko/avg_coingecko_price_7d.sql
- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
1. Calculate the price of a non USD backed stablecoin based on the last 7 day average of the current price
> Stablecoin V2.5: updating stablecoin pricing for non-usd stablecoins

- models/data_hubs/fact_daily_app_datahub.sql
1. Right now all models that don't have a specified warehouse run on `small`, this seems to be causing issues for deploying when the small warehouse is queued. This should help fix this, by giving it a separate warehouse that is not used by the majority of models
> Updating Datahub Warehouse

- models/staging/coingecko/fact_coingecko_token_metadata.sql
When the categories = `[]` with a coingecko token it is not included in the coingecko metadata table because the CTE does not contain a row for that token (`inner join`). This causes our metadata table to not contain all the tokens that we extract from coingecko as well as not allow us to tag some tokens to apps in sigma. By using a left join we continue to support tokens that do not have an empty array for the categories.
> Updating coingecko metadata

- macros/stablecoins/stablecoin_metrics.sql
1. There is an issue with Ton stablecoin transfers where we are missing some of the transfers. I am currently talking with Ton Apps to try and get this fixed. This is meant to be a short term fix to remove the category breakdown for ton. The outcome will be that the Ton breakdown by category will only show `other`. 
By removing the category breakdown we will show the same thing that is shown on the other `ton` stablecoin breakdowns.
> Stablecoins (TON): Updating stablecoin metrics for ton

- models/projects/ton/core/ez_ton_metrics.sql
Adding stablecoin metrics to ez_ton_metrics table
> [Stablecoin Dashboard] Adding ton stablecoin metrics to ez table

- models/projects/axelar/core/ez_axelar_metrics.sql
- models/staging/axelar/__axelar__sources.yml
- models/staging/axelar/fact_axelar_crosschain_dau_txns_fees_volume.sql
Add DBT models for Axelar fundamental data from Axelarscan API.
Successful test run: http://127.0.0.1:3000/runs/35011b76-3641-49f8-8595-9b2ff1b47827
> replacing old Axelar data with Axelarscan data

- macros/routescan_helpers/convert_routescan_api_daus_for_chain.sql
- macros/routescan_helpers/convert_routescan_api_fees_native_for_chain.sql
- macros/routescan_helpers/convert_routescan_api_txns_for_chain.sql
- models/projects/chiliz/core/ez_chiliz_metrics.sql
- models/staging/chiliz/__chiliz__sources.yml
- models/staging/chiliz/fact_chiliz_dau.sql
- models/staging/chiliz/fact_chiliz_fees.sql
- models/staging/chiliz/fact_chiliz_fees_native.sql
- models/staging/chiliz/fact_chiliz_txns.sql
Daily Chiliz job runs successfully:
> Chiliz: Fundamental metrics

- macros/metrics/get_p2p_metrics.sql
- models/projects/arbitrum/core/ez_arbitrum_metrics.sql
- models/projects/avalanche/core/ez_avalanche_metrics.sql
- models/projects/base/core/ez_base_metrics.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/projects/optimism/core/ez_optimism_metrics.sql
- models/projects/polygon/core/ez_polygon_metrics.sql
- models/projects/solana/core/ez_solana_metrics.sql
- models/projects/tron/core/ez_tron_metrics.sql
- models/staging/tron/fact_tron_p2p_token_transfers.sql
1. Fixing materialization of near by adding `p2p_stablecoin_transfer_volume` to `get_p2p_metrics`. Need to fix the other ez metric tables that also support `get_p2p_metrics` because `get_stablecoin_metrics` also supports this metric.
2. Fixing Tron p2p token transfers to by adding another blacklisted address.
These are all the chains that support p2p metrics:
Re-materialize all the tables: (solana failed but I rematerialized it)
> Customer 911: updating tables to fix issue with near and tron

- macros/stablecoins/stablecoin_metrics.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
1. Updating Ton data to remove the temporary fix of setting tags to null
2. Updating Stablecoin Artemis Filter. There was an error in the model where we should be making sure the to **and** from addresses are not MEV rather than using an `or` and only removing when one is MEV.
To Do:
1. This will require a complete backfill of all the ez metrics tables. I will start with the lower touch chains like `base`, `celo`, `ton` to verify that this is correct and then move to the more expensive chains like `ethereum`, `bsc` and `tron`
2. I may time this to also add the two new stablecoins `AUSD` and `FDUSD`
> Stablecoins: Ton and Artemis Filter

- models/projects/zksync/core/ez_zksync_metrics.sql
Not sure why this didnt fail the pipeline, but we were missing a comma.
> Fixed WAU zksync data

- models/staging/solana/fact_solana_transactions.sql
Our old way was not capturing solana program activity from the instruction layer correctly.
> Updated Solana Activity Monitor transaction table

- models/projects/metis/core/ez_metis_metrics.sql
- models/staging/metis/__metis__sources.yml
- models/staging/metis/fact_metis_dau.sql
- models/staging/metis/fact_metis_fees.sql
- models/staging/metis/fact_metis_fees_native.sql
- models/staging/metis/fact_metis_txns.sql
Adding Metis fundamental metrics models: fees, daus, daily_txns.
Added ez metrics table.
daily_metis_job successfully materializes all assets:
> adding metis fundamental metrics

- models/projects/trader_joe/core/ez_trader_joe_metrics_by_chain.sql
Joe v1 adding txns as swap count. 
Models materialize cleanly and correct data shows in ez metrics table in snowflake.
> adding txns (swap) count to trader_joe

- models/projects/flare/core/ez_flare_metrics.sql
- models/projects/metis/core/ez_metis_metrics.sql
- models/projects/outerlands/core/ez_outerlands_metrics.sql
- models/staging/outerlands/__outerlands__sources.yml
- models/staging/outerlands/fact_outerlands_index_full_universe.sql
Outerlands index
Outerlands Job runs smoothly (set to refresh at 10am everyday):
> Alw outerlands index

- macros/rolling_active_addresses.sql
Small nits, adding distinct for rolling active addresses to make it faster and keep it consistent.
> Made MAU/WAU distinct

- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics.sql
- models/metrics/stablecoins/contracts/fact_avalanche_stablecoin_contracts.sql
Adding a new stablecoin AUSD
1. Added code to both the balances macro and final macro to support adding a new stablecoin. This code forces the user to add the new stablecoin locally but setting the value of the address in `new_stablecoin_address`. This forces the backfill to happen locally for now.
2. I tested this with AUSD on avalanche and it work adding a full backfill of AUSD.
To Do:
Add support in the BE and FE for AUSD
> Stablecoins AUSD: Adding new stablecoin

- models/projects/jupiter/ez_jupiter_metrics_by_chain.sql
Small fix removing unneccessary SQL since Jupiter is only on one chain. Made this change as I was investigating why some jupiter data was stale -> table was omitted from `daily_jupiter_job`
Data in `jupiter.prod_core.ez_metrics_by_chain` looks as expected.
> simplified jupiter ez by chain table as part of fix

- macros/stablecoins/agg_chain_stablecoin_transfers.sql
- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
1. Adding AUSD support on Ethereum. Already backfilled the data will show on the FE tomorrow morning.
2. Fixing near stablecoin transfers. There was a bug in the near stablecoin transfers where the amount was divided by 1e24. This is wrong for both USDC and USDT. This PR fixes this and divides by the correct decimals.
> Stablecoins: Adding AUSD (ethereum) and Fixing Near Stablecoin Transfers

- models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category_chain.sql
I forgot a comma in the config which caused the job to throw an error
> Customer 911: fixing `agg_weekly_stablecoin_breakdown_category_chain`

- models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category_chain.sql
Fixing incremental run on `agg_weekly_stablecoin_breakdown_category_chain`
> Customer 911: Fixing Stablecoin weekly model

- macros/stablecoins/stablecoin_breakdown.sql
Stablecoins symbol by sector is borked because the incremental run is not good a unifying null rows. This PR fixes this issue by making the null category or application be unlabeled rather than `null`.
> Customer 911: Fixing incremental run logic

- models/staging/sui/fact_sui_contracts_silver.sql
Updating the extract step. The new extract step changes the schema. This PR updates that Schema. Incase we need to do a full refresh I `coalesce` to make sure we can still refresh the table properly.
> C911: fixing sui contracts

- models/projects/ethena/ez_ethena_metrics.sql
- models/staging/ethena/fact_ethena_collateral_fees.sql
- models/staging/ethena/fact_ethena_yield_fees.sql
Adding Ethena (ENA) metrics
- New fees fact tables
- Joining existing USDe stablecoin (dau, txns) metrics with new fees in an `ez_metrics` table
Models materialize cleanly:
> Ethena Fundamentals

- .github/workflows/show_changed_models.yml
1. Workflow failed to run with open source contributor. https://github.com/Artemis-xyz/dbt/pull/535
2. This is becuase the output of the first job is not saved. This print shows that the next workflow should not be skipped.
3. This pr updated the output logic of the workflow to make sure that it is actually saved
To Do:
1. Find a way to test this
> Github Open Source Workflow: Update show_changed_models

- models/common/ez_bridge_flows_metrics.sql
Arbitrum wants access to the flows data. Adding it to Art Share
To Do:
1. Rerun the pipeline on dagster
> Adding adding Bridge Flows data to art share

- macros/decentralized_exchanges/fact_dex_priced_tokens.sql
- macros/decentralized_exchanges/fact_uniswap_fork_swap_events.sql
- models/projects/uniswap/raw/fact_uniswap_dex_token_prices.sql
- models/staging/uniswap/fact_uniswap_v2_ethereum_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v2_ethereum_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_arbitrum_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_arbitrum_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_avalanche_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_avalanche_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_base_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_base_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_blast_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_blast_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_bsc_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_bsc_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_ethereum_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_ethereum_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_optimism_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_optimism_swap_events.sql
- models/staging/uniswap/fact_uniswap_v3_polygon_priced_tokens.sql
- models/staging/uniswap/fact_uniswap_v3_polygon_swap_events.sql
1. Adding price of tokens on the uniswap DEX across all chains. The methodology here is we price the tokens in the stablecoin and assume the stablecoin. The token is prices in the stablecoin. Because we track both USD and EUR it will get us the price of tokens in both of these prices. 
To Do:
1. Get the price of ETH and BTC in USD denominated stablecoins
> Uniswap: adding dex token prices for uniswap

- models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
1. Flipside is reporting `wear.near` as having 18 decimals but it has 24 decimals. This PR fixes this for the rainbow bridge.
> C911L fixing flipside decimal error for near

- models/common/__common__sources.yml
- models/common/dim_geo_location_labels.sql
1. Adding support for Geo Labels in Art Share. Request from Enterprise Customer
> Art Share: Adding geo to art share

- macros/decentralized_exchanges/fact_dex_priced_tokens.sql
- models/projects/uniswap/raw/ez_uniswap_price_performance.sql
Fixing uniswap pricing model by removing dust trades. This is not a perfect filter because different tokens have different prices and the price of the token effects how this filter works but right now we can keep it simple
> C911: Fixing uniswap pricing by adding dust filter

- macros/metrics/get_stablecoin_metrics.sql
- macros/stablecoins/stablecoin_breakdown.sql
1. Adding support for the following metrics: `num_p2p_stablecoin_token_holders`, `num_stablecoin_token_holders`
2. These holders are >$.01. Anything less we currently don't count as a holder
To Do:
1. Re-backfill the tables tomorrow (will merge this tomorrow morning)
> Stablecoins: `num_p2p_stablecoin_token_holders`, `num_stablecoin_token_holders`

- macros/metrics/get_stablecoin_metrics.sql
- macros/stablecoins/stablecoin_breakdown.sql
I am currently trying to backfill token holder data but the data has been running for 4 hours with no end in sight. We are still on the first set of models. Because of this I have created a PR to easily revert the change. I will have the re-run the models that finished but that should be easy. If this is not done by 9:30 I will revert the change. 
To Fix:
1. Only run this on the daily models
2. Add more stablecoin warehouses. It has no extract cost and will reduce the queued models
https://artemis.dagster.cloud/prod/runs/235c1451-8d71-4f9a-912d-2be7c59bbdc8?logFileKey=yrfeyfqw&selection=%2A
https://artemis.dagster.cloud/prod/runs/716ba6e0-bbb4-4e47-901d-6bfd3d494234
https://artemis.dagster.cloud/prod/runs/c20bafab-a8e7-4ea4-88d2-88e962c475b7?logFileKey=duanrxnz&selection=%2A
> Incase: removing token holders for stablecoin data

- macros/stablecoins/stablecoin_breakdown.sql
The old code did not compile properly. The two knew columns were left out. This si the compiled code form SF:
```
create or replace transient table PC_DBT_DB.PROD.agg_daily_stablecoin_breakdown_symbol
as
(
select
date_trunc('day', date) as date_granularity
, symbol
, count(distinct case when stablecoin_daily_txns > 0 then from_address end) as stablecoin_dau
, sum(stablecoin_transfer_volume) as stablecoin_transfer_volume
, sum(stablecoin_daily_txns) as stablecoin_daily_txns
, case 
when sum(stablecoin_daily_txns) > 0 then sum(stablecoin_transfer_volume) / sum(stablecoin_daily_txns) 
else 0
end as stablecoin_avg_txn_value
, count(distinct case when artemis_stablecoin_daily_txns > 0 then from_address end) as artemis_stablecoin_dau
, sum(artemis_stablecoin_transfer_volume) as …
```
> Stablecoins: fix stablecoin token holders code

- models/projects/uniswap/raw/ez_uniswap_price_performance.sql
NYSE opterating hours are 9:30 to 4. Since we trunc by hour we say it is 9 to 4 exclusive of 4pm. 
This was Flagged by @alexwes: https://artemisxyz.slack.com/archives/C06GXJ5JTL6/p1729790206719149?thread_ts=1729720536.202329&cid=C06GXJ5JTL6
> Uniswap: fixing NYSE operating hours

- macros/metrics/get_stablecoin_metrics.sql
1. Update column name `stablecoin_token_holder_count` to `token_holder_count` for the `ez_metric` table for stablecoins and not for chains. This is because when thinking about AUSD as a stablecoin you what the token_holder_count for AUSD and for ethereum you would want the `stablecoin_token_holder_count` which would be different then `token_holder_count`. `token_holder_count` count for a chain should be the number of holders of the native token.
> Stablecoins: Update Column Name for Stablecoins

- macros/address_balances/address_credits_dune.sql
- macros/address_balances/address_debits_dune.sql
- macros/contracts/distinct_contract_addresses.sql
- macros/decode/token_transfer_events.sql
- macros/stablecoins/agg_chain_stablecoin_transfers.sql
- models/dimensions/contracts/dim_mantle_contract_addresses.sql
- models/dimensions/current_balances/dim_mantle_current_balances.sql
- models/metrics/stablecoins/contracts/fact_mantle_stablecoin_contracts.sql
- models/metrics/stablecoins/transfers/fact_mantle_stablecoin_transfers.sql
- models/staging/mantle/__mantle__sources.yml
- models/staging/mantle/fact_mantle_address_balances_by_token.sql
- models/staging/mantle/fact_mantle_address_credit_by_token.sql
- models/staging/mantle/fact_mantle_address_debit_by_token.sql
- models/staging/mantle/fact_mantle_p2p_stablecoin_transfers.sql
- models/staging/mantle/fact_mantle_token_transfers.sql
1. Adding underlying tables to support stablecoin metrics. The data is currently being ingested from Dune where we build the token transfers table as well as dim contracts table. We can then create the stablecoin transfers and p2p stablecoin transfers table as well as the balances pipeline.
To Do:
1. Create the stablecoin v3 tables (balance, and metric tables)
> Stablecoins: adding underlying Mantle tables to support stablecoins

- macros/stablecoins/stablecoin_metrics_artemis.sql
We now support two types of MEV tags, `farming-mev` and `mev`. Because of this I want to remove transactions based on if the app is tagged to the category MEV rather than if the app is `mev`. This will scale better as our MEV tagging becomes more nuanced and we refine the types of MEV we tag.
> Stablecoins: updating artemis stablecoin metrics

- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_application.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_application_chain.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_application_symbol.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_category.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_category_chain.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_category_symbol.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_category_symbol_chain.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_chain.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_symbol.sql
- models/metrics/stablecoins/breakdowns/daily/agg_daily_stablecoin_breakdown_symbol_chain.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_category.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_category_chain.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_category_symbol.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_category_symbol_chain.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_chain.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_symbol.sql
- models/metrics/stablecoins/breakdowns/monthly/agg_monthly_stablecoin_breakdown_symbol_chain.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_category.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_category_chain.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_category_symbol.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_category_symbol_chain.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_chain.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_symbol.sql
- models/metrics/stablecoins/breakdowns/weekly/agg_weekly_stablecoin_breakdown_symbol_chain.sql
Creating specific warehouses for the `daily`, `weekly` and `monthly` stablecoin models. This should help speed up the materializations of a full refresh.
> Stablecoins: updating stablecoin warehouses

- models/staging/cardano/fact_cardano_fees_and_revenue.sql
- Update to pull from new upstream source that returns `gas_usd`
- Convert back to native units of ADA 
Executed compiled SQL query in Snowflake and data looks good
> Update Cardano Fees to new Upstream Source

- requirements.txt
- syncenv
- Hardcode dbt-core sub-version to align with backend repo and enable partial parsing
> Specify dbt-core subversion, install using uv in syncenv script

- models/staging/jupiter/fact_jupiter_perps_txs.sql
- Removing extra `)`
- Use `big_endian_hex_to_decimal` UDF for computing price 
- Executed compiled SQL 👍
> Fix fact_jupiter_perps_txs model

- models/projects/mantle/core/ez_mantle_stablecoin_metrics_by_address.sql
- models/staging/mantle/fact_mantle_stablecoin_balances.sql
- models/staging/mantle/fact_mantle_stablecoin_metrics_all.sql
- models/staging/mantle/fact_mantle_stablecoin_metrics_artemis.sql
- models/staging/mantle/fact_mantle_stablecoin_metrics_p2p.sql
For Mantle:
1. Adding Stablecoin metric and balances models.
2. Adding Stablecoin metrics by address
To Do:
1. Dune data is not backfilled currently only data back to oct. 22nd. Working with Dune to get this fixed then I need to backfill the transfers tables
> Stablecoins: Mantle Stablecoin Models

- models/staging/osmosis/fact_osmosis_trading_fees.sql
Quick fix to Osmo data that was causing below DQ issue:
Fix by filtering for any trader where the fee paid is > 1,000,000 USD.
Query compiles:
> osmo fees fix

- models/projects/gmx/raw/fact_gmx_perps_token_prices.sql
Making sure all of these tables have the same columns so end users know what to expect.
> Standardizing column names for GMX perps pricing

- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/l30d_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
- macros/stablecoins/stablecoin_metrics_p2p.sql
- macros/wallets/distinct_eoa_addresses.sql
- models/dimensions/contracts/dim_ton_contract_addresses.sql
- models/dimensions/wallet/dim_ton_eoa_addresses.sql
- models/dimensions/wallet/dim_tron_eoa_addresses.sql
- models/projects/ton/raw/ez_ton_p2p_stablecoin_transfers.sql
- models/staging/ton/fact_ton_p2p_stablecoin_transfers.sql
- models/staging/ton/fact_ton_token_transfers.sql
1. Cleaning up the TON stablecoin pipeline. TON now follows the same pipeline as the other chains where all the models are `fact` models and the final model is an `ez` model.
> C911 [TON]: Updating the ton stablecoin pipeline

- models/staging/osmosis/fact_osmosis_gas_gas_usd.sql
- models/staging/osmosis/fact_osmosis_trading_fees.sql
Added much more strict filters for Osmosis fees since DQ issues kept popping up. 
I blacklisted specific addresses that were causing issues. 
I also lowered the maximum limit on trading fees allowed for a single trade from $1,000,000 to $10,000 in both `fact_osmosis_gas_gas_usd` and `fact_osmosis_trading_fees` since both are susceptible to the same type of data quality issue. 
This change assumes there will be no real trades generating more than $10,000 in fees. Considering the default fee for a pool is 0.1% ([docs](https://docs.osmosis.zone/overview/educate/osmo/#taker-fees), that would mean a single trade of $10,000,000 in value, which seems highly unlikely in any near future for Osmosis.
Osmosis Fees actually look normal for once:
> osmosis strict filter

- models/projects/metaplex/core/ez_metaplex_metrics.sql
Added unique signers and new holders metrics to `ez_metaplex_metrics`.
Added required metrics in backend PR.
Tested both metrics work locally:
**NEW_HOLDERS**
**UNIQUE_SIGNERS**
> Metaplex: add unique signers and new holders

- models/projects/bitcoin/core/ez_bitcoin_metrics.sql
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/staging/bitcoin/fact_bitcoin_etf_flows.sql
- models/staging/ethereum/fact_ethereum_etf_flows.sql
Need to add aggregate ETF metrics to `ez_metrics` tables for both `bitcoin` and `ethereum` in order to be able to work with our current adapter functions.
> add etf to ez metrics table

- models/staging/drift/__drift__sources.yml
- models/staging/drift/fact_drift_parsed_logs.sql
Compiled dedup logic correctly dedups for data that was written multiple times (ordering by float column and only one record appears)
> Add Drift Parsed Logs Model

- models/metrics/stablecoins/breakdowns/_test_agg_daily_stablecoin_breakdown_silver.yml
Not null test is failing for some reason. This issue is coming from the server being in UTC time and expecting data for the 20th but the underlying models haven't materialized for yday
> Stablecoins: removing not null test

- models/staging/rainbow_bridge/fact_rainbow_bridge_flows.sql
> Near: updating rainbow bridge flows

- models/staging/raydium/fact_solana_dex_token_prices.sql
> Fixed Raydium Dex Volumes

- models/projects/base/core/ez_base_metrics.sql
- models/projects/tron/core/ez_tron_metrics.sql
- Supporting DAU over 100 for both base and tron
- the data existed in the backed just was not in the final ez metrics table
> DAU over 100: Base and Tron

- macros/decode/token_transfer_events.sql
1. Celo Stablecoin transfers are borked.
2. The issue is because SF/DBT does not know how to unify when one of the incremental unique keys are null. 
3. Switching null index for -1 index celo token transfers used as gas
> C911: Celo Stablecoin Data

- models/projects/trader_joe/core/ez_trader_joe_metrics.sql
changed column references originally made in [this PR](https://github.com/Artemis-xyz/dbt/commit/9af37d08711c419f534de86e37dc2e19a2114d8e).
Outerlands job runs now.
As does trader joe:
> correct column reference

- models/projects/celo/raw/ez_celo_transfers.sql
- models/staging/celo/fact_celo_native_token_transfers.sql
1. Adding celo native token transfers from traces
2. Creating `ez_celo_transfers` that contains both native and erc 20 transfers
> Celo: Transfers

- macros/rolling_active_addresses.sql
- models/projects/across/raw/ez_across_bridge_transfers.sql
- models/projects/synapse/raw/ez_synapse_bridge_transfers.sql
- seeds/chain_ids.csv
> Bridges: fixing transfers

- models/staging/outerlands/fact_outerlands_asset_weights_for_month_start.sql
- Added incremental logic to `fact_outerlands_fundamental_index_performance` in order to preserve historical data.
- This is particularly relevant in the case that the underlying data changes (eg. we add support for USDe on Solana -> causes historical daus, txns, etc to increase -> its historic weight changes in the index and thus its historical performance). These underlying changes should only affect future index performance.
- Only made this query incremental since it is the one that interfaces with the underlying data. All other tables rely on this table, so no need to make downstream tables incremental as well.
Ran the compiled dbt code for the model and, as expected, it returned no rows.
Also ran the compiled dbt code with a dummy date value of '2024-12-01' to see its behavior if it …
> index monthly weights to incremental

- macros/pendle/get_pendle_tvl_for_chain_by_token.sql
Pendle TVL broke again today - reason is we were filtering by native TVL and not USD TVL which is more indicative of the true value.
> adding price multiplier to convert to USD

- models/staging/ton/fact_ton_transactions.sql
This should resolve https://artemis.dagster.cloud/prod/runs/9499821a-fd53-487c-9013-9581aa85a69d. There were duplicate rows of tx_hash in the incremental portion of the model. Upon inspection, the duplicate tx_hash rows were exactly the same, so I just added a "distinct" which should resolve the error.
Eg.
> Fix ton transactions model

- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
Added this to `fact_ethereum_stablecoin_contracts`
`('FRAX', '0x853d955acef822db058eb8505911ed77f175b99e', 18, 'frax', 0)`
> Adding frax on eth

- models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
Adding sUSD and AUSD on solana.
Checked both supply number, close enough for me.
sUSD might prices might not be right because there isn't pricing data shown on coingecko but there is an api for it, will check back again in 2 weeks time.
> Adding sUSD and AUSD on Solana

- models/projects/sui/core/ez_sui_stablecoin_metrics_by_address.sql
- models/staging/sui/fact_sui_p2p_stablecoin_transfers.sql
- models/staging/sui/fact_sui_stablecoin_balances.sql
- models/staging/sui/fact_sui_stablecoin_metrics_all.sql
- models/staging/sui/fact_sui_stablecoin_metrics_artemis.sql
- models/staging/sui/fact_sui_stablecoin_metrics_p2p.sql
- models/staging/sui/fact_sui_stablecoin_transfers.sql
fact_sui_stablecoin_balances
fact_sui_stablecoin_metrics_all
fact_sui_stablecoin_metrics_artemis
fact_sui_stablecoin_metrics_p2p
ez_sui_stablecoin_metrics_by_address
all these uses the macro for SUI but it wasn't updated, which causes the job to fail for these 5, creating empty table.
I have updated it.
I also included the changes for
fact_sui_stablecoin_transfers
fact_sui_p2p_stablecoin_transfers
such that it does an incremental refresh for the rest, and full refresh for a new stablecoin address.
> fixing sui stablecoin pipeline

- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_balances.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
1. Created macro in this PR to waterfall prices and maintain stablecoin prices for nonusd stablecoins in a single place. Implementing this marco in the other places in the code that it can be used. 
PR: https://github.com/Artemis-xyz/dbt/pull/518/files
Marco In main Repo: https://github.com/Artemis-xyz/dbt/blob/main/macros/coingecko/waterfall_stablecoin_prices.sql
> Stablecoins Cleanup: using macro to waterfall prices

- models/data_hubs/fact_daily_bam_datahub_v2.sql
Remove 'arbitrum' filter on bam datahub v2 b/c I've integrated the rest of the chains already (except Solana but that's fine for now)
Ran locally
> Remove arbitrum filter on bam datahub v2

- models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Adding an onchain explorer datahub to port to postgres to grab the top 10000 untagged contracts/applications for each chain
Ran locally
> Add onchainexplorer datahub

- models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
There were duplicate address rows because of casing on the full outer join.
Ran locally
> Fix labeling duplicates issue

- models/dimensions/__dimension__sources.yml
- models/dimensions/labeling/dim_all_addresses_labeled_gold.sql
- models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
- models/dimensions/labeling/dim_all_addresses_silver.sql
- models/dimensions/labeling/dim_all_apps_silver.sql
- models/dimensions/labeling/dim_legacy_sigma_tagged_contracts.sql
This keeps the sigma snapshots updated, although we will have to manually upload the new applications if they are created in Sigma. This is because dim_new_apps_post_sigma contains a hodgepodge of namespaces where some are legitimate but others need to be mapped to parent namespace to be legit.
Also made all addresses lowercase to standardize them and also modified labels table to be full refresh so that they can handle category changes when we modify application categories.
Ran locally
> Update Sigma Snapshot

- models/dimensions/dim_app_datahub.sql
Fix deployed on column in dimappdatahub such that it doesn't show chains where only trace-level addresses are labeled.
Ran locally
> Fix deployed on column in dimappdatahub

- models/data_hubs/fact_daily_onchainexplorer_datahub.sql
- models/staging/arbitrum/fact_arbitrum_one_bridge_transfers.sql
Fix onchain explorer datahub numbers (I was grabbing past 31 days and not past 30 days and I was also doing AVG(dau) on a daily basis instead of summing)
Fix arbitrum table where block timestamp is null for today from flipside
Ran locally for both
> Fix onchain explorer datahub numbers and also arbitrum fix

- models/staging/injective/injective_trending_daily_v2.sql
- models/staging/injective/injective_trending_weekly_monthly_v2.sql
- models/staging/stellar/stellar_trending_daily_v2.sql
- models/staging/stellar/stellar_trending_weekly_monthly_v2.sql
- models/staging/sui/sui_trending_daily_v2.sql
- models/staging/sui/sui_trending_weekly_monthly_v2.sql
Some referenced tables in BAM trending cards V2 are still referencing V1 tables. This fixes it.
Ran locally and checked on localhost.
> Change tables to v2 in trending dbt models

- models/data_hubs/fact_daily_onchainexplorer_datahub.sql
This change modifies the average DAU on the onchain explorer table such that days where there were no interactions with the contract are NULL, but are still shown as 0 in the 30 day historical mini-chart per @crystaltai 's request
> Continue revising onchainexplorer table

- models/projects/base/raw/ez_base_transfers.sql
There were duplicate rows in ez_base_transfers, so added a distinct to fix the dbt model.
Ran locally to check
> Fix incremental distinct rows for ez_base_transfers

- macros/rwa/rwa_balances.sql
Have to use a combination of `get_multiple_coingecko_price_with_latest` and add a specific left join for TBILL since `dim_coingecko_token_map` does not support the correct contract address on Ethereum.
> fix pricing issues in rwa pipeline

- models/dimensions/__dimension__sources.yml
- models/dimensions/events/dim_events_silver.sql
- Combine all ABIs and extract event info for event log decoding
> Obtain All Event Info

- macros/bridge/stargate_veSTGholders.sql
- models/projects/stargate/core/ez_stargate_metrics_top100veSTGholders.sql
- models/staging/stargate/dim_stargate_arbitrum_veSTGholders.sql
- models/staging/stargate/dim_stargate_avalanche_veSTGholders.sql
- models/staging/stargate/dim_stargate_bsc_veSTGholders.sql
- models/staging/stargate/dim_stargate_ethereum_veSTGholders.sql
- models/staging/stargate/dim_stargate_optimism_veSTGholders.sql
- models/staging/stargate/dim_stargate_polygon_veSTGholders.sql
- models/staging/stargate/fact_stargate_top100veSTGholders.sql
Added the 6 chains that have veSTG holders:
- arbitrum
- avalanche
- bsc
- ethereum
- optimism
- polygon
Created the fact table and ez_metrics table as well:
ez_metrics_top100veSTGholders materialized successfully
> veSTG top 100 holders

- macros/create_ez_transactions.sql
- models/projects/sei/raw/ez_sei_transactions_v2.sql
- models/projects/solana/raw/ez_solana_transactions_v2.sql
- models/staging/arbitrum/fact_arbitrum_transactions_v2.sql
- models/staging/avalanche/fact_avalanche_transactions_v2.sql
- models/staging/base/fact_base_transactions_v2.sql
- models/staging/bsc/fact_bsc_transactions_v2.sql
- models/staging/ethereum/fact_ethereum_transactions_v2.sql
- models/staging/mantle/fact_mantle_transactions_v2.sql
- models/staging/near/fact_near_transactions_v2.sql
- models/staging/optimism/fact_optimism_transactions_v2.sql
- models/staging/polygon/fact_polygon_transactions_v2.sql
- models/staging/sei/fact_sei_evm_transactions_v2.sql
- models/staging/sei/fact_sei_transactions_v2.sql
- models/staging/sei/fact_sei_wasm_transactions_v2.sql
- models/staging/solana/fact_solana_transactions_v2.sql
- models/staging/tron/fact_tron_transactions_v2.sql
Modified chain-level transactions V2 tables such that they are able to incrementally take new historical labels as well. Basically, every single incremental run will include all rows in the transactions table where the contract address is labeled, regardless of how recent that row is.
> Modify chain transactions v2 tables

- models/staging/jupiter/fact_jupiter_limit_order_fees_silver.sql
- models/staging/jupiter/fact_jupiter_swap_metrics.sql
- models/staging/jupiter/fact_jupiter_swap_txs.sql
Ran full refresh on Jupiter tables, then tested to make sure incremental runs did not affect historical data/change the values. Part of the issue was due to pricing of some tokens but also there was an issue with the incremental logic since there were nulls in the inner_index column which is used as a unique_key.
> filter tokens and edit incremental logic

- models/staging/across/fact_across_v3_filledrelay.sql
- models/staging/across/fact_across_v3_fundsdeposited.sql
There were duplicate rows for fact_across_v3_filledrelay and fact_across_v3_fundsdeposited
Ran locally
> Add distinct to across filledrelay and fundsdeposited

- models/metrics/stablecoins/contracts/fact_sui_stablecoin_premint_addresses.sql
- models/staging/sui/fact_sui_stablecoin_transfers.sql
Change the is_mint and is_burn logic such that the transfer_volume reflects correct amount after accounting for premints.
> Fix SUI transfer volume

- models/projects/solana/core/ez_solana_metrics_by_contract_v2.sql
- models/projects/solana/raw/ez_solana_transactions_v2.sql
- models/staging/solana/fact_solana_transactions_v2.sql
Increased the lookback days for solana transactions to 30 days on a daily incremental run and 90 days every saturday so that onchain explorer for solana will look normal (since it looks at up to T-30 on a daily basis).
Checked locally.
> Extend solana incremental lookback days

- models/projects/jito/core/ez_jito_metrics.sql
- models/projects/meteora/core/ez_meteora_metrics.sql
Jito
- Fix to sum tip_revenue + management/withdrawal fees as revenue
Meteora
- Rename column to what the adapter expects
- Ran reverse ETL and it works.
> fix jito revs and meteora col name

- macros/p2p/p2p_token_transfers.sql
- models/staging/near/fact_near_transactions.sql
- models/staging/near/fact_near_transactions_v2.sql
Add a distinct to near transactions and p2p token transfers because flipside is providing us with duplicate rows.
Ran locally. Full refresh has been ran on the fact_transactions and ez_transactions tables for near already.
> Add distinct to near transactions and p2p token transfers

- models/staging/polygon_zk/fact_polygon_zk_daa_txns_gas_usd.sql
- `txns` and `dau` within Polygon ZK ez_metrics table were both VARIANT type
- Casting to `NUMBER` so we can Iceberg-ify the table
> Fix types in polygon_zk fact table

- models/staging/across/fact_across_complete_transfers.sql
`fact_across_complete_transfers` was missing 2 columns which caused `ez_across_transfers` to break. 
Ran locally
> Add columns to across model

- macros/rwa/rwa_balances.sql
- models/staging/arbitrum/fact_arbitrum_events.sql
- models/staging/rwa/addresses/fact_ethereum_rwa_addresses.sql
- Quick change to the pricing data for RWA balances
- TLDR is USDY is actually 2 tokens, one that circulates and is held by users, and one that is held centrally in certificate form for a period of time before it can be received by end users. We were not tracking the certificate for of USDY. 
- Since coingecko does not support that specific contract address, I added an additional join for the case when the symbols match but the contract addresses do not. 
Notes:
- The pricing around RWAs is getting a bit unwieldy and the query is becoming complicated to read and debug, need to come up with a better solution to this pricing data
- We are still missing tracking of USDY across Sui, Aptos and Noble
Our values are now much more in line with the expected values:
> add price handling for USDY in certificate form

- models/staging/arbitrum/fact_arbitrum_decoded_events.sql
- models/staging/arbitrum/fact_arbitrum_events.sql
- models/staging/avalanche/fact_avalanche_decoded_events.sql
- models/staging/avalanche/fact_avalanche_events.sql
- models/staging/base/fact_base_decoded_events.sql
Arbitrum sample:
Avalanche sample:
> add arb/avax decoded events + use chain specific warehouse

- models/projects/near/core/ez_near_metrics.sql
- models/staging/near/__near__sources.yml
- models/staging/near/fact_near_dex_volumes.sql
- models/staging/near/fact_near_rhea_finance_volumes.sql
… volumes sheet and ezm table
Potential issues: We do not have a big spike on 02/20/2025, and we are missing data from 4/20/2022 to 4/20/2023 (albeit, somewhat negligible relative to their cumulative volume)
> Rhea Finance DEX Volumes Fix

- models/projects/aerodrome/core/ez_aerodrome_metrics_by_chain.sql
Fix for Aerodrome ez metric by chain. Error was that there was a missing comma but also there was a duplicate column name.
> fix aero by chain

- models/__global__schema.yml
- Re-adding metrics removed in [this commit](https://github.com/Artemis-xyz/dbt/commit/13a995b711f8d699773123d8641e434b1ebbdd0d)
> Add l1_cash_flow_metrics

- models/dimensions/labeling/_test_dim_all_addresses_labeled_silver.yml
- models/dimensions/labeling/_test_dim_all_addresses_silver.yml
- models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
- models/dimensions/labeling/dim_global_labeled_addresses.sql
- models/staging/jito/fact_jitosol_stake_accounts.sql
- models/staging/jito/fact_jitosol_tvl.sql
Add workflow to integrate addresses derived from protocols into labeling system so that downstream TVL, balances, and other metric calculations can pull from the addresses within the labels table.
Tested locally
> Add global workflow to labeling pipeline

- models/staging/arbitrum/fact_arbitrum_transactions_v2.sql
- Enable table clustering on `(to_date(block_timestamp), app)` for `fact_arbitrum_transactions_v2`
- Ran `alter table fact_arbitrum_transactions_v2 CLUSTER BY (to_date(block_timestamp), app);`
- Executed incremental run
> Add clustering on fact_arbitrum_transactions_v2

- models/projects/arbitrum/core/ez_arbitrum_metrics_by_category_v2.sql
- models/projects/avalanche/core/ez_avalanche_metrics_by_category_v2.sql
- models/projects/base/core/ez_base_metrics_by_category_v2.sql
- models/projects/bsc/core/ez_bsc_metrics_by_category_v2.sql
- models/projects/ethereum/core/ez_ethereum_metrics_by_category_v2.sql
- models/projects/mantle/core/ez_mantle_metrics_by_category_v2.sql
- models/projects/near/core/ez_near_metrics_by_category_v2.sql
- models/projects/optimism/core/ez_optimism_metrics_by_category_v2.sql
- models/projects/polygon/core/ez_polygon_metrics_by_category_v2.sql
- models/projects/sei/core/ez_sei_metrics_by_category_v2.sql
- models/projects/solana/core/ez_solana_metrics_by_category_v2.sql
- models/projects/tron/core/ez_tron_metrics_by_category_v2.sql
BAM category_v2 was dependent on fact_transactions_v2 instead of subcategory dbt model. This fixes it.
Ran locally for arbitrum
> Fix BAM category dependencies

- models/staging/ethereum/fact_ethereum_amount_staked_silver.sql
Native block rewards:
BG:
We don't have every slot number in `fact_validator_balances` in `fact_blocks`.
Because we read it everyday instead of every slot number.
Hence:
To fill NULL balances, I decided to forward fill
Reasons:
1. The margin of error here is less 0.01% which I think is reasonable to forgo
2. ETH staking wouldn't change much for a day, due to how it works, where there is a limited number of amount being able to stake each day, and there is a queue. In reality there wouldn't be much changes within a 24hour period.
What changes were made:
Now we forward fill balances for each date. Created a Date spine to support this change as well.
> Fix eth block rewards native

- models/metrics/contracts/_test_fact_arbitrum_contracts.yml
- models/metrics/contracts/_test_fact_avalanche_contracts.yml
- models/metrics/contracts/_test_fact_base_contracts.yml
- models/metrics/contracts/_test_fact_blast_contracts.yml
- models/metrics/contracts/_test_fact_bsc_contracts.yml
- models/metrics/contracts/_test_fact_ethereum_contracts.yml
- models/metrics/contracts/_test_fact_linea_contracts.yml
- models/metrics/contracts/_test_fact_optimism_contracts.yml
- models/metrics/contracts/_test_fact_polygon_contracts.yml
- models/metrics/contracts/_test_fact_scroll_contracts.yml
- models/metrics/contracts/_test_fact_zora_contracts.yml
- models/staging/near/_test_fact_near_contracts.yml
- models/staging/solana/_test_fact_solana_contracts.yml
- models/staging/solana/_test_fact_solana_issuance_silver.yml
- Data is written actually at the weekly granularity so the tests were misconfigured
- Solana epochs aren't mapped cleanly to dates so pushing back the test to fail after 5 days instead of 3
> Update recent values tests for contracts and solana issuance

- models/__global__schema.yml
- models/projects/gains_network/core/ez_gains_network_metrics.sql
- models/projects/gains_network/core/ez_gains_network_metrics_by_chain.sql
- models/staging/gains/__gains__sources.yml
- models/staging/gains/fact_gains_data_v8_v9.sql
Test Plan:
Dagster extract runs successfully. ✅ 
All models compile. ✅ 
Data looks good ✅ 
Note: filtered `fact_gains_trading_volume_unique_traders` by `where chain is not null` in the ez metrics query to make sure we don't double count.
> gains v8 v9 volume and traders

- models/staging/debridge/__debridge__sources.yml
- models/staging/debridge/_test_fact_debridge_metadata.yml
- models/staging/debridge/fact_debridge_order_metadata.sql
- models/staging/debridge/fact_debridge_transfers_with_price_and_metadata.sql
- models/staging/debridge/fact_debridge_transfers_with_prices.sql
Fixed Bug where ETH debridge asset wasn't priced properly. This was because ETH had the 0x000... contract address. 
No longer null values in amount_sent in the image below:
Added Skeleton for debridge metadata. Not super accurate / still WIP because there are 939957 null occurrences.
> Added debridge metadata

- models/projects/ton/core/__ton__schema.yml
- models/projects/ton/core/ez_ton_metrics.sql
- models/staging/ton/__ton__sources.yml
- models/staging/ton/fact_ton_minted.sql
- models/staging/ton/fact_ton_supply_data.sql
fact_ton_supply_data
Added supply data into ez_metrics table
ran reverse etl
> Ton supply side data

- models/staging/jupiter/fact_jupiter_swap_metrics.sql
Our data for recent days showing ~500m in volume was incorrect. The root cause is a peculiarity with how SQL handles NULL values in filters. This was causing some swaps to be filtered out from the final aggregation.
I also noticed our data around dates like Jan 19th, when the TRUMP token launched, seem to be significantly smaller than Dune's data by up to 50% on some days. After poking around it seems there is a difference in methodology. Dune/DFL calculate volume as the sum of all DEX swaps executed as a result of a Jupiter swap. That means if I want to swap 1 USDC for 1 USDT, and Jupiter finds the best route for this to be swapping 1 USDC -> 1 PYUSD then 1 PYUSD -> 1 USDT, this will be counted as $2 in volume instead of $1. This reflects the amount of DEX volume that is …
> fix jupiter agg volume

- models/projects/injective/core/ez_injective_metrics.sql
- models/staging/injective/fact_injective_defillama_tvl_and_dexvolumes.sql
- models/staging/injective/fact_injective_unlocks.sql
Add: fact_injective_unlocks table to staging layer
- This table pulls INJ unlocks from raw flipside logs
Add: INJ supply data to injective ez table
Add: defillama queries to fetch injective TVL & dex volumes into ez table
Modify: re-organized & renaming of injective ez-table for clarity & readability
*Note: circulating supply value is above Coingecko & Tokenomist. Our value includes emissions_native. If we were to exclude emissions_native our value would be equal to Coingecko & Tokenomist
> April Supply Data Refresh - Injective

- models/common/fundamental_data_by_application.sql
- models/common/fundamental_data_by_category.sql
- models/common/fundamental_data_by_chain.sql
- models/common/fundamental_data_by_contract.sql
- models/common/fundamental_data_by_subcategory.sql
> Add Views Atop BAM Data to Common Schema

- models/projects/arbitrum/core/__arbitrum__schema.yml
- models/projects/gains_network/core/ez_gains_network_metrics.sql
- models/projects/gains_network/core/ez_gains_network_metrics_by_chain.sql
- models/projects/rabbitx/core/ez_rabbit_x_metrics.sql
- models/projects/rabbitx/core/ez_rabbit_x_metrics_by_chain.sql
- Disable models to silence freshness checks
> Disable Gains and RabbitX Models

- models/projects/convex/raw/fact_convex_pools.sql
- models/projects/gains_network/core/ez_gains_network_metrics.sql
- models/projects/gains_network/core/ez_gains_network_metrics_by_chain.sql
- models/projects/rabbitx/core/ez_rabbit_x_metrics.sql
- models/projects/rabbitx/core/ez_rabbit_x_metrics_by_chain.sql
- models/staging/gains/_test_fact_gains_data_v8_v9.yml
- models/staging/injective/_test_fact_injective_revenue_silver.yml
- models/staging/level_finance/_test_fact_level_finance_trading_volume.yml
- models/staging/level_finance/_test_fact_level_finance_unique_traders.yml
- models/staging/rabbitx/_test_fact_rabbitx_unique_traders.yml
- seeds/supply/hivemapper/hivemapper_daily_premine_unlocks.csv
- Relevant Slack [Thread](https://artemisxyz.slack.com/archives/C05S8H76M08/p1745799500320679)
- Fixing EVM Flipside Migration column for Convex
- Turning on gains and rabbitx models again
- Removing test on rabbitx unique traders that's no longer used
- Adding test for gains v8/v9. Removing old test for api that is no longer updated.
- Lengthening lookback for injective revenue silver test and level finance tests
- Updating col name for hivemapper to `premine_unlocks_native`
Gains
Rabbitx
Level Finance
Injective Revenue Silver
Convex (sql compiles and executes)
> Various Oncall Fixes

- models/projects/blast/core/ez_blast_metrics.sql
- Blast has been deprecated by Flipside
- Disabling this model now as all of the relevant jobs have been turned off, and we'd like to disable the freshness alert
> Disable Blast EZ Model to Silence Freshness Alert

- macros/nft/nft_trading_volume.sql
- models/__global__sources.yml
- models/staging/magiceden/fact_magiceden_solana_transactions.sql
- Flipside has moved the `FACT_NFT_SALES` table from the `NFT` schema to the`SOLANA_SHARE`
- Updating relevant DB relations and dbt sources
```
SHOW TABLES IN SCHEMA SOLANA_FLIPSIDE.SOLANA_SHARE;
```
> Update FACT_NFT_SALES Schema

- models/projects/babylon/core/ez_babylon_metrics.sql
- models/projects/babylon/core/ez_babylon_metrics_by_chain.sql
- models/staging/babylon/__babylon_sources__.yml
- models/staging/babylon/fact_babylon_metrics.sql
- models/staging/babylon/fact_babylon_tvl.sql
**Key Notes:**
1. TVL numbers from the start of the data until 4-28-2025 are seeded from the defillama API. For all dates after 4-25-2025 tvl is pulled directly from Babylon's API
2. CAD write up for Babylon will be a fast follow
> Babylon Project Page - v1

- macros/address_balances/forward_filled_address_balances.sql
- In https://github.com/Artemis-xyz/dbt/pull/1257/files#diff-f4f2ff9b6164c2f47703b9f0761c3d62b530f72d657bdb0b7f4b70020f43f9cc we modified the `forward_filled_address_balances` but were missing the `decimals` column from the `old_balances` CTE
Compiled SQL
SQL with `decimals` col added to the `old_balances` CTE
> Fix Foward Filled Address Balances Macro

- macros/nft/nft_trading_volume.sql
- models/__global__sources.yml
- models/staging/injective/_test_fact_injective_revenue_silver.yml
- models/staging/magiceden/fact_magiceden_solana_transactions.sql
- models/staging/metaplex/fact_metaplex_sales.sql
- Updating schema from `SOLANA_SHARE` to `NFT`
- Loosening interval of test on `fact_injective_revenue_silver` due to off-by-one error
> Update Flipside Solana NFT Schema

- models/projects/level_finance/core/ez_level_finance_metrics.sql
- Disable `ez_level_finance_metrics` to prevent it from being included in freshness tests
- Turned off job + remove project page
> Disable ez_level_finance_metrics

- models/metrics/stablecoins/breakdowns/_test_agg_daily_stablecoin_breakdown_with_labels_silver.yml
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels.sql
- models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql
This is part one of the label migration:
1. Creating the two core stablecoin tables with updated labels. Next it will be important to update the FE logic to support this change and make sure nothing breaks. The largest issue right now will be the Categories and Applications have new names in the table.
> Part 1: Stablecoin Label Migration

- macros/wallets/distinct_eoa_addresses.sql
- models/dimensions/contracts/dim_flipside_near_contracts.sql
- models/staging/near/fact_near_contracts.sql
- models/staging/near/fact_near_da_metrics.sql
- Near actions tables have been deprecated in favor of `ez_actions`
- Docs for new table in question https://flipsidecrypto.github.io/near-models/#!/model/model.near_models.core__ez_actions
- `fact_near_da_metrics`
Prod
Compiled SQL
- `fact_near_contracts`
- `dim_flipside_near_contracts`
- `dim_near_eoa_addresses`
Can't verify the prod data because it's a view that no longer works
> Update near actions

- models/projects/movement/core/ez_movement_metrics.sql
- models/staging/movement/__movement__sources.yml
- models/staging/movement/fact_movement_fundamental_data.sql
DAUs
Txns
Chain Fees
Still waiting on confirmation from the team since our data differs from their explorer (eg. our total transaction count is 25% lower than the explorer, 1.8m vs 2.4m)
> initial movement dbt pr

- macros/address_balances/evm_address_credits.sql
- macros/address_balances/evm_address_debits.sql
- models/staging/tron/fact_tron_address_balances.sql
- models/staging/tron/fact_tron_address_credits.sql
- models/staging/tron/fact_tron_address_debits.sql
- models/staging/tron/fact_tron_token_transfers.sql
1. We are moving off current Data Provider for Tron. 
2. Create Transfers and Balances tables
> Tron Data mIgration part 1: Create upsteam models to move tron from current DP

- models/projects/cetus/core/ez_cetus_metrics.sql
- models/projects/pharaoh/core/ez_pharaoh_metrics.sql
There was an extra comma the final select statements of both Cetus and Pharaoh which was causing the models to fail. 
Both models run now:
> fix commas in final select

- macros/goldsky/get_goldsky_chain_fundamental_metrics.sql
- models/projects/blast/core/ez_blast_metrics.sql
- models/staging/blast/fact_blast_transactions_v2.sql
- Switch to Goldsky fundamentals macro
- Properly compute fees off of `receipt_l1_fee`, `receipt_effective_gas_price`, `receipt_gas_used`
- Switch dedup logic to be based off of `QUALIFY`
> Switch to goldsky fundamentals

- macros/stablecoins/agg_chain_stablecoin_transfers.sql
- models/staging/aptos/fact_aptos_address_balances.sql
- models/staging/aptos/fact_aptos_address_credits.sql
- models/staging/aptos/fact_aptos_address_debits.sql
- models/staging/aptos/fact_aptos_token_transfers.sql
- models/staging/kaia/fact_kaia_decoded_events.sql
- models/staging/kaia/fact_kaia_events.sql
- models/staging/kaia/fact_kaia_stablecoin_transfers.sql
- models/staging/kaia/fact_kaia_token_transfers.sql
1. Create the aptos token transfers table
To do:
1. Create the balances pipeline, credit and debits will not rely on transfers because the transfers code is complicated and meant to estimate transfers not be an exact amount for transfers. This is because token transfers for aptos is complicated. The move blockchain works by create new objects rather than emitting an event like the EVM.
3. Create the Stablecoin pipeline
> Aptos: Adding Token Transfers and Balances

- models/staging/pendle/fact_pendle_token_incentives_by_chain_silver.sql
- `FACT_TOKEN_TRANSFERS` is no longer provided by flipside
- All necessary columns are available in `EZ_TOKEN_TRANSFERS`
- Compiled SQL executes
> Update Flipside Arb Token Transfers Table

- models/staging/federal_funds/fact_fedfunds_rates.sql
> Fix naming convention

- models/staging/aptos/fact_aptos_token_transfers.sql
1. Aptos Incremental Token Transfers is borked because fo the unique key
> Fix aptos transfers incrmental runs

- models/data_hubs/fact_protocol_datahub_gold.sql
There is a mismatch between some artemis_id in Snowflake and artemis_id in postgres, where the postgres asset has a hyphen and the snowflake asset has an underscore. This PR should fix those mismatches.
> replace hyphens with underscores

- models/projects/liquity/core/ez_liquity_metrics.sql
- models/projects/liquity/core/ez_liquity_metrics_by_token.sql
- models/projects/liquity/raw/fact_liquity_v1_tvl.sql
Liquity TVL was borked:
It is now not borked:
> forward fill tvl

- models/projects/kelp_dao/core/__kelp_dao__schema.yml
Needed to regenerate the KelpDAO schema in order to run the datahub script since the script traverses the dbt manifest.
> kelpdao schema

- models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql
- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
- models/metrics/stablecoins/contracts/fact_optimism_stablecoin_contracts.sql
- models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql
- models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
Adding BUIDL,
most of the transfer volume is low / 0 because mostly is mint/burnts happening.
Supply example check:
> Adding BUIDL

- macros/address_balances/daily_address_balance_rolling_avgs.sql
- models/staging/arbitrum/fact_arbitrum_daily_balance_rolling_avgs.sql
Adding wallet balance rolling avgs as a metric to look at when considering historical DAU's. ie: do users have 30d avg balance > $x at previous transaction times.
> Add daily balance rolling avgs

- models/projects/believe/core/ez_believe_metrics.sql
- models/projects/believe/core/ez_believe_metrics_by_chain.sql
- missing out a letter `s`
ran RETL for backwards compatibility
> standardize launchpad_volumes

- models/staging/stargate/fact_stargate_v2_arbitrum_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_base_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_bsc_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_ethereum_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_mantle_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_optimism_treasury_balance.sql
- models/staging/stargate/fact_stargate_v2_polygon_treasury_balance.sql
Added t1 to the symbols because there was a `SQL compilation error: ambiguous column name 'SYMBOL'`
reran all 6 fact table models
- fact_stargate_v2_arbitrum_treasury_balance.sql
- fact_stargate_v2_base_treasury_balance.sql
- fact_stargate_v2_bsc_treasury_balance.sql
- fact_stargate_v2_ethereum_treasury_balance.sql
- fact_stargate_v2_mantle_treasury_balance.sql
- fact_stargate_v2_optimism_treasury_balance.sql
- fact_stargate_v2_polygon_treasury_balance.sql
reran ez_stargate_metrics table as well (data is refreshed until `2025-05-13`)
reran RETL for backwards compatibility
> Fix stargate ambiguous column name

- macros/metrics/get_adjusted_dau.sql
- models/projects/arbitrum/raw/ez_arbitrum_adjusted_dau.sql
- models/projects/base/raw/ez_base_adjusted_dau.sql
- models/projects/ethereum/raw/ez_ethereum_adjusted_dau.sql
- models/projects/optimism/raw/ez_optimism_adjusted_dau.sql
Fixing ssue with alias in subquery and also adding merge incremental_strategy to adjusted_dau models. Tested and successfully built incremental run.
> adjusted dau fix incremental alias and add incremental_strategy

- models/staging/optimism/fact_optimism_bridge_transfers.sql
I used the wrong contract address for the op bridge
> Fixed OP Contract

- models/projects/morpho/core/ez_morpho_metrics.sql
- models/projects/morpho/core/ez_morpho_metrics_by_chain.sql
- renamed columns to deposits and borrows so we don't have to depend on adapters support metrics `SupportsLending`
- ez_morpho_metrics_by_chain
- removed SupportsLending
> Rename columns to deposits and borrows

- models/projects/syrup/core/ez_syrup_metrics.sql
- models/projects/syrup/core/ez_syrup_metrics_by_chain.sql
- Adding Syrup ez tables
- For now these are just copies of the tables for Maple 
- We need to materialize these into the `SYRUP` database for the FE to properly attribute them to `syrup` instead of `maple` for now
- Materialized models, ran RETL locally, and metrics appear 
- Schedule DBT models and fix adapter
> Add Syrup ez tables

- models/projects/polygon_zk/core/ez_polygon_zk_metrics.sql
- models/projects/zcash/core/ez_zcash_metrics.sql
- Setting these models to disabled so they don't appear in the dbt manifest.json file and get pulled into various automated systems
> Disable PolygonZK and ZCash ez Metrics Models

- models/projects/liquity/raw/fact_liquity_v1_outstanding_supply_polygon.sql
- `fact_token_transfers` has been renamed to `ez_token_transfers` by Elipside for Polygon
> Switching liquity to use ez_token_transfers for Polygon

- models/__global__sources.yml
- models/_complete_asset_models/maker/ez_maker_metrics__complete__.sql
- models/_complete_asset_models/maker/ez_maker_metrics_by_chain__complete__.sql
- models/_complete_asset_models/maker/ez_maker_metrics_by_token__complete__.sql
- models/projects/balancer/raw/fact_balancer_ethereum_revenue_by_token.sql
- models/projects/balancer/raw/fact_balancer_token_incentives.sql
- models/projects/convex/raw/fact_convex_revenue.sql
- models/projects/lido/raw/fact_lido_fees_revs_expenses.sql
- models/projects/lido/raw/fact_lido_token_incentives.sql
- models/projects/liquity/raw/fact_liquity_v1_outstanding_supply_ethereum.sql
- models/projects/maker/raw/fact_dai_burn.sql
- models/projects/maker/raw/fact_dai_mint.sql
- models/projects/maker/raw/fact_pause_proxy_mkr_trxns_raw.sql
- models/projects/maker/raw/fact_treasury_flows.sql
- models/projects/maker/raw/fact_uni_lp_supply.sql
- models/staging/bananagun/fact_bananagun_coin_metrics.sql
- models/staging/gnosispay/fact_gnosispay_transfers.sql
- models/staging/pendle/fact_pendle_token_incentives_by_chain_silver.sql
- Updating references to `fact_token_transfers` in advance of Flipside Ethereum Standarization later this month
columns in fact_token_transfers are a subset of those in ez_token_transfers
> Switch fact_token_transfers -> ez_token_transfers for Ethereum and Gnosis

- iceberg/dbt_project.yml
- iceberg/models/test_iceberg.sql
- package-lock.yml
- packages.yml
- Adding subproject for Iceberg tables
- Ran model from iceberg project 
`dbt run -s models/test_iceberg.sql`
- Compilation runs super fast (6s)
- Selecting models from primary package works
`dbt ls --select 'artemis_dbt_iceberg.*'`
- `dbt compile` from primary project still works in normal amount of time
- Files written to S3 
- Table available within `ARTEMIS_ICEBERG` in snowflake
- Iron out Dagster Integration
> Add Iceberg dbt Subproject

- models/projects/vertex/core/ez_vertex_metrics.sql
- models/staging/vertex/fact_vertex_token_incentives.sql
Added:
- Vertex token incentives data model
- vertex token incentives to ez_metrics table
CAD: in-progress
**Key Notes:**
- VRTX token incentives is constructed using 'ClaimVRTX' events and initial mint to reach parity with TT
- Initial mint is multiplied by an assumed VTRX price @ launch of .01938, derived back back calculating based on the initial mint usd value on TT (Arbitrum_flipside prices for VRTX don't begin until 10 days after the mint date)
- Claim events only collected before July 2024 to match TT token incentives going to zero after July 2024
- Research to be expanded in the CAD in regards to what token incentives actually mean in this case
Validation:
> feature/vertex token_incentives

- models/projects/convex/raw/fact_convex_pools.sql
Flipside removed the fact decoded traces table. This works just as well.
> use ez decoed traces

- models/projects/magiceden/core/__magiceden__schema.yml
- models/projects/magiceden/core/ez_magiceden_metrics.sql
- models/projects/magiceden/core/ez_magiceden_metrics_by_chain.sql
- models/staging/magiceden/fact_magiceden_ethereum_transactions.sql
- models/staging/magiceden/fact_magiceden_metrics_by_chain.sql
fix fact_magiceden_ethereum_transactions
- remove `project_name` column because ethereum_flipside table no longer supports the `project_name` column
- running all downstream models
- ez_magiceden_metrics
- ez_magiceden_metrics_by_chain
> Magic Eden Fix due to flipside changes

- iceberg/models/test_iceberg.sql
- Model was being pulled in by the daily_iceberg_share_job because it writes to the `ARTEMIS_ICEBERG` database and is therefore part of that asset group
- Once we create a separate Dagster asset for models in this project we will be unblocked for running models with Iceberg materialization turned on
> Disable Test Iceberg Model

- models/staging/standard_8d737a18/fact_aptos_stablecoin_transfers_standard_8d737a18.sql
- models/staging/standard_8d737a18/fact_celo_stablecoin_transfers_standard_8d737a18.sql
- models/staging/standard_8d737a18/fact_kaia_stablecoin_transfers_standard_8d737a18.sql
1. Adding transaction_position to stablecoin standard transfers
> Updating celo, kaia, and aptos

- iceberg/models/ez_metrics/balancer/ez_balancer_metrics_by_pool_iceberg.sql
- iceberg/models/ez_metrics/maple/ez_maple_metrics_by_pool_iceberg.sql
Balancer and Maple `ez_metrics_by_pool` had different columns, so we need to modify the columns that they're ordering by.
Ran locally
> Modify order_by for balancer and maple iceberg

- models/metrics/stablecoins/yield/ez_yield_table.sql
- models/metrics/stablecoins/yield/fact_stablecoin_apy.sql
- models/staging/drift/agg_drift_stablecoin_apy.sql
- models/staging/drift/fact_drift_insurance_vault_apy.sql
- models/staging/drift/fact_drift_lending_apy.sql
- models/staging/drift/fact_drift_stablecoin_apy.sql
- models/staging/kamino/agg_kamino_stablecoin_apy.sql
- models/staging/kamino/fact_kamino_lending_apy.sql
- models/staging/kamino/fact_kamino_stablecoin_apy.sql
- models/staging/kamino/fact_kamino_vaults_apy.sql
- models/staging/orca/agg_orca_stablecoin_apy.sql
- models/staging/orca/fact_orca_apy.sql
- models/staging/orca/fact_orca_stablecoin_apy.sql
- models/staging/raydium/agg_raydium_stablecoin_apy.sql
- models/staging/raydium/fact_raydium_apy.sql
- models/staging/raydium/fact_raydium_stablecoin_apy.sql
- models/staging/save/agg_save_stablecoin_apy.sql
- models/staging/save/fact_save_apy.sql
- models/staging/save/fact_save_stablecoin_apy.sql
Adding risk score(tvl_score right now) to the yield tables
right now is for kamino and raydium, if the model looks good to go, will add the rest here as well.
Current build
> Adding models to support risk_score

- models/projects/ethereum/raw/ez_ethereum_blocks.sql
- models/staging/ethereum/fact_ethereum_blocks.sql
- `hash` was renamed to `block_hash` in the upstream tables
- `total_difficulty` was removed
- Ran compiled sql, will remove `total_difficulty` from the tables after merging this PR
> Fix Ethereum blocks

- models/projects/balancer/raw/fact_balancer_ethereum_revenue_by_token.sql
Balancer dbt model couldn't use `having` with newly defined column, so I split the query out into a CTE first before running the `having` statement.
Ran locally
> Fix balancer dbt model

- iceberg/macros/merge_tags_dict.sql
- iceberg/models/ez_metrics/pancakeswap/ez_pancakeswap_metrics_by_pool_iceberg.sql
Pancakeswap table is too large to do a order by on the entire table for duckdb (it overwhelms the ephemeral storage), so making the date column a `partitioned_order_by` where it first partitions distinct values into separate tables, orders those tables independently, and then combines them back in order.
Ran locally
> Add partitioned order by for pancakeswap

- models/projects/trader_joe/core/ez_trader_joe_metrics.sql
- models/projects/trader_joe/core/ez_trader_joe_metrics_by_chain.sql
Added:
- token incentives added to ez_trader_joe_metrics_by_chain tables
- Re-organized ez_metric/ez_metric_by_chain table naming & ordering
Validation:
**Key Notes:**
- Trader Joe's rebranded to 'Let's Fucking Joe' and the token is now LFJ. Adding to the backlog to update the CAD & the protocol information to take account for this re-brand
> dataquality/trader_joe token_incentives added to by_chain table

- models/projects/pancakeswap/core/ez_pancakeswap_metrics.sql
- models/projects/pancakeswap/core/ez_pancakeswap_metrics_by_chain.sql
Added:
- pancakeswap token incentives added to by_chain table so that metric data flows to the Artemis terminal
Validation:
Question:
- Why does the front-end terminal pull from the by_chain table for the token_incentives metric? I take it has to do with the new all-metric adaptor implementation? @akan72
> dataquality/pancakeswap token incentives added to by_chain table

- models/staging/hyperliquid/__hyperliquid__sources.yml
- models/staging/hyperliquid/fact_hyperliquid_perps_trading_volume.sql
- models/staging/hyperliquid/fact_hyperliquid_trading_volume.sql
- add fact_hyperliquid_perps_trading_volume (only pushed to prod on `2025-05-22` hence we only have daily data since then)
- deprecate hypurrscan and use hyperliquid API data
ran RETL to make sure backwards compatibility works
> Deprecating previous Hyperliquid upstream provider and using hyperliquid API

- models/projects/trader_joe/core/ez_trader_joe_metrics.sql
Ez trader joe metrics table had duplicate columns and was also missing a column
Ran locally
> Fix ez trader joe metrics table

- models/projects/dodo/core/ez_dodo_metrics.sql
- models/projects/dodo/core/ez_dodo_metrics_by_chain.sql
- models/staging/dodo/__dodo__sources.yml
- models/staging/dodo/fact_dodo_swap_metrics.sql
- models/staging/dodo/fact_dodo_token_incentives.sql
Token Incentives:
**Key Notes:**
- Token Incentives data methodology is defined in CAD and maps cleanly to token terminal data
- Volume has discrepancies bc of ez_dex_swap null values, so commenting this metric out for now
> feature/dodo models & token incentives

- models/projects/vertex/core/ez_vertex_metrics.sql
Added:
- coalesce around vertex_token_incentives to flow data through present day on the front-end
- previously, the chart only showed data through the last non-null value. Now it should show through present day
> dataquality/vertex token_incentives

- macros/stablecoins/stablecoin_breakdown.sql
Date was aggregated to first day of each month, which can be misleading to people that its stale data, especially for monthly and weekly aggregation data.
Change such that for each date aggregation we use the last day of it.
> Changing the date aggregation to the last day

- models/projects/optimism/core/ez_optimism_metrics.sql
- models/staging/optimism/__optimism__sources.yml
- models/staging/optimism/fact_optimism_token_incentives.sql
Added:
- optimism token incentives model & metric in ez_metrics table
Validation:
**Key Notes:**
- This is slightly DIFFERENT than TT's method. Our values correlate, but are not the same as you see in the picture. **Our method calculates all OP token outflows from the Optimism Foundation contract**, which is named the distributor of token incentives in Optimism documentation. 
Why different methologies?
- After spending ~2 days tracking down the smart contract architecture of OP token outflows and cross-referencing against developer docs / twitter posts (see Excalidraw), it's clear that continuing this goose chase is diminishing returns. Current best leads:
- Airdrops might be distributed from a different contract than the Optimism Foundation contract, and could be included in the TT calc …
> feature/optimism token_incentives

- models/projects/dydx/core/ez_dydx_metrics.sql
- models/projects/dydx/core/ez_dydx_metrics_by_chain.sql
- models/projects/dydx/core/ez_dydx_metrics_by_version.sql
- models/projects/dydx_v4/core/ez_dydx_v4_metrics.sql
- models/projects/dydx_v4/core/ez_dydx_v4_metrics_by_chain.sql
- models/staging/dydx/__dydx__sources.yml
- models/staging/dydx/_test_fact_dydx_v4_trading_fees.yml
- models/staging/dydx/_test_fact_dydx_v4_txn_fees.yml
- models/staging/dydx/fact_dydx_v4_trading_fees.sql
- models/staging/dydx/fact_dydx_v4_txn_fees.sql
created `fact_dydx_v4_txn_fees`
`txn_fees`
and `fact_dydx_v4_trading_fees`
`total_fees` = `trading_fees`
updated the formatting for the ez_tables
created the test yml files as well
ran RETL for dydx_v4
ran RETL for dydx
> Deprecate old dydx endpoint and use new endpoint

- models/projects/solana/core/ez_solana_app_retention_metrics.sql
- models/staging/solana/fact_solana_transactions_v2.sql
Fix solana transactions table. It wasn't actually running for the past 90 days every Saturday.
Increase to 13 month lookback for app retention. That way, we get month 0 and then 12 months of lookback instead of month 0 and only 11 months of lookback.
Running locally
> Fix solana transactions table and increase to 13 month lookback for app retention

- macros/dune/clean_dune_events.sql
- models/projects/maker/raw/fact_uni_lp_supply.sql
1. Dune timestamps were not being converted properly.
2. flipside deprecated a table effecting maker
> C911: update dune and maker models

- models/projects/meteora/raw/fact_meteora_decoded_swaps.sql
- models/projects/meteora/raw/fact_meteora_encoded_swaps.sql
- models/staging/meteora/fact_meteora_decoded_swaps_extract.sql
- Re-enable meteora decoded swaps model
- Comment out microbatch config until we implement microbatch ETL in Dagster
- Convert raw DB relations to dbt refs on the decoded swaps model
```
dbt run -s fact_meteora_decoded_swaps fact_meteora_decode
d_swaps_extract fact_meteora_dlmm_metrics ez_meteora_metrics ez_meteora_metrics_by_chain
```
- [x ] `dbt build model_name+` screenshot (must include downstream models)
> Re-Enable Meteora Decoded Swaps

- models/staging/hyperliquid/fact_hyperliquid_trading_volume.sql
- Change from raw table to fact table as raw table has stale data
now trading_volume has the most updated data
ran dagster materialize on raw_hyperliquid_unique_traders and raw_hyperliquid_daily_transactions to get the most updated data from upstream provider -- `2025-06-08` (latest data)
ran all the downstream tables and now data is showing in the front-end
DAU
Daily transactions
ran RETL
> Change to hyperliquid perps trading volume fact table

- macros/goldsky/get_goldsky_chain_fundamental_metrics.sql
- models/projects/hyperliquid/core/__hyperliquid__schema.yml
- models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql
- models/projects/hyperliquid/core/ez_hyperliquid_metrics_by_chain.sql
- models/staging/hyperliquid/fact_hyperliquid_hypercore_burns.sql
- models/staging/hyperliquid/fact_hyperliquid_hyperevm_fundamental_metrics.sql
- models/staging/hyperliquid/fact_hyperliquid_hyperevm_transactions.sql
`fact_hyperliquid_hyperevm_transactions`
`fact_hyperliquid_hyperevm_fundamental_metrics`
renamed `fact_hyperliquid_daily_burn` with `fact_hyperliquid_hypercore_burns` as fact_hyperliquid_daily_burn seems very vague and there are 2 components of burns now - fact_hyperliquid_hypercore and hyperevm
removed self-register metrics in adapter for hyperliquid (backend PR: https://github.com/Artemis-xyz/gokustats-back-end/pull/3876)
> Add hyperliquid burns

- macros/coingecko/waterfall_stablecoin_prices.sql
- macros/p2p/p2p_stablecoin_transfers.sql
- macros/stablecoins/stablecoin_metrics_all.sql
- macros/stablecoins/stablecoin_metrics_artemis.sql
- macros/stablecoins/stablecoin_metrics_p2p.sql
- macros/standardization/decode_artemis_events.sql
- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_bridge_addresses.sql
- models/staging/coingecko/fact_coingecko_token.sql
1. Fix fact_coingecko_tokens to left join on circulating supply. This was causing AEUR to be excluded from the table and making the stablecoin job fail
2. Update Artemis Decoded events to use the new decoder. V4 keeps bytes32 values as hexadecimal strings otherwise it returns a bytes array which is difficult to parse and handle in snowflake (https://github.com/Artemis-xyz/gokustats-back-end/pull/3878)
3. Add USDT0 bridge address to the tracked stablecoin bridged on ethereum
> c911 Ethereum Stablecoin and update Artemis events

- models/staging/arbitrum/__arbitrum__sources.yml
Duplicate source in arbitrum__sources and global__sources was throwing an error in backend CI.
Removed the source from the arbitrum file.
Dependent table runs:
> remove dupllicate source

- macros/standardization/decode_artemis_events.sql
- models/dimensions/events/dim_events_silver.sql
1. Update the decoder to use web3 py lib
2. We need to join on both the topiczero and the number of indexed topics
The new number of failed events is much lower that the previous decoders.
Previously there were 381 logs we could not decode
> Update decoder to v5

- macros/standardization/token_transfer_events.sql
1. All upstream tables assume that the addresses are the same case. This breaks a lot of our upstream logic and we need to force the to and the from address to be lowercase
> c911: Updating token transfers macro

- models/projects/optimism/raw/ez_optimism_bridge_transfers.sql
Upstream column names  in `fact_optimism_bridge_transfers` are `transaction_hash` and `amount_native` 
- Ran compiled sql
> Fix view sql in ez_optimism_bridge_transfers

- macros/metrics/get_github_metrics.sql
- Set latest available date for Developer Metrics in ez tables to 2 Sundays ago given underlying changes in the github
- [ x] `dbt build model_name+` screenshot (must include downstream models)
Ran compiled sql for `ez_cardano_metrics`, latest data available is 6/15 as expected
> Add latest github metrics data macro to ez table model

- models/metrics/stablecoins/contracts/fact_ripple_stablecoin_contracts.sql
I checked the token address on usdc.cool, and found I was tracking the wrong token address.
> Replace the contract address for usdc

- models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_premint_addresses.sql
USDe uses OFT to bridge token from one chain to another. Therefore, our numbers are inflated because we are not removing the balances in the OFT address that is locked up.
Add to bridged addresses.
get the OFT address from
https://layerzeroscan.com/application/ethena
our current numbers : 5298607470.57
DFL numbers : 5096000000
This will account for the ~200M difference
> Adding OFT address to remove supply from it

- models/common/ez_protocol_datahub.sql
- models/common/ez_protocol_datahub_by_chain.sql
- models/data_hubs/fact_protocol_datahub_by_chain_gold.sql
- models/data_hubs/fact_protocol_datahub_gold.sql
Adding revenue to datahub to make it a more powerful tool.
Job to create the silver table runs:
Downstream gold and ez tables run:
N/A
N/A
N/A
Revenue by app by month - interesting to see the evolution and diversification of revenue-generating apps:
About 47% of entries have non-null revenue.
> add revenue to datahub

- iceberg/models/ez_metrics/stargate/ez_stargate_metrics_by_token_iceberg.sql
- models/projects/stargate/core/__stargate__schema.yml
Adding stargate by token dimension type into duckdb so that we can query from DuckDB in the future for dimensiontypes by pool and token
Ran `generate_schema.py` and `cd iceberg; dbt run -s ez_stargate_metrics_by_token_iceberg`
> Add stargate by token into duckdb

- .github/workflows/docs.yml
- Add slack alerts for failed runs of the `generateDocs` workflow. Intentionally cause it to fail...will revert the `exit 1` in a fast follow PR
> Example Slack Alert for Failed Docs Runs

- models/staging/standard_8d737a18/fact_aptos_stablecoin_withdraw_deposit_transfers_8d737a18.sql
Adding a model to `standard_8d737a18` breaking down aptos transfers into raw deposit and withdrawal events per Tether's request. Will then replicate this to their S3. 
> add withdraw and deposit transfers for aptos

- models/__global__schema.yml
- models/projects/arbitrum/core/__arbitrum__schema.yml
- models/projects/arbitrum/core/ez_arbitrum_metrics.sql
- models/projects/avalanche/core/__avalanche__schema.yml
- models/projects/avalanche/core/ez_avalanche_metrics.sql
- models/projects/ethereum/core/__ethereum__schema.yml
- models/projects/ethereum/core/ez_ethereum_metrics.sql
- models/projects/near/core/__near__schema.yml
- models/projects/near/core/ez_near_metrics.sql
- models/projects/optimism/core/__optimism__schema.yml
- models/projects/optimism/core/ez_optimism_metrics.sql
- models/projects/solana/core/__solana__schema.yml
- models/projects/solana/core/ez_solana_metrics.sql
- models/projects/tron/core/__tron__schema.yml
- models/projects/tron/core/ez_tron_metrics.sql
Adding a new metric TEA (total economic activity) to global schema and `ez_metrics` tables for the below chains:
- Arbitrum
- Avalanche
- Ethereum
- Near
- Optimism
- Solana
- Tron
Total Economic Activity (TEA) is a new metric we created to measure the size and economic activity of blockchains. It is designed to be flexible and widely applicable to all blockchains regardless of their niche use cases and user patterns. It consists of Chain Fees (including gas fees, blob fees, and MEV), Settlement Volume (Dex Volumes, NFT Volumes and P2P Transfer Volumes), and Application Fees. 
Arbitrum:
Tron:
Solana:
Near:
Optimism:
Ethereum:
Avalanche:
NOTE: Data is not appearing on charts because local frontend is hitting the prod FastAPI backend and I am not setup on that repo yet. Still waiting on …
> add tea to ez_metrics

- models/projects/solana/core/ez_solana_metrics.sql
Fixing REV column calculation on Solana ez_metrics. Adding a coalesce so REV reflects the entire fee history, not just when jito_tips were available. Previously REV was ending on 2022-10-20 due to the cutoff from jito_tips data. Now it will reflect fees prior to this date (going back to 2021-04-20). 
> fix rev column on solana ez_metrics

- macros/wallets/distinct_eoa_addresses.sql
There was a discrepancy in the number of `from_address`s comparing Tron SonarX data to Allium data which was resulting in lower P2P transfer volumes.
It turns out it is because SonarX splits out the `trx_from_address` and `trx_owner_address` (both are "from" addresses) so we need to account for the `trx_owner_address` in the `distinct_eoa_addresses` macro. After accounting for both it matches with Allium pretty closely.
> Add trx_owner_address to Tron EOA macro

- models/staging/bsc/fact_bsc_address_balances_by_token.sql
Bsc address balances table took over 4 hours instead of ~2h 30m which caused downstream tables to encounter an auth error. Bumping up warehouse here.
Started running locally
> Bump up bsc address balances table

- iceberg/models/ez_metrics/aave/ez_aave_metrics_by_chain_iceberg.sql
- iceberg/models/ez_metrics/aave/ez_aave_metrics_by_token_iceberg.sql
- iceberg/models/ez_metrics/morpho/ez_morpho_metrics_by_chain_iceberg.sql
- iceberg/models/ez_metrics/uniswap/ez_uniswap_metrics_by_chain_iceberg.sql
- iceberg/models/ez_metrics/uniswap/ez_uniswap_metrics_by_token_iceberg.sql
Add Aave, Morpho, and Uniswap dimension type tables by chain and token to duckdb. This is in service of: https://www.notion.so/artemisxyz/Deep-Dive-Project-Page-23746f0265b480099b7bd351808f1613
Ran all tables locally.
> Add aave, morpho, uniswap dimension type tables to duckdb

- models/staging/standard_8d737a18/fact_aptos_stablecoin_withdraw_deposit_transfers_8d737a18.sql
Amending withdraw deposit model per Leo's request, including the below changes:
- limiting to stablecoins (inner join on stablecoin_contracts table)
- adding asset_symbol
- amending amount_asset to account for decimals
- adding transaction_position column
> amend aptos withdraw deposit transfers model

- models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql
- models/staging/hyperliquid/fact_hyperliquid_supply_data.sql
Tick the following only after PR has been approved and before it is merged: 
Fixed Hyperliquid Circulating Supply as there -ve values in the dataset.
Reason being: on `2025-06-27` we actually ran the job twice, hence the foundation_balances and unvested_tokens doubled due to the sum aggregation. 
This result in circulating_supply_native being -ve. Hence, the fix is to do a inner select statement with max_by before summing up in the CTE.
> Fix Hyperliquid -ve Circulating Supply Values

- models/projects/hyperliquid/raw/fact_hyperliquid_trades.sql
- Fix incremental logic for `fact_hyperliquid_trades`
- [x ] Internal only (check this box this PR should not appear in external facing docs/changelog)
full refreshed model, then did incremental run
- [x ] `dbt build model_name+` screenshot (must include downstream models)
> Fix incremental logic in fact_hyperliquid_trades

- models/projects/sui/core/ez_sui_metrics.sql
There is an issue with upstream data beginning on 7/24 leading to dupes being inserted into the table. Going to temporarily handle those with a `GROUP BY ALL` until mysten labs can resolve on their end. Also full refreshed the table locally to remove the existing dupes. 
> Temporarily handle dupes in ez_sui_metrics

- dbt_scripts/generate_schema.py
Fixed generate schema macro. The new incremental logic in the ez tables inserts a select statement at the end of the model. The previous generate schema macro always grabbed the last select statement before parsing it to generate the schema. The new logic checks if the final select statement is from the incremental logic, and if so, it grabs the second to last select statement.
Before: script removes certain columns from schema since the SELECT clause it processes is `max(this.date)`. 
After, columns are added back as it now processes the correct SELECT clause:
> fix generate schema script

- models/metrics/bridges/agg_daily_bridge_flows_metrics.sql
- models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql
- models/staging/across/fact_across_flows.sql
- models/staging/across/fact_across_transfers.sql
- models/staging/across/fact_across_transfers_with_price.sql
- models/staging/arbitrum/fact_arbitrum_one_bridge_flows.sql
- models/staging/avalanche/fact_avalanche_bridge_flows.sql
- models/staging/base/fact_base_bridge_flows.sql
- models/staging/debridge/fact_debridge_flows.sql
- models/staging/ink/fact_ink_bridge_flows.sql
- models/staging/optimism/fact_optimism_bridge_flows.sql
- models/staging/polygon/fact_polygon_pos_bridge_flows.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_flows.sql
- models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
- models/staging/soneium/fact_soneium_bridge_flows.sql
- models/staging/sonic/fact_sonic_bridge_flows.sql
- models/staging/stargate/fact_stargate_flows.sql
- models/staging/starknet/fact_starknet_bridge_flows.sql
- models/staging/synapse/fact_synapse_flows.sql
- models/staging/unichain/fact_unichain_bridge_flows.sql
- models/staging/usdt0/fact_usdt0_flows.sql
- models/staging/worldchain/fact_worldchain_bridge_flows.sql
- models/staging/wormhole/fact_wormhole_flows.sql
- models/staging/wormhole/fact_wormhole_operations_with_price.sql
- models/staging/zksync/fact_zksync_era_bridge_flows.sql
Adding asset details to bridge flows models. Some upstream models only have source or destination token, not both, so I was unable to add both source and destination token for all bridges. Since most source and destination tokens are the same it shouldn't be an issue. In instances where both source and destination are present, I am defaulting to using the source token symbol if present and destination token symbol if the source token symbol is not present. 
> Add asset detail to bridge flows

- models/projects/lido/core/__lido__schema.yml
- models/projects/lido/core/ez_lido_metrics.sql
- models/projects/lido/core/ez_lido_metrics_by_chain.sql
- models/projects/lido/core/ez_lido_metrics_by_token.sql
Tick the following only after PR has been approved and before it is merged: 
This is part of BDR Final Deprecation Plan - Lido
Tests
Backend PR - https://github.com/Artemis-xyz/gokustats-back-end/pull/4096
> Lido Metric Deprecation

- models/projects/ach/core/ez_ach_metrics.sql
- models/projects/aftermath/core/ez_aftermath_metrics.sql
- models/projects/bitpay/core/ez_bitpay_metrics.sql
- models/projects/braintrust/ez_braintrust_metrics.sql
Added timestamp columns to assets that were missing them.
N/A
N/A
Tick the following only after PR has been approved and before it is merged: 
ACH Before:
ACH After 2 back-to-back runs:
Aftermath Before (seems to be stale to June 10th) (akhil looking into staleness)
Aftermath after 2 back-to-back runs - data is as expected (although stale):
Bitpay Before
Bitpay After 2 back-to-back runs
Braintrust Before
Braintrust After (refreshed upstream tables too)
> add ts cols to tables that were missing it

- models/projects/algorand/core/__algorand__schema.yml
- models/projects/algorand/core/ez_algorand_metrics.sql
- models/staging/algorand/__algorand_sources.yml
- models/staging/algorand/fact_algorand_fundamental_data.sql
Added raw_algorand_ez_algorand_metrics_parquet as a source, created a fact table from the parquet file, and updated the EZ table to pull from this new fact table
This PR: 
- Replaces the old `ez_algorand_metrics` source that comes directly from the backend with `raw_algorand_ez_algorand_metrics_parquet` that comes from the Chakra replication
- To make the flow easier, I created a fact table that first takes the parquet file as a source and converts it into a regular table called `fact_algorand_fundamental_data.sql`
- The EZ table calls from this table now
- [] Screenshots of changed data **in local frontend**
There aren't any changes in the data per se, but the data in our local frontend after these changes matches the data in our frontend. There were too many screenshots to add to this …
> Akhil/Algorand Legacy Replication Deprecation

- models/projects/braintrust/ez_braintrust_metrics.sql
- models/projects/mento/core/ez_mento_metrics.sql
- models/projects/pendle/core/ez_pendle_metrics_by_chain.sql
- models/projects/polygon_zk/core/ez_polygon_zk_metrics.sql
- models/projects/polymarket/core/ez_polymarket_metrics.sql
- models/projects/render/core/ez_render_metrics.sql
- models/projects/vertex/core/ez_vertex_metrics.sql
- models/projects/zcash/core/ez_zcash_metrics.sql
Added `where date < to_date(sysdate())` to a few models that were missing it. This causes issues with the new incremental models.
**ach**
**braintrust**
**mento**
**polygon_zk**
**polymarket**
**render**
**vertex**
**zcash**
> add date where clauses

- models/projects/leo/core/ez_leo_metrics.sql
Very small PR to enable issued supply, circulating supply, and revenue to flow on days where there are no burns.
This ez table will be overwrote as part of the metric standardization, this is just a quick fix.
> feature/leo ez_table fix

- macros/admin/generate_alias_name.sql
Was hitting an issue testing versioning in dev, slightly tweaked this macro to handle aliasing in dev. 
The error I was getting during testing was due to this macro not recognizing versioning in dev and trying to materialize multiple version models to the same db object. 
After making this change to the macro, it materialized correctly in dev
> amend generate_alias_name to handle versions in dev
