Artemis-xyz/dbt

models/projects/geodnet/core/ez_geodnet_metrics.sql, models/projects/geodnet/core/fact_geodnet_fees_revenue.sql
=> Add GEODNET Fees + Revenue

models/staging/stride/fact_stride_daa_gas_usd_txns.sql
1. Updating Stride Code to not remove dates where daa or fees is null
To Do
1. Talking with Numia in order to find a better way to calculate DAA
=> Updating Stride

models/bam_models/all_chains/all_chains_gas_dau_txns_by_category.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_namespace.sql
=> Fixed Tron BAM where gas is none

macros/decode/decode_events.sql, macros/decode/transfer_events.sql, models/dimensions/contracts/dim_contract_abis.sql, models/dimensions/events/dim_events_silver.sql, models/metrics/stablecoins/contracts/fact_celo_stablecoin_contracts.sql, models/staging/celo/fact_celo_token_transfers.sql
1. Added `dim_celo_stablecoin_contracts` tracking USDC, USDT, cUSD, cEUR
2. Added fact_celo_token_transfers
=> Celo Token Transfers

macros/retention/get_cohort_retention.sql, models/data_hubs/fact_retention_datahub.sql, models/projects/arbitrum/core/ez_arbitrum_retention.sql, models/projects/avalanche/core/ez_avalanche_retention.sql, models/projects/base/core/ez_base_retention.sql, models/projects/bsc/core/ez_bsc_retention.sql, models/projects/ethereum/core/ez_ethereum_retention.sql, models/projects/near/core/ez_near_retention.sql, models/projects/optimism/core/ez_optimism_retention.sql, models/projects/polygon/core/ez_polygon_retention.sql, models/projects/tron/core/ez_tron_retention.sql
=> Added Retention for Activity Monitor chains except solana

models/data_hubs/fact_retention_datahub.sql
=> Added Unique ID for retention datahub

macros/address_balances/address_credits_quicknode.sql, macros/address_balances/address_debits_quicknode.sql, macros/agg_chain_stablecoin_breakdown.sql, macros/agg_chain_stablecoin_transfers.sql, macros/decode/decode_events.sql, macros/decode/token_transfer_events.sql, models/dimensions/current_balances/dim_celo_current_balances.sql, models/metrics/stablecoins/breakdowns/daily/agg_celo_stablecoin_breakdown_daily.sql, models/metrics/stablecoins/breakdowns/monthly/agg_celo_stablecoin_breakdown_monthly.sql, models/metrics/stablecoins/breakdowns/weekly/agg_celo_stablecoin_breakdown_weekly.sql, models/metrics/stablecoins/contracts/fact_celo_stablecoin_contracts.sql, models/metrics/stablecoins/metrics/agg_celo_stablecoin_metrics.sql, models/staging/celo/__celo__sources.yml, models/staging/celo/fact_celo_address_balances_by_token.sql, models/staging/celo/fact_celo_address_credit_by_token.sql, models/staging/celo/fact_celo_address_debit_by_token.sql, models/staging/celo/fact_celo_token_transfers.sql
Created
1. `fact_celo_token_transfers`
2. `dim_celo_current_balances`
3. `fact_celo_address_balances_by_token`
4. `fact_celo_address_debit_by_token`
5. `fact_celo_address_credit_by_token`
Updated 
1. decoded_events macro to pass along the raw data
=> Creating Celo Stablecoin tables

models/projects/cardano/core/ez_cardano_metrics.sql, models/staging/cardano/__cardano__sources.yml, models/staging/cardano/_test_fact_cardano_nft_trading_volume.yml, models/staging/cardano/fact_cardano_nft_trading_volume.sql
1. Adding Cardano NFT Trading Volume
=> Cardano NFT Trading Volume

macros/transform/fact_protocol_daa_txns_gas_gas_usd.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_base.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_base_gold.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_bsc.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_bsc_gold.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_ethereum.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_ethereum_gold.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_zksync.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_zksync_gold.sql
=> Fixed Maverick Friendly Name

models/dimensions/bot_v_human/dim_blast_bots.sql, models/dimensions/current_balances/dim_blast_current_balances.sql, models/metrics/contracts/_test_fact_blast_contracts.yml, models/metrics/contracts/fact_blast_contracts.sql, models/metrics/contracts/fact_blast_contracts_gold.sql, models/metrics/stablecoins/breakdowns/daily/agg_blast_stablecoin_breakdown_daily.sql, models/metrics/stablecoins/breakdowns/daily/agg_stablecoin_breakdown_daily.sql, models/metrics/stablecoins/breakdowns/monthly/agg_blast_stablecoin_breakdown_monthly.sql, models/metrics/stablecoins/breakdowns/monthly/agg_stablecoin_breakdown_monthly.sql, models/metrics/stablecoins/breakdowns/weekly/agg_blast_stablecoin_breakdown_weekly.sql, models/metrics/stablecoins/breakdowns/weekly/agg_stablecoin_breakdown_weekly.sql, models/metrics/stablecoins/contracts/fact_blast_stablecoin_contracts.sql, models/metrics/stablecoins/metrics/agg_blast_stablecoin_metrics.sql, models/metrics/stablecoins/metrics/agg_daily_stablecoin_metrics_silver.sql, models/projects/blast/core/ez_blast_metrics.sql, models/projects/blast/raw/ez_blast_transactions.sql, models/staging/blast/__blast__sources.yml, models/staging/blast/_test_fact_blast_transactions.yml, models/staging/blast/fact_blast_address_balances_by_token.sql, models/staging/blast/fact_blast_address_credit_by_token.sql, models/staging/blast/fact_blast_address_debit_by_token.sql, models/staging/blast/fact_blast_daily_balances.sql, models/staging/blast/fact_blast_daily_sleep.sql, models/staging/blast/fact_blast_transactions.sql, models/staging/blast/fact_blast_transactions_gold.sql, models/staging/sybil/dim_blast_sybil_address.sql
Still pending revenue - just want to make sure models work first.
=> Add Blast Metrics

macros/p2p/filter_p2p_token_transfers.sql, macros/p2p/p2p_native_transfers.sql, macros/p2p/p2p_token_transfers.sql, macros/p2p/p2p_transfer_volume.sql, macros/wallets/distinct_evm_eoa_addresses.sql, models/dimensions/wallet/dim_tron_eoa_addresses.sql, models/staging/ethereum/fact_ethereum_p2p_native_transfers.sql, models/staging/tron/fact_tron_p2p_native_transfers.sql, models/staging/tron/fact_tron_p2p_token_transfers.sql, models/staging/tron/fact_tron_p2p_token_transfers_silver.sql, models/staging/tron/fact_tron_p2p_transfer_volume.sql
1. Added tron p2p transfer volume
`stables`
`token`
`native`
`daily`
=> Adding tron p2p models

models/projects/base/core/ez_base_metrics.sql, models/projects/optimism/core/ez_optimism_metrics.sql, models/staging/base/_test_fact_base_nft_trading_volume.yml, models/staging/base/fact_base_nft_trading_volume.sql, models/staging/optimism/_test_fact_optimism_nft_trading_volume.yml, models/staging/optimism/fact_optimism_nft_trading_volume.sql
1. Adding NFT Trading for Base and OP through ez metrics
=> NFT trading volume: Base, Optimism

models/data_hubs/fact_daily_app_datahub.sql, models/staging/meth/__meth__sources.yml, models/staging/meth/_test_fact_meth_staked_eth_count_with_USD_and_change.yml, models/staging/meth/fact_meth_staked_eth_count.sql, models/staging/meth/fact_meth_staked_eth_count_with_USD_and_change.sql, models/staging/meth/fact_meth_staked_eth_count_with_USD_and_change_gold.sql
=> Add Meth LSP

macros/p2p/filter_p2p_token_transfers.sql, models/projects/immutable_x/core/ez_immutable_x_metrics.sql, models/projects/tron/core/ez_tron_metrics.sql, models/staging/base/fact_base_nft_trading_volume.sql, models/staging/immutable_x/__immutable_x__sources.yml, models/staging/immutable_x/_test_fact_immutable_x_nft_trading_volume.yml, models/staging/immutable_x/fact_immutable_x_nft_trading_volume.sql, models/staging/optimism/fact_optimism_nft_trading_volume.sql, models/staging/tron/fact_tron_p2p_token_transfers.sql
1. Adding Tron P2P transfer volumes
2. Updating models for Base and OP for NFT Trading Volumes
3. Adding IMX NFT Trading Volume Models
=> BCC: Tron P2P Volumes, Base/OP NFT Trading Volumes

models/staging/sui/sui_trending_daily.sql, models/staging/sui/sui_trending_weekly_monthly.sql, models/trending/bam_trending_data.sql
=> Added Sui trending data

models/bam_models/all_chains/all_chains_gas_dau_txns_by_contract.sql
=> Fixed All chains contracts

models/staging/near/_test_fact_near_transactions.yml, models/staging/sui/sui_trending_weekly_monthly.sql
=> Add near slack and fixed sui trending

models/staging/sui/sui_trending_weekly_monthly.sql
=> Fixed Sui trending monthly

models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_base_gold.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_bsc_gold.sql, models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_ethereum_gold.sql
=> Added category to mavericks

models/dimensions/apps/dim_apps_post_sigma.sql, models/dimensions/apps/dim_apps_silver.sql
=> Udpate Visibility

models/staging/maverick/fact_maverick_daa_txns_gas_gas_usd_zksync_gold.sql
=> Added Maverick Category to Zksycn

models/trending/bam_trending_by_category.sql
=> Remove Null category

models/projects/arbitrum/core/ez_arbitrum_metrics.sql, models/projects/base/core/ez_base_metrics.sql, models/projects/optimism/core/ez_optimism_metrics.sql, models/staging/celo/__celo__sources.yml, models/staging/celo/fact_celo_epoch_reward_events.sql, models/staging/celo/fact_celo_events.sql
1. Creating `fact_celo_epoch_reward_events` and adding events to `fact_celo_transfers`
=> Adding Celo Epoch Events

models/metrics/stablecoins/contracts/fact_celo_stablecoin_contracts.sql
1. Tracking cEUR, cREAL, USDGLO on celo
=> Stablecoins - Update Celo Stablecoins

models/dimensions/apps/dim_flipside_namespaces.sql, models/dimensions/contracts/dim_contracts_silver.sql, models/dimensions/contracts/dim_flipside_contracts.sql, models/dimensions/contracts/dim_flipside_sei_contracts.sql
=> Added Sei labels

models/staging/sui/sui_trending_daily.sql
=> Fixed Sui daily trending

models/staging/sui/fact_sui_transactions.sql
=> Fixed Duplicates Error

macros/p2p/filter_p2p_token_transfers.sql, macros/p2p/p2p_native_transfers.sql, macros/p2p/p2p_token_transfers.sql, macros/wallets/distinct_eoa_addresses.sql, models/dimensions/wallet/dim_near_eoa_addresses.sql, models/metrics/stablecoins/contracts/fact_near_stablecoin_contracts.sql, models/projects/near/core/ez_near_metrics.sql, models/staging/near/_test_fact_near_p2p_transfer_volume.yml, models/staging/near/fact_near_p2p_native_transfers.sql, models/staging/near/fact_near_p2p_token_transfers.sql, models/staging/near/fact_near_p2p_token_transfers_silver.sql, models/staging/near/fact_near_p2p_transfer_volume.sql
1. Adding Near P2P volume models
=> P2P Volumes: Adding near models

models/staging/solana/solana_trending_daily.sql, models/staging/solana/solana_trending_weekly_monthly.sql
=> Fixed Solana Trending

models/staging/cardano/__cardano__sources.yml, models/staging/cardano/fact_cardano_daa.sql, models/staging/cardano/fact_cardano_txns.sql
=> Use new SF table for Cardano DAA

models/projects/internet_computer/core/ez_internet_computer_metrics.sql, models/staging/internet_computer/__internet_computer__sources.yml, models/staging/internet_computer/_test_fact_internet_computer_block_count.yml, models/staging/internet_computer/_test_fact_internet_computer_fundamental_metrics.yml, models/staging/internet_computer/fact_internet_computer_block_count_silver.sql, models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
=> Added Internet Computer Metrics

models/projects/internet_computer/core/ez_internet_computer_metrics.sql
=> fixed internet computer metrics

macros/nft/nft_trading_volume.sql, macros/p2p/filter_p2p_token_transfers.sql, macros/p2p/p2p_stablecoin_transfers.sql, models/staging/solana/fact_solana_p2p_token_transfers.sql, models/staging/starknet_bridge/fact_starknet_bridge_bridge_volume.sql, models/staging/starknet_bridge/fact_starknet_bridge_flows.sql, models/staging/wormhole/fact_wormhole_transfers.sql
1. Fixing Wormhole pricing data
2. Fixing Solana P2P Stablecoin Transfers
3. Fixing Solana P2P NFT Volume data
=> Fixing Solana and Bridge data

models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
=> Fixed ICP Burn Data

models/projects/sei/core/ez_sei_metrics.sql
=> Fix Sei prices

models/staging/sui/__sui__sources.yml
=> Migrate to new Zettablocks

models/dimensions/events/dim_events_silver.sql
1. Removing events with unsupported types from dim events for event decoding
=> Celo: Update dim_events

models/metrics/stablecoins/contracts/fact_celo_stablecoin_contracts.sql
1. Adding cUSD to `fact_celo_stablecoin_contracts`
=> Celo: Adding cUSD 

models/projects/celestia/core/ez_celestia_metrics.sql, models/staging/celestia/_test_fact_celestia_fees_usd.yml, models/staging/celestia/fact_celestia_fees_usd.sql
=> Alw celestia fees usd

udfs/base58_udfs.sql
=> adding base58-related udfs

models/dimensions/dim_all_supported_symbols_with_mc_rank.sql
=> Lower Category

macros/bridge/cctp_transfers.sql, models/projects/cctp/core/ez_cctp_metrics.sql, models/projects/cctp/core/ez_cctp_metrics_by_chain.sql, models/projects/ton/core/ez_ton_metrics.sql, models/staging/cctp/_test_fact_cctp_bridge_dau.yml, models/staging/cctp/_test_fact_cctp_bridge_volume.yml, models/staging/cctp/fact_cctp_bridge_dau.sql, models/staging/cctp/fact_cctp_bridge_volume.sql, models/staging/cctp/fact_cctp_flows.sql, models/staging/cctp/fact_cctp_transfers.sql
1. Adding CCTP through the bridges pipeline
```
fact_cctp_transfers
fact_cctp_flows
fact_cctp_bridge_volume
fact_cctp_bridge_dau
```
CCTP is not getting added to the flows page. This is because CCTP is a base layer that other bridges use
=> Bridges: adding CCTP

models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
1. Adding aurora to rainbow bridge
=> Updating rainbow bridge model

models/staging/across/__across__sources.yml, models/staging/across/fact_across_flows.sql, models/staging/across/fact_across_v3_transfers.sql
1. Adding support for Linea on the Across Models
=> Updating across to support Linea

models/projects/sei/core/ez_sei_metrics.sql, models/staging/sei/_test_fact_sei_avg_block_time.yml, models/staging/sei/fact_sei_avg_block_time_silver.sql
=> Changed Sei BPS to Block time

macros/rolling_active_addresses.sql, models/projects/sui/core/ez_sui_metrics.sql, models/staging/sui/_test_fact_sui_rolling_active_addresses.yml, models/staging/sui/fact_sui_rolling_active_addresses.sql
=> sui rolling mau/wau

models/metrics/revenue/agg_daily_arbitrum_revenue.sql
1. Fixing compilation error in agg_daily_arbitrum_revenue table
=> Customer 911: Daily Datahub Job Failure

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Stablecoins: Adding USDP

models/dimensions/dim_chain_ids.sql
1. Adding new chain `mode` to chain ids
=> C911: Bridge Job

models/data_hubs/fact_daily_app_datahub.sql, models/staging/stader/__ethx_staked_eth__sources.yml, models/staging/stader/fact_ethx_staked_eth_count.sql, models/staging/stader/fact_ethx_staked_eth_count_with_usd_and_change.sql
=> Add Stader

models/metrics/revenue/agg_daily_base_revenue.sql, models/metrics/revenue/agg_daily_blast_revenue.sql, models/metrics/revenue/agg_daily_optimism_revenue.sql, models/metrics/revenue/agg_daily_polygon_zk_revenue.sql
=> Fixed Revenue EVM Chains

models/projects/internet_computer/core/ez_internet_computer_metrics.sql, models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
=> Added ICP changes:

models/dimensions/dim_asset_datahub.sql
=> Update dim asset datahub

models/projects/bedrock/core/ez_bedrock_metrics_by_chain.sql, models/projects/cctp/core/ez_cctp_metrics_by_chain.sql, models/projects/eigenpie/core/ez_eigenpie_metrics_by_chain.sql, models/projects/etherfi/core/ez_etherfi_metrics_by_chain.sql, models/projects/kelp_dao/core/ez_kelp_dao_metrics_by_chain.sql, models/projects/puffer_finance/core/ez_puffer_finance_metrics_by_chain.sql, models/projects/rainbow_bridge/core/ez_rainbow_bridge_metrics.sql, models/projects/rainbow_bridge/core/ez_rainbow_bridge_metrics_by_chain.sql, models/projects/renzo_protocol/core/ez_renzo_protocol_metrics_by_chain.sql, models/projects/swell/core/ez_swell_metrics_by_chain.sql, models/staging/osmosis/__osmosis__sources.yml, models/staging/osmosis/fact_osmosis_gas_gas_usd_fees_revenue.sql, models/staging/osmosis/fact_osmosis_trading_fees.sql
1. Fixing Osmosis and types with protocol ez metric tables
=> Customer 911: Osmosis/Typos

models/projects/aave/core/ez_aave_metrics_by_chain.sql
1. Creating `ez_aave_metric_by_chain` table
=> AAVE: Creating Ez Metric Table

macros/p2p/p2p_stablecoin_transfers.sql, models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_solana_stablecoin_premint_addresses.sql
1. Adding PYUSD tracking to Solana
=> Stablecoins: Solana PYUSD

models/projects/compound/core/ez_compound_metrics_by_chain.sql
- Creating `ez_compound_metrics_by_chain`
`dbt run -s ez_compound_metrics_by_chain`
=> COMPOUND: Creating Ez Metric Table

models/staging/uniswap/fact_uniswap_v2_ethereum_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_arbitrum_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_avalanche_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_base_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_bsc_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_ethereum_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_optimism_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_polygon_trading_vol_fees_traders_by_pool.sql
1. Cleaning up full materialized tables for uniswap
=> Uniswap: Fix Polygon Asset

.github/workflows/show_changed_models.yml
1. Fixing error in request to listMembersInOrg. Passing in json
=> Github Actions update: Try 3

models/projects/sei/core/ez_sei_metrics.sql, models/staging/sei/_test_fact_sei_avg_block_time.yml, models/staging/sei/_test_fact_sei_daa_txns_gas_gas_usd_revenue.yml, models/staging/sei/fact_sei_avg_block_time_silver.sql, models/staging/sei/fact_sei_daa_txns_gas_gas_usd_revenue.sql
Combined all sei wasm and evm metrics to one.
=> Added Sei update

.github/workflows/show_changed_models.yml
1. Using a newly generated Github App initialization token to make an authenticated API request to data outside this repo but within the org.
=> Update Github Action Show Changes on Models

.github/workflows/show_changed_models.yml
Using `GITHUB_TOKEN` instead of `GH_TOKEN`
=> Update Github Action Again

models/staging/near/fact_near_transactions.sql
Added a where clause to filter out datapoints that are most recent which won't have transaciton fee.
=> Flipside work through

.github/workflows/show_changed_models.yml
1. Looking at maintainers of the repo rather than trying to get members of the org team `all`
=> Updating Github `Show On Change` 

.github/workflows/show_changed_models.yml
1. Fix workflow to return maintainers
2. Simplify workflow
3. add print statements to see what is returned
=> Github Action: Update workflow

models/staging/scroll/fact_scroll_gas_gas_usd_revenue.sql, models/staging/zora/fact_zora_gas_gas_usd_revenue.sql
=> Switched to coingecko prices

macros/contracts/distinct_contract_addresses.sql, macros/p2p/p2p_native_transfers.sql, macros/p2p/p2p_stablecoin_transfers.sql, macros/p2p/p2p_token_transfers.sql, macros/wallets/distinct_eoa_addresses.sql, models/dimensions/contracts/dim_arbitrum_contract_addresses.sql, models/dimensions/contracts/dim_avalanche_contract_addresses.sql, models/dimensions/contracts/dim_base_contract_addresses.sql, models/dimensions/contracts/dim_ethereum_contract_addresses.sql, models/dimensions/contracts/dim_optimism_contract_addresses.sql, models/dimensions/contracts/dim_polygon_contract_addresses.sql, models/dimensions/wallet/dim_arbitrum_eoa_addresses.sql, models/dimensions/wallet/dim_avalanche_eoa_addresses.sql, models/dimensions/wallet/dim_base_eoa_addresses.sql, models/dimensions/wallet/dim_ethereum_eoa_addresses.sql, models/dimensions/wallet/dim_optimism_eoa_addresses.sql, models/dimensions/wallet/dim_polygon_eoa_addresses.sql, models/staging/solana/fact_solana_p2p_native_transfers.sql, models/staging/solana/fact_solana_p2p_stablecoin_transfers.sql, models/staging/solana/fact_solana_p2p_token_transfers_silver.sql, models/staging/tron/fact_tron_p2p_native_transfers.sql, models/staging/tron/fact_tron_p2p_stablecoin_transfers.sql, models/staging/tron/fact_tron_p2p_token_transfers_silver.sql
1. Creating `dim_<chain>_contract_addresses` for EVM chains
2. Lazily get p2p transfers by saying not in contract_addresses table
=> P2P: Updating Methodology

models/projects/radiant/core/ez_radiant_metrics_by_chain.sql
- Similar to https://github.com/Artemis-xyz/dbt/pull/116/ for AAVE
- CI + created warehouse and associated DB
=> Add ez radiant_metrics_by_chain

models/projects/celestia/core/ez_celestia_metrics.sql, models/staging/frax/fact_frax_staked_eth_count.sql, models/staging/lido/fact_lido_staked_eth_count.sql, models/staging/mantle/fact_meth_staked_eth_count.sql, models/staging/rocketpool/fact_rocketpool_staked_eth_count.sql, models/staging/stakewise/fact_stakewise_staked_eth_count.sql
1. Remove the current date from LST dbt models that have a full refresh.
=> C911: LST Jobs Failing due to pricing issue

models/projects/linea/core/ez_linea_metrics.sql, models/staging/linea/fact_linea_daa.sql, models/staging/linea/fact_linea_gas_gas_usd_revenue.sql, models/staging/linea/fact_linea_transactions.sql, models/staging/linea/fact_linea_txns.sql
1. creating ez metrics migration
=> Chains: Linea

models/projects/fuse/core/ez_fuse_metrics.sql, models/staging/fuse/fact_fuse_daa.sql, models/staging/fuse/fact_fuse_daa_txns_gas_gas_usd.sql, models/staging/fuse/fact_fuse_gas_gas_usd.sql, models/staging/fuse/fact_fuse_txns.sql
1. Creating ez fuse metrics table
=> Chains: Fuse

models/projects/zora/core/ez_zora_metrics.sql, models/staging/zora/fact_zora_daa.sql, models/staging/zora/fact_zora_gas_gas_usd_revenue.sql, models/staging/zora/fact_zora_transactions.sql, models/staging/zora/fact_zora_txns.sql, models/staging/zora/fact_zora_txns_gold.sql
1. Creating Zora ez metrics table
=> Chains: Zora

models/projects/multiversx/core/ez_multiversx.sql, models/projects/scroll/core/ez_scroll_metrics.sql, models/projects/zcash/core/ez_zcash_metrics.sql, models/staging/multiversx/fact_multiversx_daa.sql, models/staging/multiversx/fact_multiversx_txns.sql, models/staging/scroll/fact_scroll_daa.sql, models/staging/scroll/fact_scroll_gas_gas_usd_revenue.sql, models/staging/scroll/fact_scroll_txns.sql, models/staging/scroll/fact_scroll_txns_gold.sql, models/staging/zcash/fact_zcash_gas_gas_usd_txns.sql
Creating ez metrics tables for:
`scroll`
`zcash`
`multiversx`
=> Chains: Scroll, Zcash, MultiverseX

models/projects/axelar/core/ez_axelar_metrics.sql, models/projects/gnosis/core/ez_gnosis_metrics.sql, models/projects/mantle/core/ez_mantle_metrics.sql, models/projects/parallel_finance/core/ez_parallel_finance_metrics.sql, models/staging/axelar/fact_axelar_daa_txns.sql, models/staging/gnosis/fact_gnosis_blocks.sql, models/staging/gnosis/fact_gnosis_daa_txns_gas_gas_usd.sql, models/staging/mantle/fact_mantle_daa.sql, models/staging/mantle/fact_mantle_daa_txns_gas_gas_usd_revenue.sql, models/staging/mantle/fact_mantle_expenses.sql, models/staging/mantle/fact_mantle_gas.sql, models/staging/mantle/fact_mantle_txns.sql, models/staging/parallel_finance/fact_parallel_finance_daa.sql, models/staging/parallel_finance/fact_parallel_finance_daa_gas_gas_usd_txns.sql, models/staging/parallel_finance/fact_parallel_finance_gas_gas_usd.sql, models/staging/parallel_finance/fact_parallel_finance_txns.sql
Creating ez metric tables for
`parallel`
`mantle`
`gnosis`
`axelar`
=> Chains Migrations: Mantle, Parallel, Gnosis, Axelar

models/projects/quickswap/core/ez_quickswap_metrics_by_chain.sql, models/projects/quickswap/core/ez_quickswap_metrics_by_pool.sql, models/projects/quickswap/raw/ez_quickswap_dex_swaps.sql, models/staging/quickswap/fact_quickswap_polygon_dex_swaps.sql, models/staging/quickswap/fact_quickswap_polygon_trading_vol_fees_traders_by_pool.sql, models/staging/quickswap/fact_quickswap_polygon_tvl_by_pool.sql
1. Creating the ez quickswap tables and moving quickswap over to the new dex pipeline
=> ez quickswap

models/metrics/stablecoins/contracts/fact_solana_stablecoin_premint_addresses.sql
Removed a pre-mint address that wasn't actually a pre-mint :) 
Verified this fixed supply # to tie with Solscan
=> Fix PYUSD Solana Supply

models/projects/uniswap/raw/ez_uniswap_dex_swaps.sql, models/staging/solana/fact_solana_p2p_native_transfers.sql, models/staging/solana/fact_solana_p2p_stablecoin_transfers.sql, models/staging/solana/fact_solana_p2p_token_transfers_silver.sql
1. Fixing uniswap `ez_dex_swaps` compilation error
2. Making solana p2p metrics incremental
=> C911: Uniswap, Solana

macros/decentralized_exchanges/fact_curve_daily_metrics.sql, macros/decentralized_exchanges/fact_curve_dex_swaps.sql, macros/decentralized_exchanges/fact_curve_tvl_by_pool.sql, macros/decentralized_exchanges/fact_uniswap_v2_fork_dex_swaps.sql, models/projects/curve/core/ez_curve_metrics_by_chain.sql, models/projects/curve/core/ez_curve_metrics_by_pool.sql, models/projects/curve/raw/ez_curve_dex_swaps.sql, models/projects/pancakeswap/raw/ez_pancakeswap_dex_swaps.sql, models/staging/curve/dim_curve_pools.sql, models/staging/curve/fact_curve_arbitrum_daily_trading_metrics.sql, models/staging/curve/fact_curve_arbitrum_dex_swaps.sql, models/staging/curve/fact_curve_arbitrum_tvl_by_pool.sql, models/staging/curve/fact_curve_avalanche_daily_trading_metrics.sql, models/staging/curve/fact_curve_avalanche_dex_swaps.sql, models/staging/curve/fact_curve_avalanche_tvl_by_pool.sql, models/staging/curve/fact_curve_ethereum_daily_trading_metrics.sql, models/staging/curve/fact_curve_ethereum_dex_swaps.sql, models/staging/curve/fact_curve_ethereum_tvl_by_pool.sql, models/staging/curve/fact_curve_optimism_daily_trading_metrics.sql, models/staging/curve/fact_curve_optimism_dex_swaps.sql, models/staging/curve/fact_curve_optimism_tvl_by_pool.sql, models/staging/curve/fact_curve_polygon_daily_trading_metrics.sql, models/staging/curve/fact_curve_polygon_dex_swaps.sql, models/staging/curve/fact_curve_polygon_tvl_by_pool.sql, models/staging/pancakeswap/fact_pancakeswap_v2_bsc_dex_swaps.sql
1. Adding curve ez metrics
2. Fixing pancakeswap bugs
=> Ez Curve + Dex Bugs

macros/decentralized_exchanges/fact_curve_daily_metrics.sql, macros/decentralized_exchanges/fact_curve_tvl_by_pool.sql
Fixing SQL compilation errors with curve models
=> Curve: Fixing SQL Compilation Errors 

models/staging/zksync/fact_zksync_revenue.sql
Tracking 2 new contract for zksync, they no longer use the contract we were tracking for revenue.
=> Zksync: adding new contract

models/data_hubs/fact_daily_app_datahub.sql
=> Remove friendly_name from app datahub

macros/metrics/get_contract_metrics.sql
1. changing get_contract_metrics to remove dependency on the gold table.
=> rm rf fact_chain_contract_gold dep.

macros/p2p/filter_p2p_token_transfers.sql, macros/p2p/p2p_token_transfers.sql
Fix Solana Stablecoin being stale.
=> Updated Solana Flipside Pricing Table

models/staging/fuse/fact_fuse_daa_txns_gas_gas_usd_gold.sql, models/staging/mantle/fact_mantle_daa_txns_gas_gas_usd_revenue_gold.sql
=> rm fuse, mantle orphaned

models/staging/aevo/fact_aevo_trading_volume_gold.sql, models/staging/apex/fact_apex_trading_volume_gold.sql, models/staging/bluefin/fact_bluefin_trading_volume_gold.sql
=> rm rf orphaned gold perps

models/staging/parallel_finance/fact_parallel_finance_daa_gas_gas_usd_txns_gold.sql
=> rm parallel finance orphaned

models/staging/zcash/fact_zcash_gas_gas_usd_txns_gold.sql
=> rm zcash orphaned

models/staging/polkadot/fact_polkadot_daa_txns_gas_gas_usd_revenue_gold.sql
=> rm polkadot orphaned

models/staging/stride/fact_stride_daa_gas_usd_txns_gold.sql
=> rm stride orphaned

models/metrics/revenue/agg_daily_gnosis_revenue_gold.sql, models/staging/gnosis/fact_gnosis_daa_txns_gas_gas_usd_gold.sql
=> rm gnosis orphaned

models/staging/acala/fact_acala_daa_txns_gas_gas_usd_revenue_gold.sql, models/staging/aptos/fact_aptos_daa_txns_gas_gas_usd_revenue_gold.sql, models/staging/axelar/fact_axelar_daa_txns_gold.sql, models/staging/axie/fact_axie_sales_data_gold.sql
To do:
1. Remove all of Axie, it has never been materialized
=> rm axie, aptos, acala, axelar orphaned

models/staging/zora/fact_zora_daa_gold.sql, models/staging/zora/fact_zora_gas_gas_usd_revenue_gold.sql, models/staging/zora/fact_zora_txns_gold.sql
=> rm zora orphaned

models/staging/osmosis/fact_osmosis_daa_txns_gold.sql, models/staging/osmosis/fact_osmosis_gas_gas_usd_fees_revenue_gold.sql
=> rm osmosis orphaned

models/staging/fantom/fact_fantom_daa_gold.sql, models/staging/fantom/fact_fantom_gas_gas_usd_fees_revenue_gold.sql, models/staging/fantom/fact_fantom_txns_gold.sql
=> rm fantom orphaned

models/staging/linea/fact_linea_daa_gold.sql, models/staging/linea/fact_linea_gas_gas_usd_revenue_gold.sql, models/staging/linea/fact_linea_txns_gold.sql
=> rm linea orphaned

models/staging/stacks/fact_stacks_daa_txns_gold.sql, models/staging/stacks/fact_stacks_native_fees_gold.sql
=> rm stacks orphaned

models/staging/cosmoshub/fact_cosmoshub_daa_gold.sql, models/staging/cosmoshub/fact_cosmoshub_fees_and_revenue_gold.sql, models/staging/cosmoshub/fact_cosmoshub_txns_gold.sql
=> rm cosmoshub orphaned

models/staging/multiversx/fact_multiversx_daa_gold.sql, models/staging/multiversx/fact_multiversx_txns_gold.sql
=> rm multiversx orphaned

models/staging/flow/fact_flow_daa_txns_gold.sql, models/staging/flow/fact_flow_fees_revs_gold.sql
=> rm flow orphaned

models/staging/cardano/fact_cardano_daa_gold.sql, models/staging/cardano/fact_cardano_fees_and_revenue_gold.sql, models/staging/cardano/fact_cardano_txns_gold.sql
=> rm cardano orphaned

models/staging/scroll/fact_scroll_daa_gold.sql, models/staging/scroll/fact_scroll_gas_gas_usd_revenue_gold.sql, models/staging/scroll/fact_scroll_txns_gold.sql
=> rm scroll orgpaned tables

models/staging/zksync/fact_zksync_daa_txns_gas_gas_usd_gold.sql, models/staging/zksync/fact_zksync_revenue_gold.sql
=> rm zksync orphaned tables

models/staging/ton/fact_ton_dex_volumes.sql
1. Fixing down stream dependencies for TON DEX Data
=> Fix: Ton Dex Volumes

models/staging/ethereum/agg_base_stablecoin_balances.sql
=> Add Base balances table

models/projects/chainlink/prod_raw/fact_chainlink_ethereum_ocr_operator_admin_meta.sql, models/projects/chainlink/prod_raw/fact_chainlink_ethereum_ocr_reward_daily.sql, models/projects/chainlink/prod_raw/fact_chainlink_ethereum_ocr_reward_evt_transfer.sql, models/projects/chainlink/prod_raw/fact_chainlink_ethereum_ocr_reward_evt_transfer_daily.sql, models/projects/chainlink/prod_raw/fact_chainlink_ethereum_ocr_reward_transmission_logs.sql, models/staging/solana/agg_solana_daily_stablecoin_metrics_breakdown.sql
Creating all the chainlink OCR Reward tables and dependencies
=> Fidelity: Chainlink OCR Rewards

models/staging/chainlink/fact_chainlink_ethereum_vrf_request_fulfilled.sql, models/staging/chainlink/fact_chainlink_ethereum_vrf_request_fulfilled_daily.sql, models/staging/chainlink/fact_chainlink_ethereum_vrf_rewards_daily.sql, models/staging/chainlink/fact_chainlink_ethereum_vrf_v1_random_fulfilled_logs.sql, models/staging/chainlink/fact_chainlink_ethereum_vrf_v1_random_request_logs.sql, models/staging/chainlink/fact_chainlink_ethereum_vrf_v2_random_fulfilled_logs.sql
Adding chainlink vrf fees models
=> adding vrf fees models

models/staging/base/agg_base_daily_stablecoin_metrics_breakdown.sql
=> Update unique key for Base

macros/metrics/get_fundamental_data_for_chain.sql
=> Increase time window of Near DAU adjusted calc

macros/stablecoins/agg_daily_stablecoin_metrics_breakdown.sql, macros/stablecoins/agg_foward_filled_stablecoin_balances_by_addresses.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown.sql, models/staging/solana/agg_solana_daily_stablecoin_metrics_breakdown.sql, models/staging/solana/agg_solana_stablecoin_balances.sql
1. Creating a column in the metrics macro called `is_wallet`. We will be able to use this to get the wallet supply
2. Removing DAU columns 
3. Adding Solana models
=> Stablecoin V2: Solana and Is Wallet Column

models/projects/chainlink/prod_core/ez_chainlink_metrics.sql, models/projects/chainlink/prod_core/ez_chainlink_metrics_by_chain.sql, models/projects/chainlink/prod_raw/fact_chainlink_fdv_and_turnover.sql
1. Adding chainlink ez metrics and ez metrics by chain
=> Chainlink: EZ Metrics

macros/metrics/get_fundamental_data_for_chain.sql
=> Calculate adjusted Near DAU for all of time

models/projects/ton/raw/ez_ton_stablecoin_transfers.sql, models/staging/ton/fact_ton_stablecoin_transfers.sql
=> Added Ton address types

macros/address_balances/current_address_balances.sql, macros/stablecoins/agg_chain_stablecoin_breakdown.sql, models/metrics/stablecoins/breakdowns/daily/agg_stablecoin_breakdown_daily.sql, models/metrics/stablecoins/breakdowns/daily/agg_ton_stablecoin_breakdown_daily.sql, models/metrics/stablecoins/breakdowns/monthly/agg_stablecoin_breakdown_monthly.sql, models/metrics/stablecoins/breakdowns/monthly/agg_ton_stablecoin_breakdown_monthly.sql, models/metrics/stablecoins/breakdowns/weekly/agg_stablecoin_breakdown_weekly.sql, models/metrics/stablecoins/breakdowns/weekly/agg_ton_stablecoin_breakdown_weekly.sql, models/metrics/stablecoins/metrics/agg_daily_stablecoin_metrics_silver.sql, models/projects/ton/core/__ez_ton_core_sources__.yml, models/projects/ton/core/ez_ton_address_balances_by_token.sql, models/projects/ton/core/ez_ton_current_balances.sql, models/projects/ton/raw/ez_ton_stablecoin_transfers.sql, models/staging/ton/fact_ton_address_credit_by_token.sql, models/staging/ton/fact_ton_address_debit_by_token.sql, models/staging/ton/fact_ton_stablecoin_contracts.sql, models/staging/ton/fact_ton_stablecoin_transfers.sql
Added all the models to add ton to the stablecoin dashboard this includes:
ton debit + credit
ton balances
ton stablecoin breakdowns
=> Ton stablecoin models

models/projects/ton/raw/ez_ton_stablecoin_transfers.sql
=> Fix Ton Stablecoins

macros/chains/transfrom_avalanche_subnets_fundamental_data.sql
Needed to push avalanche dates by 1
=> Fix avalanche subnets

models/projects/ton/core/ez_ton_app_open_league.sql, models/projects/ton/core/ez_ton_token_open_league.sql, models/staging/ton/__ton__sources.yml, models/staging/ton/dim_ton_open_league_dates.sql, models/staging/ton/fact_ton_app_open_league.sql, models/staging/ton/fact_ton_token_open_league.sql
=> Updated Ton Open League models to ez tables

models/projects/akash/core/ez_akash_metrics.sql, models/staging/akash/__akash__sources.yml, models/staging/akash/fact_akash_burns_native_silver.sql, models/staging/akash/fact_akash_mints_silver.sql
=> adding akash mints and burns data

models/staging/ton/dim_ton_open_league_dates.sql
=> Added Season 5 to Ton Open League

models/projects/akash/core/ez_akash_metrics.sql
=> Alw akash dates fix

macros/create_ez_transactions.sql, macros/metrics/get_fundamental_data_for_chain.sql, models/staging/near/fact_near_transactions.sql
=> Added from_address_adjusted for near

dbt_project.yml
Fixing `uwu_lend` node name (`uwulend` -> `uwu_lend`) in `dbt_project.yml`
=> Fix uwu_lend node name

dbt_project.yml, models/staging/avalanche/fact_avalanche_amount_staked_silver.sql, models/staging/beam/fact_beam_fundamental_metrics.sql, models/staging/polygon/fact_polygon_daily_sleep.sql, models/staging/polygon/fact_polygon_p2p_native_transfers.sql, models/staging/stride/fact_stride_rolling_active_addresses.sql, models/staging/stride/fact_stride_txns.sql, models/staging/sushiswap/fact_sushiswap_v2_arbitrum_trading_vol_fees_traders_by_pool.sql, models/staging/sushiswap/fact_sushiswap_v2_avalanche_dex_swaps.sql, models/staging/sushiswap/fact_sushiswap_v2_bsc_trading_vol_fees_traders_by_pool.sql, models/staging/tron/fact_tron_rolling_active_addresses.sql, models/staging/uniswap/fact_uniswap_v2_ethereum_dex_swaps.sql, models/staging/uniswap/fact_uniswap_v2_ethereum_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_base_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_bsc_dex_swaps.sql, models/staging/uniswap/fact_uniswap_v3_bsc_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_ethereum_dex_swaps.sql, models/staging/uniswap/fact_uniswap_v3_ethereum_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_optimism_dex_swaps.sql, models/staging/uniswap/fact_uniswap_v3_optimism_trading_vol_fees_traders_by_pool.sql, models/staging/uniswap/fact_uniswap_v3_polygon_dex_swaps.sql
- Fix WH name for Seamless (should be `SEAMLESSPROTOCOL`)
- Remove model-level configs for remaining staging models
=> Update Staging Warehouses

models/projects/ton/core/__ez_ton_core_sources__.yml, models/projects/ton/core/ez_ton_token_open_league.sql
=> Used Coingecko Price Data when available

models/projects/ton/core/ez_ton_token_open_league.sql
=> Convert TOL DEX TVL to usd

models/staging/wormhole/fact_wormhole_flows.sql
Adding additional chain constants from 
https://docs.wormhole.com/wormhole/reference/constants
=> Add additional chains to fact_wormhole_flows

models/common/__common__sources.yml, models/common/daily_market_data.sql
Added FDMC and some other fields for KRC
=> Add more fields to CoinGecko share

models/staging/wormhole/fact_wormhole_flows.sql
=> Fix Syntax Error in fact_wormhole_flows

macros/stablecoins/stablecoin_balances.sql, macros/stablecoins/stablecoin_metrics.sql, models/projects/ethereum/core/ez_ethereum_stablecoin_metrics_by_address.sql, models/staging/ethereum/fact_ethereum_stablecoin_balances.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_all.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_artemis.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_p2p.sql
1. Creating the Ethereum stablecoin v2 Pipeline
2. Fix the incremental run of the balances table
3. Create all metric tables
4. Create stablecoin balances table
To Do: 
1. The ethereum breakdown table needs a full backfill. I will work on making this table incremental while this table runs in prod.
=> Stablecoin V2: Ethereum 

macros/stablecoins/stablecoin_metrics.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql, models/projects/ethereum/core/ez_ethereum_stablecoin_metrics_by_address.sql
1. Update `Stablecoin_balance` macro to be incremental and rewrite the previous  day
2. Add Arbitrum on to final agg table
=> Stablecoin V2: Arbitrum, Stablcoin Balances

models/projects/ton/core/ez_ton_metrics.sql, models/staging/ton/fact_ton_app_fees_txns.sql
=> Fix Nit errors for Ton Models

macros/address_balances/address_balances_by_token.sql, macros/stablecoins/genesis_stablecoin_balances.sql, models/projects/optimism/core/ez_optimism_stablecoin_metrics_by_address.sql, models/staging/optimism/__optimism__sources.yml, models/staging/optimism/fact_optimism_genesis_stablecoin_balances.sql, models/staging/optimism/fact_optimism_stablecoin_balances.sql, models/staging/optimism/fact_optimism_stablecoin_metrics_all.sql, models/staging/optimism/fact_optimism_stablecoin_metrics_artemis.sql, models/staging/optimism/fact_optimism_stablecoin_metrics_p2p.sql
1. Generating the Genesis Stablecoin Balances and fixing op stablecoin balances.
2. Creating all Op stablecoin tables
To Do:
1. Refresh P2P in Production
2. Run Metrics Table
=> Stablecoin V2: Optimism Pipeline

models/projects/injective/core/ez_injective_metrics.sql, models/projects/injective/core/ez_injective_metrics_by_application.sql, models/projects/injective/core/ez_injective_metrics_by_category.sql, models/projects/injective/core/ez_injective_metrics_by_contract.sql
- Remove date offset from injective models, but maintain timezone conversion
- Fixed tz type in upstream source
=> Remove Date Adjustment from Injective Models

macros/stablecoins/stablecoin_metrics_all.sql, models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_all.sql, models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_artemis.sql, models/staging/arbitrum/fact_arbitrum_stablecoin_metrics_p2p.sql, models/staging/base/fact_base_stablecoin_metrics_all.sql, models/staging/base/fact_base_stablecoin_metrics_artemis.sql, models/staging/base/fact_base_stablecoin_metrics_p2p.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_all.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_artemis.sql, models/staging/ethereum/fact_ethereum_stablecoin_metrics_p2p.sql
=> Stablecoin V2: Make Ethereum Arb, Base incremental

macros/stablecoins/stablecoin_metrics.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql, models/staging/optimism/dim_optimism_genesis_dai_addresses.sql
1. Adding optimism stablecoin to `agg_daily_stablecoin_breakdown_silver`
2. Creating `dim_optimism_genesis_dai_addresses`
3. See this PR for more details: https://github.com/Artemis-xyz/gokustats-back-end/pull/2216
=> Stablecoin V2: Optimism

models/projects/polygon/core/ez_polygon_stablecoin_metrics_by_address.sql, models/staging/polygon/fact_polygon_stablecoin_balances.sql, models/staging/polygon/fact_polygon_stablecoin_metrics_all.sql, models/staging/polygon/fact_polygon_stablecoin_metrics_artemis.sql, models/staging/polygon/fact_polygon_stablecoin_metrics_p2p.sql
1. Adding Polygon Stablecoin V2 models
To Do: 
1. Finish backfilling Polygon stablecoin balances
2. Backfill polygon metrics table
=> Stablecoin V2: Polygon

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
1. Adding `tron` and `polygon` to `agg_daily_stablecoin_breakdown_silver`
=> Stablecoin V2: Polygon, Tron

models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql
- Rollup all ibc chains into `cosmos_ecosystem`  as src/dest
=> Create injective_ibc Rollup

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
1. After fixing the ethereum DAI supply and backfilling the metrics table, this PR adds the Ethereum Table to final `agg` table
=> Stablecoin V2: Ethereum DAI

macros/lending/lending_flashloan_fees.sql, macros/lending/lending_liquidation_revenue.sql, models/projects/aave/raw/arbitrum/fact_aave_v3_arbitrum_flashloan_fees.sql, models/projects/aave/raw/arbitrum/fact_aave_v3_arbitrum_liquidation_revenue.sql, models/projects/aave/raw/avalanche/fact_aave_v2_avalanche_flashloan_fees.sql, models/projects/aave/raw/avalanche/fact_aave_v2_avalanche_liquidation_revenue.sql, models/projects/aave/raw/avalanche/fact_aave_v3_avalanche_flashloan_fees.sql, models/projects/aave/raw/avalanche/fact_aave_v3_avalanche_liquidation_revenue.sql, models/projects/aave/raw/base/fact_aave_v3_base_flashloan_fees.sql, models/projects/aave/raw/base/fact_aave_v3_base_liquidation_revenue.sql, models/projects/aave/raw/bsc/fact_aave_v3_bsc_liquidation_revenue.sql, models/projects/aave/raw/ethereum/fact_aave_v2_ethereum_flashloan_fees.sql, models/projects/aave/raw/ethereum/fact_aave_v2_ethereum_liquidation_revenue.sql, models/projects/aave/raw/ethereum/fact_aave_v3_ethereum_flashloan_fees.sql, models/projects/aave/raw/ethereum/fact_aave_v3_ethereum_liquidation_revenue.sql, models/projects/aave/raw/gnosis/fact_aave_v3_gnosis_flashloan_fees.sql, models/projects/aave/raw/gnosis/fact_aave_v3_gnosis_liquidation_revenue.sql, models/projects/aave/raw/optimism/fact_aave_v3_optimism_flashloan_fees.sql, models/projects/aave/raw/optimism/fact_aave_v3_optimism_liquidation_revenue.sql, models/projects/aave/raw/polygon/fact_aave_v2_polygon_flashloan_fees.sql, models/projects/aave/raw/polygon/fact_aave_v2_polygon_liquidation_revenue.sql, models/projects/aave/raw/polygon/fact_aave_v3_polygon_flashloan_fees.sql, models/projects/aave/raw/polygon/fact_aave_v3_polygon_liquidation_revenue.sql
1. Create the liquidation revenue models
2. Create Flashloan Fee models
=> Fidelity: AAVE

macros/rolling_active_addresses.sql, models/projects/bitcoin/core/ez_bitcoin_metrics.sql, models/staging/bitcoin/fact_bitcoin_rolling_active_addresses.sql
1. Adding MAU and WAU for Bitcoin
=> Bitcoin: MAU and WAU

models/staging/celestia/fact_celestia_namespaces_blob_sizes_silver.sql
1. Fixing Celestia dbt sql
https://github.com/Artemis-xyz/gokustats-back-end/pull/2268
=> C911: Celestia

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
1. Addin tron to final metric table
=> Stablecoin V2: Tron 

models/projects/maker/prod_raw/fact_treasury_lp_balances.sql
- Maker treasury data, specifically UNI V2 LP data, was not forward filling correctly, so there were days where there was missing data
- All fixed now
=> fixing Maker DQ issue (treasury data not forward filled)

models/projects/maker/prod_raw/fact_treasury_lp_balances.sql
=> C911 Fixing maker

models/projects/maker/prod_raw/fact_treasury_lp_balances.sql
1. Fixing maker 
https://github.com/Artemis-xyz/dbt/pull/357/files
=> C911: Pushing maker fix

models/projects/maker/prod_raw/fact_treasury_lp_balances.sql
Maker fix - referencing wrong table.
=> mkr quick fix + removing some nulls

macros/contracts/distinct_contract_addresses.sql, macros/p2p/p2p_stablecoin_transfers.sql, models/dimensions/contracts/dim_ton_contract_addresses.sql, models/projects/ton/raw/ez_ton_stablecoin_transfers.sql, models/staging/ton/fact_ton_stablecoin_transfers.sql
Add ton stablecoin contracts dim models.
=> Add Ton stablecoin contracts Dimension Model

macros/p2p/p2p_stablecoin_transfers.sql, macros/stablecoins/stablecoin_balances.sql, macros/stablecoins/stablecoin_metrics_all.sql, macros/stablecoins/stablecoin_metrics_artemis.sql, macros/stablecoins/stablecoin_metrics_p2p.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql, models/projects/ton/core/ez_ton_stablecoin_metrics_by_address.sql, models/projects/ton/raw/ez_ton_p2p_stablecoin_transfers.sql, models/projects/ton/raw/ez_ton_stablecoin_transfers.sql, models/staging/ton/fact_ton_stablecoin_balances.sql, models/staging/ton/fact_ton_stablecoin_metrics_all.sql, models/staging/ton/fact_ton_stablecoin_metrics_artemis.sql, models/staging/ton/fact_ton_stablecoin_metrics_p2p.sql
1. Adding ton stablecoin tables
=> Stablecoin V2: Ton

macros/lending/aave_reserve_factor_revenue.sql, macros/lending/raw_aave_rpc_data.sql, models/projects/aave/core/ez_aave_metrics.sql, models/projects/aave/core/ez_aave_metrics_by_chain.sql, models/projects/aave/core/ez_aave_metrics_by_token.sql, models/projects/aave/raw/arbitrum/raw_aave_v3_arbitrum_rpc_data.sql, models/projects/aave/raw/avalanche/raw_aave_v2_avalanche_rpc_data.sql, models/projects/aave/raw/avalanche/raw_aave_v3_avalanche_rpc_data.sql, models/projects/aave/raw/base/raw_aave_v3_base_rpc_data.sql, models/projects/aave/raw/bsc/raw_aave_v3_bsc_rpc_data.sql, models/projects/aave/raw/ethereum/raw_aave_v2_ethereum_rpc_data copy.sql, models/projects/aave/raw/ethereum/raw_aave_v3_ethereum_rpc_data.sql, models/projects/aave/raw/gnosis/raw_aave_v3_gnosis_rpc_data.sql, models/projects/aave/raw/optimism/raw_aave_v3_optimism_rpc_data.sql, models/projects/aave/raw/polygon/raw_aave_v2_polygon_rpc_data.sql, models/projects/aave/raw/polygon/raw_aave_v3_polygon_rpc_data.sql
1. Adding final aave metrics `net_treasury` and `treasury_value_native`
2. Adding raw aave tables
=> Fidelity AAVE

models/projects/ton/raw/ez_ton_p2p_stablecoin_transfers.sql
1. Forcing Ton P2P Stablecoin Lineage
=> Stablecoin V2: Forcing Ton P2P Lineage

macros/p2p/p2p_stablecoin_transfers.sql
1. The job was trying to find tables in the wrong warehouse and schema. Updated the macro
=> C911: ton stablecoin job

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown.sql
1. Removing clustering for now. Can add this back in the future once we get some use on the data
=> Stablecoin V2: removing clustering

models/common/ez_stablecoin_metrics_by_address.sql
1. Adding Stablecoin V2 table to common database
=> Stablecoin V2: Adding to Common Database 

models/projects/arbitrum/raw/ez_arbitrum_stablecoin_transfers.sql, models/projects/avalanche/raw/ez_avalanche_stablecoin_transfers.sql, models/projects/base/raw/ez_base_stablecoin_transfers.sql, models/projects/bsc/raw/ez_bsc_stablecoin_transfers.sql, models/projects/celo/raw/ez_celo_stablecoin_transfers.sql, models/projects/ethereum/raw/ez_ethereum_stablecoin_transfers.sql, models/projects/optimism/raw/ez_optimism_stablecoin_transfers.sql, models/projects/polygon/raw/ez_polygon_stablecoin_transfers.sql, models/projects/solana/raw/ez_solana_stablecoin_transfers.sql, models/projects/tron/raw/ez_tron_stablecoin_transfers.sql
1. Adding all stablecoin transfers to art_share
=> Adding stablecoin transfers to Art Share

macros/flows/get_category_inflows.sql, macros/flows/get_category_outflows.sql, models/metrics/flows/agg_daily_category_inflows_by_chain.sql, models/metrics/flows/agg_daily_category_outflows_by_chain.sql, models/staging/optimism/fact_optimism_category_inflows.sql, models/staging/optimism/fact_optimism_category_outflows.sql
Built Models to power the chain specific sankeys. Enabled flipping from inflow to outflows.
=> Optimism Models to Flip the Chain Flow Sankey

models/projects/polygon/core/ez_polygon_metrics.sql
adding l1 data cost to polygon ez_metrics table
=> Polygon: Add L1 Da Cost

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown.sql
Add clustering to Stablecoin table
=> Stablecoin V2: Clustering

models/dimensions/contracts/dim_ethereum_contract_addresses.sql, models/projects/ethereum/raw/dim_ethereum_contract_addresses.sql
Adding `dim_ethereum_contracts_addresses` to `art_share`
=> Ethereum: Share `dim_contracts_addresses`

models/staging/ton/fact_ton_fundamental_metrics.sql
=> Fix Fact Ton DAU

macros/stablecoins/stablecoin_ez_metrics.sql, models/projects/usdc/core/ez_usdc_metrics.sql
I built a macro to make it easier for us to add new stablecoin ez metrics! This way we won't need to keep copying the same query over and over again. A macro is like a function that takes in some arguments to build similar code.
=> Added macros for adding new stablecoins

models/staging/starknet/fact_starknet_transactions.sql
1. Changing the Starknet tables to rely on dune
=> Starknet: Dune

macros/metrics/get_coingecko_metrics.sql
Fixing Division by zero from celo, osmosis, and mantle 
Ex. https://artemis.dagster.cloud/prod/runs/55883d47-3c46-4cba-811a-ae241af7f94e?logFileKey=afdhriui&selection=%22run_dbt_d2c55%22&logs=query%3A%22run_dbt_d2c55%22
=> Coingecko fixing division by zero

macros/stablecoins/stablecoin_breakdown.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_category.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_category_chain.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_category_symbol.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_category_symbol_chain.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_symbol.sql, models/metrics/stablecoins/breakdowns/agg_monthly_stablecoin_breakdown_symbol_chain.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category_chain.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category_symbol.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_category_symbol_chain.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_symbol.sql, models/metrics/stablecoins/breakdowns/agg_weekly_stablecoin_breakdown_symbol_chain.sql
1. Creating Monthly and Weekly Breakdowns for stablecoin metrics
=> Stablecoin V2.5: Adding weekly and monthly breakdowns

models/projects/polymarket/core/ez_polymarket_metrics.sql, models/staging/polymarket/__polymarket__sources.yml, models/staging/polymarket/fact_polymarket_prediction_markets.sql
=> Add polymarket trump and kamala metrics

models/projects/drift/core/ez_drift_metrics.sql, models/projects/polymarket/core/ez_polymarket_metrics.sql, models/staging/drift/__drift__sources.yml, models/staging/drift/fact_drift_prediction_markets.sql, models/staging/polymarket/__polymarket__sources.yml, models/staging/polymarket/fact_polymarket_prediction_markets.sql
=> Add sell metrics for drift + polymarket

macros/stablecoins/stablecoin_breakdown.sql
1. Adding new columns to stablecoin data `breakdown`
2. The old date column will be removed after the backend data is updated
=> Stablecoin v2.5: 

macros/stablecoins/stablecoin_metrics_artemis.sql
Fixing syntax error: https://artemis.dagster.cloud/prod/runs/fc603d37-c0d0-4565-892c-c2b8777ebbba?logFileKey=nmwynlaj&selection=%22run_dbt_d2c55%22&logs=query%3A%22run_dbt_d2c55%22
=> Stablecoins: quickfix

macros/stablecoins/stablecoin_balances.sql
Previously the model was getting the `stablecoin_supply` when executing an incremental run. The issue with this is the model expects the native supply not the stablecoin supply in usd. To fix this I select the correct column now and tested it with celo.
=> Stablecoins: Fix Balances Bug

models/dimensions/apps/dim_apps_silver.sql, models/staging/sei/fact_sei_transactions.sql
Made it so now None will delete tags in our tagging system. Also made sure Sei data isn't incomplete during midnights.
=> Updated Tagging + Fix Sei Transactions

macros/lending/aave_deposits_borrows_lender_revenue.sql
=> Updating AAVE with APY

models/projects/lido/core/ez_lido_metrics.sql, models/projects/lido/core/ez_lido_metrics_by_chain.sql, models/projects/lido/core/ez_lido_metrics_by_token.sql
=> adding lido earnings and total expenses

models/staging/zksync/__zksync__sources.yml, models/staging/zksync/fact_zksync_daa_txns_gas_gas_usd.sql
deprecating zksync from zettablocks and moving it over to dune
=> updating zksync to be on dune data

models/staging/zksync/fact_zksync_daa_txns_gas_gas_usd.sql
=> Quickfix: Adding chain to zksync query

models/projects/ton/raw/ez_ton_stablecoin_transfers.sql, models/staging/ton/fact_ton_stablecoin_transfers.sql
Filtering out un verified accounts and transfers in our ez ton stablecoin transfers to help fix ton balances.
=> Filtered out un verified stablecoin transfers and accounts

models/projects/jupiter/ez_jupiter_metrics_by_chain.sql, models/projects/jupiter/fact_jupiter_perps_silver.sql
Added txn count support for Jupiter Perps. Added ez_metrics_by_chain.
=> adding jupiter perps txns + ez metrics by chain

models/projects/ton/raw/ez_ton_stablecoin_transfers.sql
=> Quick Fix for ton stablecoin

models/projects/wormhole/core/ez_wormhole_metrics.sql, models/staging/wormhole/fact_wormhole_txns.sql
Added Wormhole EZ Metrics table and daily txns count.
Latest successful test run:
=> Wormhole: EZ metrics + Txns

models/staging/defillama/fact_defillama_protocol_fees.sql, models/staging/defillama/fact_defillama_protocol_revenue.sql
=> [911 Mitigation] Don't select rows that have null defillamaIds

models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_symbol.sql
Creating models for the stablecoin tiles that summarize the last 30 days of activity across chains and symbols.
=> [Stablecoin V3] Adding models for stablecoin tiles

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown.sql
Add unique id to `agg_daily_stablecoin_breakdown`
=> Stablecoin V2: adding unique id

models/projects/flare/core/ez_flare_metrics.sql, models/staging/flare/__flare__sources.yml, models/staging/flare/fact_flare_dau.sql, models/staging/flare/fact_flare_fees.sql, models/staging/flare/fact_flare_fees_native.sql, models/staging/flare/fact_flare_txns.sql
Flare fundamental metrics models including fees, daus, txns. 
Flare daily job runs successfully:
=> flare fundamentals models

models/projects/chainlink/prod_core/ez_chainlink_metrics.sql, models/projects/chainlink/prod_raw/__chainlink__sources.yml, models/projects/chainlink/prod_raw/fact_chainlink_daily_txns.sql, models/projects/chainlink/prod_raw/fact_chainlink_dau.sql
Adding DAUs and Txn counts for Chainlink
Relevant assets materialize nicely. Full chainlink job takes ~2.5 hrs so only materialized relevant assets.
=> Alw chainlink dau txns

dbt_scripts/create_complete_queries.sh, models/_complete_asset_models/aave/ez_aave_metrics__complete__.sql, models/_complete_asset_models/aave/ez_aave_metrics_by_chain__complete__.sql, models/_complete_asset_models/aave/ez_aave_metrics_by_token__complete__.sql, models/_complete_asset_models/maker/ez_maker_metrics__complete__.sql, models/_complete_asset_models/maker/ez_maker_metrics_by_chain__complete__.sql, models/_complete_asset_models/maker/ez_maker_metrics_by_token__complete__.sql, udfs/hex_to_utf8.sql
1. Adding complete queries for maker and aave
2. Adding UDF for Hex to string
=> Adding complete queries and udf

models/projects/rocketpool/core/ez_rocketpool_metrics_by_chain.sql
Ensuring all metrics are available downstream.
=> rocketpool quickfix

models/projects/stacks/core/ez_stacks_metrics.sql, models/projects/ton/core/ez_ton_metrics.sql, models/staging/stacks/fact_stacks_rolling_active_addresses.sql, models/staging/ton/fact_ton_rolling_active_addresses.sql
=> Added Stacks and Ton

macros/rolling_active_addresses.sql, models/projects/linea/core/ez_linea_metrics.sql, models/staging/linea/fact_linea_rolling_active_addresses.sql
=> adding mau wau for linea

macros/rolling_active_addresses.sql, models/projects/scroll/core/ez_scroll_metrics.sql, models/staging/scroll/fact_scroll_rolling_active_addresses.sql
Adding Scroll MAU and WAU numbers
=> adding scroll mau wau

macros/rolling_active_addresses.sql, models/projects/aptos/core/ez_aptos_metrics.sql, models/staging/aptos/fact_aptos_rolling_active_addresses.sql
Adding mau and wau metrics for aptos
=> adding aptos wau mau

macros/rolling_active_addresses.sql, models/projects/starknet/core/ez_starknet_metrics.sql, models/staging/starknet/fact_starknet_rolling_active_addresses.sql
=> adding starknet mau wau

models/projects/raydium/core/ez_raydium_metrics.sql
=> Fixed Raydium Incremental Bugs

models/projects/raydium/core/ez_raydium_metrics.sql, models/staging/sei/fact_sei_evm_transactions.sql
=> Fix raydium and sei

models/projects/raydium/core/ez_raydium_metrics.sql, models/staging/sei/fact_sei_wasm_transactions.sql
=> Fixed Raydium and wasm sei

models/projects/raydium/core/ez_raydium_metrics.sql
=> Raydium Trading volume filtered

models/projects/injective/core/ez_injective_metrics.sql
=> Add wau + mau to ez_injective_metrics in core schema

macros/rolling_active_addresses.sql, models/projects/sei/core/ez_sei_metrics.sql, models/staging/sei/fact_sei_evm_rolling_active_addresses.sql, models/staging/sei/fact_sei_wasm_rolling_active_addresses.sql
=> sei rolling actives ART-3703

models/staging/ton/dim_ton_open_league_dates.sql, models/staging/ton/fact_ton_app_open_league.sql
=> Updated Ton apps open league

macros/p2p/p2p_token_transfers.sql
Fixing Schema change from Flipside
=> C911: Fixing near token token transfers

macros/p2p/p2p_native_transfers.sql
1. updating Near P2P Native transfers after flipside changes schema
=> C911: updating near native transfers

models/projects/acala/core/ez_acala_metrics.sql, models/projects/axelar/core/ez_axelar_metrics.sql, models/projects/beam/core/ez_beam_metrics.sql, models/projects/blast/core/ez_blast_metrics.sql, models/projects/cardano/core/ez_cardano_metrics.sql, models/projects/cosmoshub/core/ez_cosmoshub_metrics.sql, models/projects/dexalot/core/ez_dexalot_metrics.sql, models/projects/dfk/core/ez_dfk_metrics.sql, models/projects/fantom/core/ez_fantom_metrics.sql, models/projects/fuse/core/ez_fuse_metrics.sql, models/projects/gnosis/core/ez_gnosis_metrics.sql, models/projects/internet_computer/core/ez_internet_computer_metrics.sql, models/projects/linea/core/ez_linea_metrics.sql, models/projects/multiversx/core/ez_multiversx_metrics.sql, models/projects/osmosis/core/ez_osmosis_metrics.sql, models/projects/polkadot/core/ez_polkadot_metrics.sql, models/projects/polygon_zk/core/ez_polygon_zk_metrics.sql, models/projects/scroll/core/ez_scroll_metrics.sql, models/projects/sei/core/ez_sei_metrics.sql, models/projects/stacks/core/ez_stacks_metrics.sql, models/projects/zksync/core/ez_zksync_metrics.sql, models/projects/zora/core/ez_zora_metrics.sql, models/staging/multiversx/__multiversx__sources.yml, models/staging/multiversx/fact_multiversx_gas_gas_usd.sql
1. Adding Support for Avg Txns Fees 
2. Adding Fees and Fees Native for multiversX
=> Customer 911: Adding support for avg txn fees for all chains

macros/stablecoins/stablecoin_breakdown.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_application.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_application_chain.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_application_symbol.sql
Adding Support for Application metric tables
=> Stablecoins: adding application models

models/common/ez_stablecoin_metrics.sql, models/projects/arbitrum/raw/ez_arbitrum_stablecoin_balances.sql, models/projects/avalanche/raw/ez_avalanche_stablecoin_balances.sql, models/projects/base/raw/ez_base_stablecoin_balances.sql, models/projects/bsc/raw/ez_bsc_stablecoin_balances.sql, models/projects/celo/raw/ez_celo_stablecoin_balances.sql, models/projects/ethereum/raw/ez_ethereum_stablecoin_balances.sql, models/projects/optimism/raw/ez_optimism_stablecoin_balances.sql, models/projects/polygon/raw/ez_polygon_stablecoin_balances.sql, models/projects/solana/raw/ez_solana_stablecoin_balances.sql, models/projects/ton/raw/ez_ton_stablecoin_balances.sql, models/projects/tron/raw/ez_tron_stablecoin_balances.sql
Adding support for ez_stablecoin_balances as required by **** (client)
=> Stablecoins: adding ez_stablecoin_balances to art_share

macros/coingecko/waterfall_stablecoin_prices.sql, macros/stablecoins/l30d_stablecoin_transfers.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_flows_breakdown_application.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_flows_breakdown_category.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_flows_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_flows_breakdown_symbol.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_transfers_l30d.sql
Creating stablecoin flows models for the frontend
=> Stablecoins: adding stablecoin flows data

macros/stablecoins/stablecoin_breakdown.sql, models/projects/ausd/core/ez_ausd_metrics.sql
Creating AUSD Ez_metrics table
=> AUSD: Ez Metrics

models/data_hubs/fact_retention_datahub.sql, models/projects/sei/core/ez_sei_metrics.sql, models/projects/sei/core/ez_sei_retention.sql, models/staging/sei/fact_sei_daa_txns_gas_gas_usd_revenue.sql, models/staging/sei/fact_sei_evm_fundamental_metrics_silver.sql
=> Added Sei retention and new/returning

models/staging/arbitrum_one_bridge/fact_arbitrum_one_bridge_flows.sql, models/staging/avalanche_bridge/fact_avalanche_bridge_flows.sql, models/staging/base_bridge/fact_base_bridge_flows.sql, models/staging/optimism_bridge/fact_optimism_bridge_flows.sql, models/staging/polygon_pos_bridge/fact_polygon_pos_bridge_flows.sql, models/staging/starknet_bridge/fact_starknet_bridge_flows.sql, models/staging/zksync_era_bridge/fact_zksync_era_bridge_flows.sql
Cleaning up bridge names in the backend
=> C911/Tech Debt: updating bridge names for native bridges

models/staging/outerlands/fact_outerlands_daily_asset_price_change.sql
Adding Outerlands index performance up to and including today, so it matches other benchmark assets in the chart.
=> outerlands index latest day pricing

models/projects/internet_computer/core/ez_internet_computer_metrics.sql, models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
=> Added Internet Computer Avg Txn Fee Update

.github/workflows/show_changed_models.yml
Show Changed Models is currently Borked see this PR where it ran even when it wasn't suppose to
https://github.com/Artemis-xyz/dbt/pull/539
=> C911: show changes models update

models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql
1. Adding support for EURC on base. 
To Do:
Need to wait for this to finish: https://artemis.dagster.cloud/prod/runs/14ffefd9-97fb-4dbd-b345-117c5b51d54e
=> Adding EURC to Base

models/projects/stride/core/ez_stride_metrics.sql, models/staging/stride/__stride__sources.yml
=> ez_stride_merics prod table

models/staging/synapse/fact_synapse_flows.sql
=> Added a filter for synapse because of their dq issue

models/projects/raydium/core/ez_raydium_metrics_by_pair.sql
=> Add Raydium buyback fee by token pair by day

models/projects/raydium/core/ez_raydium_metrics_by_pair.sql
=> fix unique key for ez_metrics_by_pair for Raydium

models/projects/raydium/core/ez_raydium_metrics.sql, models/projects/raydium/core/ez_raydium_metrics_by_pair.sql
=> replace buyback and trading fee and fee from the token_pair buyback method so it has more frequency

models/metrics/defillama/agg_defillama_protocol_fees_rev_tvl_dex_vol.sql
=> Fix defillama nulls

models/projects/raydium/core/ez_raydium_metrics.sql
=> Fixed Date Raydium

models/staging/scroll/fact_scroll_gas_gas_usd_revenue.sql
=> Fixed Median Fees

models/staging/osmosis/fact_osmosis_daa_txns.sql, models/staging/osmosis/fact_osmosis_gas_gas_usd.sql, models/staging/osmosis/fact_osmosis_gas_gas_usd_fees_revenue.sql, models/staging/osmosis/fact_osmosis_trading_fees.sql
=> Fixed Osmosis Fees

macros/create_ez_transactions.sql, models/projects/mantle/core/ez_mantle_metrics.sql, models/projects/mantle/core/ez_mantle_metrics_by_application.sql, models/projects/mantle/core/ez_mantle_metrics_by_category.sql, models/projects/mantle/core/ez_mantle_metrics_by_contract.sql, models/projects/mantle/core/ez_mantle_retention.sql, models/projects/mantle/raw/ez_mantle_transactions.sql, models/staging/mantle/fact_mantle_l1_data_cost.sql, models/staging/mantle/fact_mantle_rolling_active_addresses.sql, models/staging/mantle/fact_mantle_transactions.sql
Adding mantle BAM models and deprecating old mantle dbt models that transformed extracted data
=> Stablecoins: adding mantle bam models

models/projects/stellar/core/ez_stellar_metrics.sql, models/staging/stellar/__stellar__sources.yml, models/staging/stellar/fact_stellar_rwa_tvl.sql, models/staging/stellar/fact_stellar_stablecoin_tvl.sql
=> Add Stellar staging models

models/projects/stellar/core/ez_stellar_metrics.sql
=> Rename fees_usd -> fees

macros/wallets/distinct_eoa_addresses.sql
=> C911: fixing tron

macros/stablecoins/stablecoin_metrics.sql, models/dimensions/wallet/dim_solana_eoa_addresses.sql
1. Adding Ton premint addresses to ez_stablecoin_metrics_by_address
2. Fixing solana EOA addresses
=> C911: Fixing Ton and Solana Stablecoin pipeline

models/projects/solana/raw/ez_solana_token_account_mapping.sql
1. Adding a token account to owner mapping for solana
=> Solana: adding token account mapping

models/data_hubs/fact_daily_bam_datahub.sql
=> Added Fix for bam datahub

models/data_hubs/fact_daily_bam_datahub.sql
=> Fix Bam Datahub

models/staging/metaplex/fact_metaplex_transaction_counts.sql
- Fix transactions incremental model
- Clean up code to remove pivot
=> fix incremental and clean up code

models/staging/polygon_zk/fact_polygon_zk_daa_txns_gas_usd.sql
Zettablocks is having pricing issues, because of this we now do pricing in snowflake with coingecko
=> C911: Polygon ZK

models/projects/metaplex/core/ez_metaplex_metrics.sql, models/staging/metaplex/fact_metaplex_active_wallets.sql
Three quick metaplex fixes
- one table was missing incremental logic
- ez table referencing wrong column in upstream table
- added a date spine to ez table to ensure all dates are present
=> mplx daw add incremental, fix ez metric reference

macros/stablecoins/stablecoin_balances.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_bridge_addresses.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
1. Adding support of USDS
2. Ran all the tables up to the ez metric tables for both solana and ethereum
=> Stablecoins: USDS

models/projects/ethena/ez_ethena_metrics.sql
Title. Related to: https://github.com/Artemis-xyz/gokustats-back-end/pull/2722
=> add tvl to ena ez table

models/metrics/stablecoins/breakdowns/_test_agg_daily_stablecoin_breakdown_silver.yml
Adding back stablecoin not null test
=> Stablecoins: adding back not null tests

models/projects/raydium/core/ez_raydium_metrics.sql, models/staging/raydium/fact_raydium_token_prices.sql, models/staging/raydium/fact_raydium_trades.sql, models/staging/raydium/fact_raydium_trading_volumes.sql, models/staging/raydium/fact_solana_dex_token_prices.sql
=> Added Better Filtering for Raydium Dex Volumes

models/staging/ton/fact_ton_fundamental_metrics.sql
Ton Success Flag is borked, this fixes it
=> C911: fixing ton success flag

macros/decode/token_transfer_events.sql, models/staging/mantle/fact_mantle_transactions.sql
=> Stablecoins: adding updatine timezone for mantle

models/projects/sei/core/ez_sei_metrics.sql, models/staging/sei/fact_sei_rolling_active_addresses.sql, models/staging/sei/fact_sei_wasm_transactions.sql
=> Fix sei dau count

models/projects/metaplex/core/ez_metaplex_metrics.sql, models/staging/metaplex/fact_metaplex_buybacks.sql
=> Fix Metaplex Buybacks

models/projects/stride/core/ez_stride_metrics.sql
Add Stride TVL:
Looks good in the front end:
=> add stride tvl

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_transfers_l30d.sql
Adding mantle to the final stablecoin models
=> Mantle: Adding to final Stablecoin Models

models/staging/ref_finance/core/ez_ref_finance_metrics.sql
=> Fix the date spine for ref finance

models/staging/rainbow_bridge/fact_rainbow_bridge_transfers.sql
Fixing rainbow bridge bridge volume
=> C911: fixing rainbow bridge

models/bam_models/all_chains/all_chains_gas_dau_txns_by_category.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_chain.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_contract.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_namespace.sql, models/staging/mantle/mantle_trending_daily.sql, models/staging/mantle/mantle_trending_weekly_monthly.sql, models/trending/bam_trending_data.sql
adding mantle to the bam datahub models
=> Mantle: adding mantle to bam datahub models

models/staging/ref_finance/core/ez_ref_finance_metrics.sql
=> Fix Ref Date Spine

models/staging/raydium/fact_solana_dex_token_prices.sql
=> Use Least ignore nulls instead of just least

macros/metrics/get_fundamental_data_for_chain.sql, models/projects/mantle/core/ez_mantle_metrics.sql
Fixing mantle new/returning users
=> C911: fixing mantle new and returning

models/staging/defillama/_defillama_sources.yml, models/staging/defillama/fact_defillama_yields.sql
=> Add DFL yields data

models/projects/across/raw/ez_across_bridge_transfers.sql, models/projects/arbitrum/raw/ez_arbitrum_bridge_transfers.sql, models/projects/avalanche/raw/ez_avalanche_bridge_transfers.sql, models/projects/base/raw/ez_base_bridge_transfers.sql, models/projects/cctp/raw/ez_cctp_bridge_transfers.sql, models/projects/optimism/raw/ez_optimism_bridge_transfers.sql, models/projects/polygon/raw/ez_polygon_bridge_transfers.sql, models/projects/rainbow_bridge/raw/ez_rainbow_bridge_transfers.sql, models/projects/starknet/raw/ez_starknet_bridge_transfers.sql, models/projects/synapse/raw/ez_synapse_bridge_transfers.sql, models/projects/wormhole/raw/ez_wormhole_bridge_transfers.sql, models/projects/zksync/raw/ez_zksync_bridge_transfers.sql
Add bridge transfers to art share for codex
=> ART SHARE: Bridge Transfers

macros/wallets/get_wallet_dex_trades.sql, macros/wallets/get_wallet_stablecoin_data.sql, models/projects/base/core/ez_address.sql, models/projects/base/core/ez_base_address.sql, models/projects/base/raw/ez_base_balances.sql, models/staging/base/wallets/dim_base_wallets_cex_funded.sql, models/staging/base/wallets/dim_base_wallets_dex_trade.sql, models/staging/base/wallets/dim_base_wallets_fundamental_metrics.sql, models/staging/base/wallets/dim_base_wallets_stablecoin_metrics.sql
=> Add base user data

macros/contracts/get_contract_deployments.sql, models/metrics/contracts/fact_arbitrum_contracts.sql, models/metrics/contracts/fact_base_contracts.sql, models/metrics/contracts/fact_ethereum_contracts.sql, models/metrics/contracts/fact_optimism_contracts.sql
=> Fixed Contract Deployment Counts

models/projects/drift/core/ez_drift_metrics.sql, models/staging/drift/fact_drift_amm_revenue.sql, models/staging/drift/fact_drift_daily_perp_data.sql
=> Added more Drift revenue + data

macros/coingecko/get_coingecko_price_with_latest.sql, models/projects/celo/raw/ez_celo_transactions.sql, models/staging/celo/fact_celo_token_transfers.sql, models/staging/coingecko/dim_coingecko_token_map.sql
1. Creating a mapping of coingecko id to chain and address
2. Adding USD columns from coingecko
=> Celo: Adding USD columns to token transfers

macros/metrics/get_ez_decoded_events.sql, models/projects/celo/raw/ez_celo_decoded_events.sql
=> Celo: fixing decoded events macro

models/projects/celo/raw/ez_celo_token_transfers.sql
=> Celo: adding ez transfers

models/projects/celo/raw/ez_celo_traces.sql, models/staging/celo/__celo__sources.yml, models/staging/celo/fact_celo_token_transfers.sql, models/staging/celo/fact_celo_traces.sql
1. Adding celo traces to celo pipeline
=> Celo: adding traces

models/staging/celo/fact_celo_traces.sql
=> Celo: updating traces

macros/p2p/p2p_native_transfers.sql, models/staging/celo/fact_celo_traces.sql
1. Typecasting celo traces
2. Fixing near p2p native transfers for duplicate rows
=> C911: Fixing Celo and Near

models/staging/celo/fact_celo_traces.sql
using better unique id for celo
=> Celo 911: updating celo traces

.github/workflows/compile.yml, .github/workflows/docs.yml, .github/workflows/show_changed_models.yml
=> Revert to ubuntu 22.04

models/staging/apex/__apex__sources.yml, models/staging/apex/fact_apex_trading_volume.sql
=> Add ApeX Omni

macros/pendle/get_pendle_deposit_redeem_txns.sql, models/staging/pendle/fact_pendle_arbitrum_deposit_redeem_txns.sql, models/staging/pendle/fact_pendle_ethereum_deposit_redeem_txns.sql
Added a unique id to avoid any duplicates due to incremental runs.
=> pendle tvl data hygiene

requirements.in, requirements.txt
- Addressing Dependabot PR https://github.com/Artemis-xyz/dbt/pull/702
=> Update jinja to 3.1.5

models/metrics/stablecoins/contracts/fact_mantle_stablecoin_contracts.sql
=> Adding USDY metadata on Mantle

models/metrics/stablecoins/contracts/fact_mantle_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
=> Usdy asset

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Adding USDO on Ethereum

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Usdo asset

macros/stablecoins/stablecoin_metrics.sql, macros/wallets/distinct_eoa_addresses.sql, models/dimensions/wallet/dim_sui_eoa_addresses.sql, models/metrics/stablecoins/contracts/fact_sui_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_sui_stablecoin_premint_addresses.sql, models/projects/sui/core/ez_sui_stablecoin_metrics_by_address.sql, models/staging/sui/__sui__sources.yml, models/staging/sui/fact_sui_address_balances_by_token.sql, models/staging/sui/fact_sui_p2p_stablecoin_transfers.sql, models/staging/sui/fact_sui_stablecoin_balances.sql, models/staging/sui/fact_sui_stablecoin_metrics_all.sql, models/staging/sui/fact_sui_stablecoin_metrics_artemis.sql, models/staging/sui/fact_sui_stablecoin_metrics_p2p.sql, models/staging/sui/fact_sui_stablecoin_transfers.sql, models/staging/sui/fact_sui_token_transfers.sql
1. adding all the sui stablecoin models up to ez_metrics
=> Stablecoins: adding sui stablecoin models

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_transfers_l30d.sql
1. Adding sui to the agg stablecoin models
=> Stablecoins: adding sui to stablecoin models

macros/across/across_v2_decode_filled_relay.sql, macros/across/across_v2_decode_funds_deposited.sql, macros/across/across_v3_decode_filled_relay.sql, macros/across/across_v3_decode_funds_deposited.sql, models/dimensions/dim_chain_ids.sql, models/staging/across/fact_across_v2_complete_transfers.sql, models/staging/across/fact_across_v2_filledrelay.sql, models/staging/across/fact_across_v2_fundsdeposited.sql, models/staging/across/fact_across_v2_transfers.sql, models/staging/across/fact_across_v3_complete_transfers.sql, models/staging/across/fact_across_v3_filledrelay.sql, models/staging/across/fact_across_v3_fundsdeposited.sql, models/staging/across/fact_across_v3_transfers.sql
=> Updated across flows

models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql
=> Adding usds on BASE

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
Adding USDX on ETH, ARB and BSC
=> Usdx assets

models/projects/base/raw/ez_base_transfers.sql, models/projects/fdusd/core/ez_fdusd_metrics.sql
1. Cleaning up base transfers
2. Adding FDUSD
=> FDUSD and Base Transfers

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Adding USR on ETH

models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
Adding USD* on SOL **NOTE: COINGECKO API CURRENTLY A PLACEHOLDER UNTIL FIXED**
=> Adding USD* on SOL

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
Adding TUSD on ETH, more chains to come :)
=> Adding TUSD on ETH

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_tron_stablecoin_contracts.sql
=> Tusd asset

macros/bananagun/get_bananagun_contracts.sql, macros/bananagun/get_bananagun_fees.sql, macros/bananagun/get_bananagun_metrics.sql, macros/bananagun/get_bananagun_trades.sql, models/projects/bananagun/core/ez_bananagun_metrics.sql, models/projects/bananagun/core/ez_bananagun_metrics_by_chain.sql, models/staging/bananagun/dim_bananagun_base_contracts.sql, models/staging/bananagun/dim_bananagun_blast_contracts.sql, models/staging/bananagun/dim_bananagun_ethereum_contracts.sql, models/staging/bananagun/fact_bananagun_all_metrics.sql, models/staging/bananagun/fact_bananagun_base_fees.sql, models/staging/bananagun/fact_bananagun_base_metrics.sql, models/staging/bananagun/fact_bananagun_base_trades.sql, models/staging/bananagun/fact_bananagun_blast_fees.sql, models/staging/bananagun/fact_bananagun_blast_metrics.sql, models/staging/bananagun/fact_bananagun_blast_trades.sql, models/staging/bananagun/fact_bananagun_coin_metrics.sql, models/staging/bananagun/fact_bananagun_ethereum_fees.sql, models/staging/bananagun/fact_bananagun_ethereum_metrics.sql, models/staging/bananagun/fact_bananagun_ethereum_trades.sql, models/staging/bananagun/fact_bananagun_solana_fees.sql, models/staging/bananagun/fact_bananagun_solana_metrics.sql, models/staging/bananagun/fact_bananagun_solana_trades.sql
current prgress friday 12/20, need to fix token specific stats, bot stats (txs, fees) work correctly
=> test pr don merge

models/projects/usdy/core/ez_usdy_metrics.sql
=> Adding project page for USDY

requirements.in, requirements.txt
=> add snowflake-connector-python[secure-local-storage] directly to requirements

models/projects/across/raw/ez_across_transfers.sql, models/staging/across/fact_across_complete_transfers.sql
=> Clean Ez Across Transfer Tables

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Frax asset

models/projects/raydium/core/ez_raydium_metrics.sql
- Added Raydium TVL to EZ metrics table via DL
- Forward fill missing data, and deduplicate dates
=> raydium tvl via defillama

models/projects/liquity/core/ez_liquity_metrics.sql, models/projects/liquity/core/ez_liquity_metrics_by_chain.sql, models/projects/liquity/core/ez_liquity_metrics_by_token.sql, models/staging/maple/fact_maple_onchain_revenue.sql
- Fix aggregation in tokenholder count
- Also renamed table aliases
=> fix aliases and aggregation

macros/stablecoins/stablecoin_metrics_artemis.sql, models/projects/base/raw/ez_base_transfers.sql
1. Fixing the base transfers incremental run 
2. Fixing the artemis stablecoin metrics model
=> C911: updating stablecoin model and base transfers

models/projects/usd_star/core/ez_usd_star_metrics.sql, models/projects/usdx/core/ez_usdx_metrics.sql
Adding USD* and USDX `ez_<token>_metrics` table for project pages
=> Adding USD* and USDX project pages

models/trending/bam_trending_data.sql
=> Fix mantle trending

macros/metrics/get_defillama_protocol_tvl.sql, models/projects/osmosis/core/ez_osmosis_metrics.sql, models/projects/ref_finance/fact_ref_finance_fees_revs_tvl.sql
Fixed some forward fill logic in DefiLlama related queries.
Tested fixes for Osmosis, Ref Finance, Cellana, DeepBook, and Cetus.
=> fix missing dates

models/projects/arbitrum/raw/ez_arbitrum_address_balances_by_token.sql, models/projects/avalanche/raw/ez_avalache_address_balances_by_token.sql, models/projects/base/raw/ez_base_address_balances_by_token.sql, models/projects/blast/raw/ez_blast_address_balances_by_token.sql, models/projects/bsc/raw/ez_bsc_address_balances_by_token.sql, models/projects/celo/raw/ez_celo_address_balances_by_token.sql, models/projects/ethereum/raw/ez_ethereum_address_balances_by_token.sql, models/projects/mantle/raw/ez_mantle_address_balances_by_token.sql, models/projects/optimism/raw/ez_optimism_address_balances_by_token.sql, models/projects/polygon/raw/ez_polygon_address_balances_by_token.sql, models/projects/solana/raw/ez_solana_address_balances_by_token.sql, models/projects/sui/raw/ez_sui_address_balances_by_token.sql, models/projects/ton/core/ez_ton_address_balances_by_token.sql, models/projects/tron/raw/ez_tron_address_balances_by_token.sql
Added address balances by token to `projects` folders.
=> adding ez balances by token to projects

macros/across/across_v2_decode_filled_relay.sql, macros/across/across_v2_decode_funds_deposited.sql, macros/across/across_v3_decode_filled_relay.sql, macros/across/across_v3_decode_funds_deposited.sql, models/staging/across/__across__sources.yml, models/staging/across/fact_across_v2_complete_transfers.sql, models/staging/across/fact_across_v2_filledrelay.sql, models/staging/across/fact_across_v2_fundsdeposited.sql, models/staging/across/fact_across_v3_filledrelay.sql, models/staging/across/fact_across_v3_fundsdeposited.sql
=> Added Zksync Bridge datasets

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
Adding RLUSD on ETH.
Data seems to make sense.
=> Adding RLUSD on ETH

macros/create_ez_transactions.sql, macros/metrics/get_fundamental_data_for_chain_by_application.sql, macros/metrics/get_fundamental_data_for_chain_by_category_v2.sql, macros/metrics/get_fundamental_data_for_chain_by_contract.sql, macros/metrics/get_fundamental_data_for_chain_by_subcategory.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_application.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_category_v2.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_contract_v2.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_subcategory.sql, models/data_hubs/fact_daily_bam_datahub_v2.sql, models/dimensions/__dimension__sources.yml, models/dimensions/dim_app_datahub.sql, models/dimensions/dim_category_datahub.sql, models/dimensions/dim_chain_datahub.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_application_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_category_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_contract_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_subcategory.sql, models/projects/arbitrum/raw/ez_arbitrum_transactions_v2.sql, models/staging/arbitrum/fact_arbitrum_transactions_v2.sql
This creates a parallel arbitrum downstream pipeline for the new labeling pipeline. It also contains revamped all_chains_... dbt models as well as new datahub models.
Tested end to end!
=> Add arbitrum downstream labeling changes

macros/across/across_v3_decode_filled_relay.sql, macros/across/across_v3_decode_funds_deposited.sql, models/staging/across/__across__sources.yml, models/staging/across/fact_across_v3_filledrelay.sql, models/staging/across/fact_across_v3_fundsdeposited.sql
=> Across Decoded Data

models/projects/frax_usd/core/ez_frax_usd_metrics.sql, models/projects/susd/core/ez_susd_metrics.sql, models/projects/tusd/core/ez_tusd_metrics.sql, models/projects/usr/core/ez_usr_metrics.sql
Adding `ez_<token>_metrics` for each assets added for the stablecoin pages.
=> Adding new project pages for frax, susd, usr, tusd

models/projects/hivemapper/core/ez_hivemapper_metrics.sql, models/projects/hivemapper/core/ez_hivemapper_metrics_by_chain.sql
=> fix col name for adapter

models/projects/arbitrum/core/ez_arbitrum_metrics_by_application_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_category_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_contract_v2.sql, models/projects/arbitrum/core/ez_arbitrum_metrics_by_subcategory.sql, models/projects/arbitrum/raw/ez_arbitrum_transactions_v2.sql
Some arbitrum daily dbt models weren't running. Specified the wrong snowflake warehouse.
Ran dbt locally
=> Fix Snowflake Warehouses for Arbitrum

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql
Added and tested them on snowflake, data is accurate enough.
=> Adding AUSD on Pol, GHO, DEUSD, USDa

profiles.yml
=> Switch Default Target Name and Query Tag

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_optimism_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql
=> Adding DOLA stablecoins

models/projects/astar/core/ez_astar_metrics.sql, models/projects/bifrost/core/ez_bifrost_metrics.sql, models/projects/centrifuge/core/ez_centrifuge_metrics.sql, models/projects/hydration/core/ez_hydration_metrics.sql, models/projects/moonbeam/core/ez_moonbeam_metrics.sql, models/projects/mythos/core/ez_mythos_metrics.sql, models/projects/neuroweb/core/ez_neuroweb_metrics.sql
astar, bifrost, centrifuge, hydration, moonbeam, mythos, neuroweb columns renamed and added the backend as well
=> changed the column names for the 7 chains

models/staging/stargate/dim_stargate_v2_arbitrum_assets.sql, models/staging/stargate/dim_stargate_v2_avalanche_assets.sql, models/staging/stargate/dim_stargate_v2_base_assets.sql, models/staging/stargate/dim_stargate_v2_bsc_assets.sql, models/staging/stargate/dim_stargate_v2_ethereum_assets.sql, models/staging/stargate/dim_stargate_v2_mantle_assets.sql, models/staging/stargate/dim_stargate_v2_optimism_assets.sql, models/staging/stargate/dim_stargate_v2_polygon_assets.sql, models/staging/stargate/fact_stargate_v2_arbitrum_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_arbitrum_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_avalanche_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_avalanche_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_base_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_base_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_bsc_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_bsc_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_ethereum_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_ethereum_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_optimism_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_optimism_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_polygon_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_polygon_event_OFTSent.sql
=> Stargate: making tables incremental

models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql
=> Adding USDF

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_optimism_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql
=> Adding USDz, USDtb and crvUSD

macros/parity/parse_parity_parquets.sql, models/staging/acala/__acala__sources.yml, models/staging/acala/fact_acala_evm_transactions.sql, models/staging/acala/fact_acala_fundamental_metrics.sql, models/staging/astar/__astar_sources__.yml, models/staging/astar/fact_astar_evm_transactions.sql, models/staging/astar/fact_astar_fundamental_metrics.sql, models/staging/bifrost/__bifrost_sources__.yml, models/staging/bifrost/fact_bifrost_evm_transactions.sql, models/staging/bifrost/fact_bifrost_fundamental_metrics.sql, models/staging/centrifuge/__centrifuge_sources__.yml, models/staging/centrifuge/fact_centrifuge_evm_transactions.sql, models/staging/centrifuge/fact_centrifuge_fundamental_metrics.sql, models/staging/hydration/__hydration_sources__.yml, models/staging/hydration/fact_hydration_evm_transactions.sql, models/staging/hydration/fact_hydration_fundamental_metrics.sql, models/staging/neuroweb/__neuroweb_sources__.yml, models/staging/neuroweb/fact_neuroweb_evm_transactions.sql, models/staging/neuroweb/fact_neuroweb_fundamental_metrics.sql, models/staging/polkadot/__polkadot__sources.yml, models/staging/polkadot/fact_polkadot_burns.sql, models/staging/polkadot/fact_polkadot_fundamental_metrics.sql
=> add parity evm transactions

macros/decode/decode_events.sql, macros/upack/unpack_logs_json.sql, models/staging/celo/fact_celo_decoded_events.sql, models/staging/celo/fact_celo_events.sql
We changed the way we decode logs and need to update to use the V2 Decoder that @Sunny77D created
=> C911: Updating celo

models/staging/acala/fact_acala_fundamental_metrics.sql
=> Fix Acala Chain bug

macros/contracts/get_contract_deployments.sql, models/staging/sei/fact_sei_contracts.sql
=> Added Sei Weekly contracts

macros/bridge/stargate_OFTReceived.sql, macros/bridge/stargate_OFTSent.sql, macros/bridge/stargate_asset_map.sql, models/staging/berachain/__berachain__sources_.yml, models/staging/berachain/fact_berachain_decoded_events.sql, models/staging/berachain/fact_berachain_events.sql, models/staging/linea/fact_linea_decoded_events.sql, models/staging/linea/fact_linea_events.sql, models/staging/stargate/dim_stargate_v2_berachain_assets.sql, models/staging/stargate/dim_stargate_v2_mantle_assets.sql, models/staging/stargate/dim_stargate_v2_sei_assets.sql, models/staging/stargate/fact_stargate_v2_berachain_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_berachain_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_mantle_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_mantle_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_sei_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_sei_event_OFTSent.sql
1. indexing berachain, mantle, sei
=> Stargate: Index Berachain, mantle, sei

macros/chainalaysis/chainalaysis_traces.sql, macros/chainalaysis/chainanalysis_stablecoin_transfers.sql, models/projects/base/raw/ez_base_transfers.sql, models/staging/chainalysis/fact_celo_stablecoin_transfers_chainalysis.sql, models/staging/chainalysis/fact_celo_traces_chainalysis.sql, models/staging/chainalysis/fact_solana_stablecoin_transfers_chainalysis.sql, models/staging/chainalysis/fact_ton_stablecoin_transfers_chainalysis.sql
updating base ez transfers
updating schemas -> keccek256()[:8]
=> Sm update schema

models/staging/coingecko/fact_coingecko_token_realtime_data.sql
=> Update FDV in realtime model

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_optimism_stablecoin_contracts.sql
Adding LISUSD, USDD, FRXUSD, SUSD contracts
=> Add LISUSD, USDD, FRXUSD, SUSD

models/projects/sei/core/ez_sei_metrics.sql
=> Added Sei Contracts to ez metrics

models/metrics/stablecoins/contracts/fact_arbitrum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_optimism_stablecoin_contracts.sql
MIM for eth and arb was added while fixing the symbol for SUSD.
=> Fixing symbol for susd

models/staging/acala/fact_acala_fundamental_metrics.sql, models/staging/astar/fact_astar_fundamental_metrics.sql, models/staging/bifrost/fact_bifrost_fundamental_metrics.sql, models/staging/centrifuge/fact_centrifuge_fundamental_metrics.sql, models/staging/hydration/fact_hydration_fundamental_metrics.sql, models/staging/moonbeam/fact_moonbeam_fundamental_metrics.sql, models/staging/neuroweb/fact_neuroweb_fundamental_metrics.sql
=> Fix Parity Evm Bugs

macros/p2p/p2p_stablecoin_transfers.sql, macros/stablecoins/agg_chain_stablecoin_transfers.sql, models/metrics/stablecoins/contracts/fact_avalanche_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_base_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_tron_stablecoin_contracts.sql, models/staging/sui/fact_sui_stablecoin_transfers.sql
Adding MIM, USD3 cgUSD and USN and fix pipeline for TRON and SUI and SOLANA
=> Add MIM, USD3, cgUSD and fix some pipelines

models/dimensions/dim_app_datahub.sql
Modify dim app datahub back into including category + subcategory per application
Ran locally
=> Modify dim app datahub

models/staging/acala/fact_acala_fundamental_metrics.sql, models/staging/astar/fact_astar_fundamental_metrics.sql, models/staging/bifrost/fact_bifrost_fundamental_metrics.sql, models/staging/centrifuge/fact_centrifuge_fundamental_metrics.sql, models/staging/hydration/fact_hydration_fundamental_metrics.sql, models/staging/moonbeam/fact_moonbeam_fundamental_metrics.sql, models/staging/neuroweb/fact_neuroweb_fundamental_metrics.sql
=> Fixed EVM DAUs

models/projects/stargate/core/ez_stargate_metrics.sql
=> fixing stg

models/projects/usual/core/ez_usual_metrics.sql, models/staging/usual/fact_usd0pp_tvl.sql, models/staging/usual/fact_usual_burn_mint.sql, models/staging/usual/fact_usual_fees.sql
usual ez_metrics table materialized successfully 
fact_usd0pp_tvl materialized successfully
fact_usual_burn_mint materialized successfully
fact_usual_fees materialized successfully
=> USUAL fact and ez metrics table materialized successfully

models/dimensions/dim_app_datahub.sql, models/dimensions/labeling/dim_all_apps_silver.sql
In preparation for on-chain explorer, add metadata to applications table.
Tested locally
=> Add additional metadata info to artemis application securitymaster

macros/standard_8d737a18/standard_8d737a18_stablecoin_transfers.sql, macros/standard_8d737a18/standard_8d737a18_traces.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_celo_stablecoin_transfers_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_celo_traces_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_solana_stablecoin_transfers_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_ton_stablecoin_transfers_standard_8d737a18.sql, seeds/chain_agnostic_ids.csv
=> standard_8d737a18: updating tables

models/dimensions/dim_app_datahub.sql
Adding an earliest deployment timestamp column within dimappdatahub
Ran locally
=> Add earliest deployment column within dimappdatahub

models/staging/synapse/fact_synapse_flows.sql
Filter out huge spiking transactions
=> Make synapse dq filter more strict

models/staging/across/fact_across_bridge_daa.sql
=> Fixed DAAs for across

macros/address_balances/forward_filled_address_balances.sql, models/dimensions/labeling/__labeling__sources.yml, models/dimensions/labeling/dim_all_addresses_labeled_gold.sql, models/dimensions/labeling/dim_all_addresses_labeled_silver.sql, models/dimensions/labeling/uploaded_labeled_addresses.sql, models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql, models/staging/coingecko/dim_coingecko_token_map.sql, models/staging/stargate/fact_stargate_v2_arbitrum_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_avalanche_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_base_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_bsc_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_ethereum_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_event_OFTReceived.sql, models/staging/stargate/fact_stargate_v2_event_OFTSent.sql, models/staging/stargate/fact_stargate_v2_mantle_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_optimism_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_polygon_treasury_balance.sql, seeds/chain_agnostic_ids.csv, seeds/native_tokens_seed.csv
1. updating stargate
2. updating labels
To do:
1. Run the labels verification job to get the mantle labelled addresses
=> Updating labels and stargate

macros/bridge/stargate_OFTReceived.sql, macros/bridge/stargate_OFTSent.sql
1. Updating stargate event macro
=> Stargate: updating stargate event macro

macros/goldsky/get_goldsky_chain_fundamental_metrics.sql, models/projects/across/raw/ez_across_transfers.sql, models/projects/ink/core/ez_ink_metrics.sql, models/projects/soneium/core/ez_soneium_metrics.sql, models/staging/ink/fact_ink_fundamental_metrics.sql, models/staging/soneium/fact_soneium_fundamental_metrics.sql, models/staging/stargate/fact_stargate_v2_transfers.sql
=> Added Ink And Soneium to chains

models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Precompute all stats in onchainexplorer datahub 
Ran locally
=> Modify onchainexplorer datahub

macros/stablecoins/stablecoin_metrics.sql
PR to include a specific wallet that we flagged out
=> Fixing FDUSD

macros/standard_8d737a18/standard_8d737a18_stablecoin_transfers.sql, macros/standard_8d737a18/standard_8d737a18_traces.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql, models/staging/stargate/fact_stargate_flows.sql, models/staging/stargate/fact_stargate_v2_transfers.sql
Need to full refresh tether data
=> C911: fixing tether and stargate

models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql
Updating stargate metrics tables
=> C911: fixing stargate ex metrics

models/projects/across/raw/ez_across_transfers.sql
=> Fixed Fees for stargate

models/dimensions/dim_app_datahub.sql
Added deployed on column in DimAppDatahub so that the user searches on application metadata by chain in onchain explorer.
Ran locally
=> Add deployed on column in dimappdatahub

macros/metrics/get_eth_l2_cost.sql, models/projects/unichain/core/ez_unichain_metrics.sql, models/projects/worldchain/core/ez_worldchain_metrics.sql, models/staging/unichain/fact_unichain_fundamental_metrics.sql, models/staging/worldchain/fact_worldchain_fundamental_metrics.sql
=> Added l2 revenue

macros/stablecoins/stablecoin_metrics.sql, models/dimensions/labeling/uploaded_labeled_addresses.sql, models/metrics/stablecoins/contracts/fact_avalanche_stablecoin_premint_addresses.sql, models/metrics/stablecoins/contracts/fact_tron_stablecoin_bridge_addresses.sql
=> C911: adding tether stablecoin addresses

models/dimensions/labeling/dim_legacy_sigma_tagged_contracts.sql
Match on lowercase addresses in sigma
Ran locally
=> Match on lowercase addresses in sigma

macros/standard_8d737a18/standard_8d737a18_stablecoin_transfers.sql, macros/standard_8d737a18/standard_8d737a18_traces.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_celo_stablecoin_transfers_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_celo_traces_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_solana_stablecoin_transfers_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_ton_stablecoin_transfers_standard_8d737a18.sql, seeds/chain_agnostic_ids.csv
1. Updating standard to follow correct lowercase and removal of characters
=> Customer Request: updating standard and chain agnositc ids

macros/metrics/get_eth_l2_cost.sql
=> Quick Fix for unichain and worldchain bugs

macros/standard_8d737a18/standard_8d737a18_stablecoin_transfers.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql
Fixing the standard models sql comp error
=> C911: updating standard files

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Adding USDG, USDA, FXUSD

macros/bridge/stargate_OFTReceived.sql, macros/bridge/stargate_OFTSent.sql
1. Updating stargate Pricing data to use unified pricing. Long term we need a unified pricing table but this will work for now
=> C911: updating stargate pricing data

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Adding EURT

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> fixing aeur

models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
Adding the dbt for AEUR and lusd
=> Adding LUSD and AEUR

models/projects/base/raw/ez_base_transfers.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql, models/staging/standard_8d737a18/dexs_quote_assets.sql
1. Updating base tranfers
2. Updating standards code
=> Updating standard and base transfers

macros/address_balances/forward_filled_address_balances.sql, macros/bridge/stargate_asset_map.sql, models/dimensions/current_balances/dim_sei_current_balances.sql, models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql, models/staging/sei/__sei__sources.yml, models/staging/sei/fact_sei_address_balances_by_token.sql, models/staging/sei/fact_sei_address_credit_by_token.sql, models/staging/sei/fact_sei_address_debit_by_token.sql, models/staging/stargate/dim_stargate_v2_sei_assets.sql, models/staging/stargate/fact_stargate_v2_arbitrum_tvl.sql, models/staging/stargate/fact_stargate_v2_avalanche_tvl.sql, models/staging/stargate/fact_stargate_v2_base_tvl.sql, models/staging/stargate/fact_stargate_v2_bsc_tvl.sql, models/staging/stargate/fact_stargate_v2_ethereum_tvl.sql, models/staging/stargate/fact_stargate_v2_mantle_tvl.sql, models/staging/stargate/fact_stargate_v2_optimism_tvl.sql, models/staging/stargate/fact_stargate_v2_polygon_tvl.sql, models/staging/stargate/fact_stargate_v2_sei_tvl.sql
=> Stargate: adding stargate tvl

models/projects/marinade/core/ez_marinade_metrics.sql, models/staging/marinade/fact_marinade_circulating_supply.sql, models/staging/marinade/fact_marinade_dau_txns.sql, models/staging/marinade/fact_marinade_fees.sql, models/staging/marinade/fact_marinade_tvl.sql, models/staging/marinade/fact_marinade_v1_fees.sql
Marinade ez_metrics table materialized successfully
=> Marinade fees, dau, txns, circulating supply, tvl

models/staging/metaplex/fact_metaplex_active_wallets.sql, models/staging/metaplex/fact_metaplex_new_holders.sql, models/staging/metaplex/fact_metaplex_transaction_counts.sql, models/staging/metaplex/fact_metaplex_unique_signers.sql
=> Fixed Datasets of metaplex to not include bubblegum (per the protocol request)

models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
=> Adding Contract Type label to Labeled addresses

models/staging/across/fact_across_v3_complete_transfers.sql
=> Fix DML Action

models/projects/equities/ez_sec_gov_10q.sql, models/staging/equities/__equities__source.yml, models/staging/equities/fact_sec_gov_10q_pivot.sql, seeds/coinbase_q4_metrics.csv
Add coinbase Q4 metrics in a seed file
Ran locally
=> Add coinbase q4 metrics

macros/decode/decode_goldsky_events.sql
=> Standardization: updating events

models/dimensions/labeling/dim_all_addresses_silver.sql
Remove dupes from manually uploaded labels within dim_all_addresses_silver
Ran locally
=> Remove dupes from manually uploaded labels

models/projects/arbitrum/core/ez_arbitrum_circulating_supply_metrics.sql, models/projects/arbitrum/raw/supply_metrics/fact_arbitrum_airdrop_emissions.sql, models/projects/arbitrum/raw/supply_metrics/fact_arbitrum_all_supply_events.sql, models/projects/arbitrum/raw/supply_metrics/fact_arbitrum_dao_emissions.sql, models/projects/arbitrum/raw/supply_metrics/fact_arbitrum_foundation_unlocks.sql, models/projects/arbitrum/raw/supply_metrics/fact_arbitrum_insider_unlocks.sql, models/projects/optimism/core/ez_optimism_supply_metrics.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_airdrop_emissions.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_all_supply_events.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_base_grants_emissions.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_govgrants_emissions.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_insider_unlocks.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_private_sale_emissions.sql, models/projects/optimism/raw/supply_metrics/fact_optimism_retropgf_emissions.sql
Objective: Calculate ARB and OP token supply and provide this as an ez metrics table.
Pulled all data from official sources, and cited sources for all values.
=> arb and op supply

models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
Remove dupes from dim_all_addresses_labeled_silver
Ran locally
=> Remove dupes from labeled addresses table

macros/coingecko/get_coingecko_price_with_latest.sql, models/dimensions/dim_chain_ids.sql, models/projects/developer/__developer__sources.yml, models/projects/developer/raw/ez_github_repository_subecosystems.sql, models/staging/across/__across__sources.yml, models/staging/across/fact_across_flows.sql, models/staging/across/fact_across_transfers_with_price.sql, models/staging/coingecko/dim_coingecko_token_map.sql
=> Fix across pricing issues and add ez_subecosystems

models/projects/sonic/ez_sonic_metrics.sql, models/staging/sonic/fact_sonic_fundamental_metrics.sql, models/staging/sonic/fact_sonic_transactions.sql
Create simple ez metrics table for Sonic.
=> sonic ez metrics

models/staging/across/fact_across_v3_transfers.sql
=> Fixed Across Null data

models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_token.sql
1. adding missing columns and supporting by token breakdown
=> Stargate: Updating by token breakdown 

macros/decode/decode_events.sql, macros/dune/clean_dune_events.sql, macros/flipside/clean_flipside_events.sql, macros/standardization/decode_artemis_events.sql, models/staging/base/fact_base_decoded_events.sql, models/staging/ethereum/fact_ethereum_decoded_events.sql, models/staging/mantle/fact_mantle_decoded_events.sql
1. standardizing logs for flipside and dune
2. using in v3 decode function
To Do:
1. port over all goldsky logs to the new paradigm and decode function
=> Standardization: adding standardized logs

models/staging/across/fact_across_flows.sql, models/staging/wormhole/fact_wormhole_flows.sql
=> Remove null amount usd from flows

macros/stablecoins/agg_chain_stablecoin_transfers.sql, models/projects/base/raw/ez_base_transfers.sql
1. Fixing base transfers
2. Fixing celo stablecoin transfers
=> C911: update transfers

models/staging/jito/fact_jito_dau_txns_fees.sql
Confirmed rollout date with the team. 0.3% of fees that go to NCN participants is counted toward supply side fees.
=> edit jito fee schedule

models/metrics/bridges/agg_daily_bridge_flows_metrics.sql, models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql
=> Added Not Categorized

models/projects/mantle/core/ez_mantle_metrics.sql, models/projects/sui/core/ez_sui_metrics.sql
Added supportstablecoins for SUI and MANTLE.
=> C911: Add supportStablecoins for sui and mantle

models/projects/virtuals/core/ez_virtuals_metrics_by_chain.sql
=> ez_virtuals_metrics_by_chain for trading_volume metric

models/staging/b3/__b3__sources.yml, models/staging/mode/__mode__sources.yml
=> Add B3 and Mode Sources

models/staging/base/fact_base_token_transfers.sql, models/staging/ethereum/fact_ethereum_token_transfers.sql, models/staging/mantle/fact_mantle_token_transfers.sql
=> C911: Mantle, Base, Ethereum updating incremental key

macros/goldsky/get_goldsky_chain_fundamental_metrics.sql, models/projects/abstract/core/ez_abstract_metrics.sql, models/projects/bob/core/ez_bob_metrics.sql, models/projects/bridge_flows/core/ez_bridge_flows.sql, models/staging/abstract/fact_abstract_fundamental_metrics.sql, models/staging/abstract/fact_abstract_transactions.sql, models/staging/bob/fact_bob_fundamental_metrics.sql, models/staging/bob/fact_bob_transactions.sql
=> Added a new Bridge Flows DB + Abstract + BOB

models/projects/avalanche/core/ez_avalanche_metrics.sql
=> Rename ds to staking_data

models/projects/aeur/core/ez_aeur_metrics.sql, models/projects/angle_usd/core/ez_angle_usd_metrics.sql, models/projects/bold/core/ez_bold_metrics.sql, models/projects/cgusd/core/ez_cgusd_metrics.sql, models/projects/crvusd/core/ez_crvusd_metrics.sql, models/projects/deusd/core/ez_deusd_metrics.sql, models/projects/dola/core/ez_dola_metrics.sql, models/projects/eurt/core/ez_eurt_metrics.sql, models/projects/flexusd/core/ez_flexusd_metrics.sql, models/projects/frxusd/core/ez_frxusd_metrics.sql, models/projects/fxusd/core/ez_fxusd_metrics.sql, models/projects/gho/core/ez_gho_metrics.sql, models/projects/gusd/core/ez_gusd_metrics.sql, models/projects/lisusd/core/ez_lisusd_metrics.sql, models/projects/lusd/core/ez_lusd_metrics.sql, models/projects/mim/core/ez_mim_metrics.sql, models/projects/rlusd/core/ez_rlusd_metrics.sql, models/projects/s_usd/core/ez_s_usd_metrics.sql, models/projects/usd3/core/ez_usd3_metrics.sql, models/projects/usda/core/ez_usda_metrics.sql, models/projects/usdd/core/ez_usdd_metrics.sql, models/projects/usdf/core/ez_usdf_metrics.sql, models/projects/usdg/core/ez_usdg_metrics.sql, models/projects/usdtb/core/ez_usdtb_metrics.sql, models/projects/usdz/core/ez_usdz_metrics.sql, models/projects/usn/core/ez_usn_metrics.sql
Creating dbt model for all project pages.
=> Add all project pages dbt model

models/projects/bridge_flows/core/ez_bridge_flows.sql
=> Change the column referenced to be raw amounts.

macros/stablecoins/agg_chain_stablecoin_transfers.sql
Fixing mantle stablecoin transfers
=> C911: fixing raw date

macros/stablecoins/stablecoin_metrics.sql
1. forcing an incremental run for ez_tron_stablecoin_metrics_by_address
=> c911: Short term fix tron

macros/stablecoins/stablecoin_metrics.sql
1. Refixing tron stablecoin metrics
=> C911: updating tron stablecoin metrics

models/staging/across/fact_across_v3_complete_transfers.sql
=> Switch ordering

macros/standard_8d737a18/standard_8d737a18_stablecoin_balances.sql, models/staging/hyperliquid/fact_hyperliquid_fees.sql, models/staging/standard_8d737a18/fact_solana_stablecoin_balances_standard_8d737a18.sql
=> C911:  updating Standard and hype

models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Add check to see if data didn't get updated, and if it didn't, then keep the same data from T-1 on onchain explorer.
Ran locally
=> Modify onchainexplorer datahub for stale data

models/projects/wormhole/raw/ez_wormhole_bridge_transfers.sql, models/staging/wormhole/fact_wormhole_flows.sql
=> Added Wormhole Flows and Bridge Transfers

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_silver.sql
Forgot to remove the data i was testing with inside.
=> Remove testing data in the dbt model

macros/decode/decode_events.sql, models/staging/base/fact_base_native_token_transfers.sql, models/staging/celo/fact_celo_events.sql, models/staging/ethereum/fact_ethereum_native_token_transfers.sql
1. Updating native transfers
2. Fixing Celo token transfer
=> Standardization: update incremental standardization p3

macros/create_ez_transactions.sql, models/dimensions/labeling/chain_level_addresses/dim_sei_all_addresses.sql, models/projects/sei/raw/ez_sei_transactions_v2.sql, models/staging/mantle/fact_mantle_transactions_v2.sql, models/staging/sei/fact_sei_evm_transactions_v2.sql, models/staging/sei/fact_sei_transactions_v2.sql, models/staging/sei/fact_sei_wasm_transactions_v2.sql, models/staging/solana/fact_solana_30d_transactions_v2.sql, models/staging/tron/fact_tron_transactions_v2.sql
Make sei, tron, and mantle transaction tables incremental
Tested locally
=> Make remaining BAM chains incremental

models/projects/stargate/core/ez_stargate_metrics.sql
=> C911: fixing stg

dbt_scripts/generate_schema.py
- Only compile models for the relevant project instead of doing a full compile
- Deleted all compiled artifacts including `manifest.json`
- Timed 
Around 5x faster than current state
=> Speed up Standardization Script

models/projects/coindesk20/core/ez_coindesk20_metrics.sql, models/staging/coindesk20/__sources__.yml, models/staging/coindesk20/_test_fact_coindesk20_price.yml, models/staging/coindesk20/fact_coindesk20_price.sql, models/staging/wormhole/fact_wormhole_operations.sql
=> Added Coindesk 20 to DBT Models

.env.local.template
=> Set Default Role to PC_DBT_ROLE

models/dimensions/labeling/__labeling__sources.yml, models/dimensions/labeling/dim_all_addresses_labeled_silver.sql, models/dimensions/labeling/dim_all_addresses_silver.sql, models/dimensions/labeling/dim_manual_labeled_addresses.sql
Update bulk loading for labels from S3. Verification functions are removed, and uploaded_labeled_addresses has been deprecated.
Checked locally
=> Update bulk uploading for labels

macros/get_entity_historical_balance.sql, models/staging/orca/fact_orca_whirlpool_pubkeys.sql, models/staging/orca/fact_orca_whirlpool_tvl.sql
- Macro is now updated and supports Solana protocols better
- Added Orca Whirlpool TVL to test it out
- Note: only added Whirlpool TVL, not the TVL for the old Whirlpool program. We are waiting on hearing back from the Orca team on the program id for the old AMM so we can get the full history.
- Holding off on adding our TVL to the ez metrics table until the above is resolved.
-
=> updated macro to better support Solana

macros/coingecko/get_coingecko_price_with_latest.sql, models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql, models/projects/debridge/core/ez_debridge_metrics.sql, models/projects/debridge/core/ez_debridge_metrics_by_chain.sql, models/staging/coindesk20/__coindesk20__sources.yml, models/staging/coindesk20/__sources__.yml, models/staging/debridge/__debridge__sources.yml, models/staging/debridge/_test_fact_debridge_fundamental_metrics.yml, models/staging/debridge/fact_debridge_chain_id.sql, models/staging/debridge/fact_debridge_flows.sql, models/staging/debridge/fact_debridge_fundamental_metrics.sql, models/staging/debridge/fact_debridge_fundamental_metrics_by_chain.sql, models/staging/debridge/fact_debridge_transfers.sql, models/staging/debridge/fact_debridge_transfers_with_prices.sql
=> Add debridge Dbt models both for flows and project page

models/projects/bridge_flows/core/ez_bridge_flows.sql
=> Added Debridge to Ez Bridge Flows

models/staging/debridge/fact_debridge_fundamental_metrics.sql
=> Fix Debridge Volume

models/staging/debridge/fact_debridge_transfers.sql, models/staging/debridge/fact_debridge_transfers_with_prices.sql
=> Fixed contract mapping

macros/address_balances/forward_filled_balance_for_address.sql, macros/address_balances/forward_filled_token_balances.sql, macros/goldsky/clean_goldsky_events_v2.sql, models/pricing/fact_ethereum_lp_token_prices.sql, models/projects/stargate/core/ez_stargate_current_positions.sql, models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql, models/staging/pometry/__pometry__sources.yml, models/staging/pometry/dim_address_clusters_base.sql, models/staging/pometry/dim_address_features_base.sql, models/staging/stargate/__stargate__sources.yml, models/staging/stargate/fact_stargate_v2_arbitrum_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_avalanche_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_base_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_bsc_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_ethereum_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_mantle_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_optimism_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_polygon_treasury_balance.sql, seeds/manually_added_tokens_seed.csv
1. Update all Stg models for treasury and tvl
=> Stargate: update all stg models

models/dimensions/labeling/dim_manual_labeled_addresses.sql
Enable labels bulk upload for all chains
Ran dbt locally
=> Enable labels bulk upload for all chains

models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql, models/staging/stargate/fact_stargate_v2_bsc_treasury_balance.sql, models/staging/stargate/fact_stargate_v2_polygon_treasury_balance.sql
1. Fixing by chain and ez metric tables
=> Stargate: fixing stargate models

models/projects/story/core/ez_story_metrics.sql, models/staging/plume/fact_plume_fundamental_metrics.sql, models/staging/plume/fact_plume_transactions.sql, models/staging/story/fact_story_fundamental_metrics.sql, models/staging/story/fact_story_transactions.sql
=> Added plume + story

macros/dune/clean_dune_events.sql, models/staging/sui/fact_sui_stablecoin_transfers.sql
Mantle was stale, and SUI transfer volume is bad.
This should fix the data for both chains
=> C911: Fix mantle and SUI data

models/staging/hyperevm/__hyperevm__sources.yml
```
dbt ls --resource-type source -s source:artemis_dbt.PROD_LANDING.raw_hyperevm\*
```
=> Add HyperEVM sources

macros/address_balances/address_credits_dune.sql, macros/address_balances/address_debits_dune.sql, macros/bridge/stargate_OFTReceived.sql, macros/bridge/stargate_OFTSent.sql, macros/goldsky/clean_goldsky_events_v2.sql, models/projects/stargate/core/ez_stargate_metrics.sql, models/projects/stargate/core/ez_stargate_metrics_by_chain.sql, models/staging/berachain/fact_berachain_decoded_events.sql, models/staging/berachain/fact_berachain_token_transfers.sql, models/staging/stargate/dim_stargate_bsc_STGholders.sql, models/staging/stargate/dim_stargate_bsc_veSTGholders.sql, models/staging/stargate/fact_stargate_v2_berachain_hydra_assets.sql, models/staging/stargate/fact_stargate_v2_sei_hydra_assets.sql
1. Adding hydraChain metrics from Stargate
2. Fixing Mantle Balances
3. Adding berachain token transfers
=> Stagate and C911 (Stablecoins): updating stargate and mantle

macros/bridge/stargate_veSTGholders.sql, models/staging/pometry/dim_address_clusters_base.sql, models/staging/stargate/fact_stargate_top100veSTGholders.sql
Fixing percentage total supply stg
=> STG: updating stg and pometry

macros/bridge/stargate_veSTGholders.sql, models/staging/stargate/fact_stargate_top100veSTGholders.sql
- used the average fees to calculate how much fees each veSTG holder receive
=> veSTG fees

models/staging/stargate/fact_stargate_top100veSTGholders.sql
getting total fees calculating (1/6) of veSTG fees
- used number of days to calculate weighted scale across all the different addresses
=> accurately calculating 1/6 of total fees

macros/bridge/stargate_veSTGholders.sql, models/staging/stargate/dim_stargate_arbitrum_veSTGholders.sql, models/staging/stargate/dim_stargate_avalanche_veSTGholders.sql, models/staging/stargate/dim_stargate_bsc_veSTGholders.sql, models/staging/stargate/dim_stargate_ethereum_veSTGholders.sql, models/staging/stargate/dim_stargate_optimism_veSTGholders.sql, models/staging/stargate/dim_stargate_polygon_veSTGholders.sql, models/staging/stargate/fact_stargate_top100veSTGholders.sql
- remove the macro changes for average fees
- added the current stg balances
=> stargate macro clean up and stgBalances

models/staging/across/fact_across_uba_transfers.sql
=> Fix Across UBA Transfers

models/staging/stargate/fact_stargate_top100veSTGholders.sql
- multiplied by 100 for the percentage (to accurately reflect on the front end)
=> mutiplied by 100 for percentage

models/projects/aerodrome/core/ez_aerodrome_metrics.sql
Fix duplicate column name error.
=> aerodrome fix

macros/coingecko/waterfall_stablecoin_prices.sql
=> C911 pricing data

models/projects/kamino/ez_kamino_metrics.sql
Rename txn-> txns so it matches the schema required by the Outerlands index query.
=> txn -> txns

macros/coingecko/waterfall_stablecoin_prices.sql
Fix pricing issue, which spikes the supply wrongly.
=> C911 fix for FLEX-USD

models/staging/pendle/fact_pendle_tvl_by_token_and_chain.sql
1. removing negative values for pendle
=> C911: Fixing Pendle

models/bam_models/all_chains/all_chains_gas_dau_txns_by_contract_v2.sql, models/dimensions/dim_app_datahub.sql, models/dimensions/labeling/dim_all_addresses_labeled_silver.sql, models/dimensions/labeling/dim_all_addresses_silver.sql
Make non-EVM addresses case-sensitive for labels. 
Reran all models.
=> Make non-EVM addresses case-sensitive

models/data_hubs/fact_daily_bam_datahub_v2.sql, models/dimensions/dim_category_datahub.sql
Friendly names for categories were not correct. Updated the seed file, and also updated category friendly names within BAM datahub V2
Ran locally
=> Update category friendly names

models/staging/standard_8d737a18/dexs_quote_assets.sql
1. Updating the dex quote assets to have another breakdown.
=> Customer: updating dex quote assets

models/projects/dydx_v4/core/ez_dydx_v4_metrics_by_chain.sql
=> Added DyDx Fix

macros/coingecko/get_coingecko_price_with_latest.sql, models/projects/raydium/core/ez_raydium_metrics.sql, models/staging/debridge/_test_fact_debridge_transfers.yml, models/staging/wormhole/fact_wormhole_operations_with_price.sql, seeds/all_categories_seed.csv
1. Wormhole: Fixing the pricing model to calculate based on the chain
2. Debridge: Removing broken tests from Transfers
3. Raydium: Adding missing columns from Raydium
4. BAM: Fixing all_category_seed
=> C911: Wormhole, Debridge, Raydium, BAM

models/staging/standard_8d737a18/dexs_quote_assets.sql
1. Fixing bug in dexs quote assets for SOL
=> c911: DEX Quote Assets

models/metrics/stablecoins/contracts/fact_solana_stablecoin_contracts.sql
Adding USDG on SOL which has 100M+ market cap, which is half of its total mcap.
=> Adding USDG on solana

models/dimensions/dim_app_datahub.sql, models/dimensions/dim_chain_datahub.sql
Update `dim_app_datahub` and `dim_chain_datahub` to include all chains, rather than just the chains that BAM supports.
Ran both locally
=> Update datahubs to include more chains

models/dimensions/dim_chain_datahub.sql
Adding a few more columns to DimChainDatahub for backend endpoint purposes as we move off of DimAssetDatahub
Ran locally
=> Add columns to dim chain datahub

models/projects/aave/core/ez_aave_metrics_by_chain.sql, models/projects/aave/core/ez_aave_metrics_by_token.sql, models/projects/arbitrum/core/ez_arbitrum_metrics.sql, models/projects/debridge/core/ez_debridge_metrics.sql, models/projects/maker/core/ez_maker_metrics_by_chain.sql, models/projects/maker/core/ez_maker_metrics_by_token.sql, models/projects/maker/raw/fact_maker_fees_revenue_expenses_by_token.sql, models/projects/wormhole/core/ez_wormhole_metrics.sql
Jobs to fix:
1. Arbitrum
2. Aave
3. Maker
4. Debridge
5. wormhole
=> C911: Fixing Arbitrum, Maker, Aave, debridge, wormhole

models/projects/debridge/core/ez_debridge_metrics.sql, models/projects/maker/core/ez_maker_metrics_by_token.sql
=> C911: updating maker and debridge

models/projects/brla/core/ez_brla_metrics.sql, models/projects/idrt/core/ez_idrt_metrics.sql, models/projects/idrx/core/ez_idrx_metrics.sql, models/projects/lvlusd/core/ez_lvlusd_metrics.sql, models/projects/tryb/core/ez_tryb_metrics.sql, models/projects/usdfalcon/core/ez_usdfalcon_metrics.sql
Adding project pages metrics for newly added stablecoins
=> Adding project pages metrics

models/dimensions/dim_all_supported_symbols_with_mc_rank.sql, models/staging/coingecko/fact_coingecko_token_metadata.sql
=> Add more category support

models/dimensions/dim_all_supported_symbols_with_mc_rank.sql
=> Remove Memecoins

models/projects/pumpfun/core/ez_pumpfun_metrics.sql, models/projects/pumpfun/core/ez_pumpfun_metrics_by_chain.sql, models/staging/pumpfun/__pumpfun__sources.yml, models/staging/pumpfun/fact_pumpswap_dau.sql, models/staging/pumpfun/fact_pumpswap_fees.sql, models/staging/pumpfun/fact_pumpswap_metrics.sql, models/staging/pumpfun/fact_pumpswap_txns.sql, models/staging/pumpfun/fact_pumpswap_volume.sql
**Fees:**
**Volume:**
**Txns:** (remain the same roughly)
**DAU:**
=> pumpswap fixes

macros/labeling/dune_evm_get_all_addresses.sql, models/dimensions/labeling/chain_level_addresses/dim_mantle_all_addresses.sql, models/dimensions/labeling/dim_all_addresses_silver.sql
Add mantle to labeling job for stablecoin pipeline
=> Labeling: add mantle labeling models

models/projects/arbitrum/core/__arbitrum__schema.yml, models/projects/base/core/__base__schema.yml, models/projects/bsc/core/__bsc__schema.yml, models/projects/ethereum/core/__ethereum__schema.yml, models/projects/mantle/core/__mantle__schema.yml, models/projects/near/core/__near__schema.yml, models/projects/optimism/core/__optimism__schema.yml, models/projects/polygon/core/__polygon__schema.yml, models/projects/sei/core/__sei__schema.yml, models/projects/stellar/core/__stellar__schema.yml, models/projects/tron/core/__tron__schema.yml
=> Remove BAM V1 models from schema files

models/dimensions/labeling/dim_all_addresses_labeled_silver.sql
Because `dim_all_addresses_labeled_silver` is an incremental table, changed categories within an app don't get propagated through all addresses with that app. This change fixes that
Ran in dbt locally
=> Update changed app categories within labels table

models/staging/mantle/fact_mantle_transactions_v2.sql, models/staging/near/fact_near_transactions_v2.sql, models/staging/tron/fact_tron_transactions_v2.sql
There were fact transactions columns which needed to get added to make downstream models work
Ran locally
=> Standardize fact transactions columns

models/projects/aerodrome/raw/fact_aerodrome_v1_tvl.sql, models/projects/near/core/ez_near_metrics.sql, models/projects/sei/core/ez_sei_metrics.sql, models/staging/arbitrum/fact_arbitrum_one_bridge_transfers.sql
Remove ANALYTICS_XL from usage in DBT models
=> Remove analytics xl warehouse from models

models/projects/ripple/core/ez_ripple_metrics.sql, models/staging/ripple/__ripple__sources.yml, models/staging/ripple/fact_ripple_fundamental_metrics.sql
=> ripple fundamental data

models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Move nulls to last in onchain explorer table
Ran in dbt
=> Move nulls to last in onchain explorer table

models/metrics/stablecoins/breakdowns/custom_charts/agg_daily_custom_charts_breakdown_by_geo.sql
=> Adding artemis daily txn to metrics

syncenv
=> Add dbt deps command to syncenv script

models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_symbol.sql
Support Artemis Filter for stat cards
=>  Model for supporting adjusted stablecoin volume for statcard

macros/stablecoins/stablecoin_metrics_automatic_labels.sql, models/projects/arbitrum/core/ez_arbitrum_stablecoin_metrics_by_address_with_labels.sql, models/projects/avalanche/core/ez_avalanche_stablecoin_metrics_by_address_with_labels.sql, models/projects/base/core/ez_base_stablecoin_metrics_by_address_with_labels.sql, models/projects/mantle/core/ez_mantle_stablecoin_metrics_by_address_with_labels.sql, models/projects/optimism/core/ez_optimism_stablecoin_metrics_by_address_with_labels.sql, models/projects/sui/core/ez_sui_stablecoin_metrics_by_address_with_labels.sql, models/projects/ton/core/ez_ton_stablecoin_metrics_by_address_with_labels.sql
1. Creates incremental logic for refreshing stablecoins labels in a full
2. Creates models for Base, Arb, Avax
=> Create new Stablecoin Models with Updated Tags

macros/goldsky/clean_goldsky_evm_native_token_transfers.sql
1. Remove rows where transfer value is 0
=> Update Celo Native Transfer

models/dimensions/contracts/dim_celo_contract_addresses.sql, models/staging/celo/fact_celo_dau_txns_gas_usd_revenue_avg_txn_fee.sql
1. Fixing Celo Job after porting over to Goldsky
=> C911: Celo

models/projects/bsc/core/ez_bsc_stablecoin_metrics_by_address_with_labels.sql, models/projects/ethereum/core/ez_ethereum_stablecoin_metrics_by_address_with_labels.sql, models/projects/polygon/core/ez_polygon_stablecoin_metrics_by_address_with_labels.sql, models/projects/solana/core/ez_solana_stablecoin_metrics_by_address_with_labels.sql, models/projects/tron/core/ez_tron_stablecoin_metrics_by_address_with_labels.sql
1. Creating the final models for stablecoins using the new labels pipeline
To Do:
1. Need to materialize each of these models
- bsc
- ethereum
- solana
- tron
- polygon
=> Stablecoins: Create final stablecoin with labels models

models/projects/orca/core/ez_orca_metrics.sql
Test Plan:
1. All models materialize
2. Data looks as expected
=> orca ez fixes

models/staging/bob/fact_bob_decoded_events.sql, models/staging/bob/fact_bob_events.sql, models/staging/bsc/fact_bsc_decoded_events.sql, models/staging/bsc/fact_bsc_events.sql
1. Add Decoded Events and Events pipeline for BSC and BoB
=> Add decoded event pipeline for bob and bsc

models/projects/solana/core/ez_solana_metrics.sql
=> Solana REV

models/staging/debridge/fact_debridge_transfers.sql, models/staging/debridge/fact_debridge_transfers_with_prices.sql
Added Debridge References Metadata.
=> Fixed Debridge SF value out of bounds (over 38 digits)

models/projects/virtuals/core/__virtuals__schema.yml, models/projects/virtuals/core/ez_virtuals_metrics.sql, models/staging/virtuals/fact_virtuals_supply_data.sql
added fact_virtuals_supply_data
pipe it to the ez_metrics_table (premine_unlock_native, net_supply_change_native, circulating_supply_native)
ran reverse etl
=> Virtuals supply data

models/projects/iotex/core/ez_iotex_metrics.sql
Modify: re-organized iotex ez-table for clarity & readability
=> Outerlands Refresh - IoTex

models/staging/stargate/fact_stargate_supply_data.sql
- didn't use the proper warehouse
- changed it to STARGATE warehouse instead of sei warehouse
=> Stargate Supply Data - Change warehouse

models/projects/dydx/core/ez_dydx_metrics.sql
=> Fix Syntax Error for dydx

models/projects/bridge_flows/core/ez_bridge_flows.sql, models/projects/debridge/core/ez_debridge_metrics.sql, models/staging/cctp/fact_cctp_flows.sql, models/staging/cctp/fact_cctp_transfers.sql, models/staging/debridge/fact_debridge_fundamental_metrics.sql, models/staging/debridge/fact_debridge_transfers_with_price_and_metadata.sql
=> Moved Chains to CCTP Transfers and added metadata to fact_debridge_datasets

models/__global__schema.yml, models/projects/hyperliquid/core/__hyperliquid__schema.yml, models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql, models/projects/hyperliquid/core/ez_hyperliquid_metrics_by_chain.sql
staked_hype column is in ez_metrics_table - reran ez_metrics_table
reran hyperliquid retl
=> Hyperliquid data fix

models/common/ez_stablecoin_metrics_by_category_and_chain.sql
Adding a view in the common schema for easy stablecoin metrics by chain symbol and category.
=> adding new stablecoin view to common schema

models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql, models/projects/hyperliquid/core/ez_hyperliquid_metrics_by_chain.sql
=> Fix hyperliquid null values

models/projects/celestia/core/ez_celestia_metrics.sql
- [] Added new `fact` tables if necessary
- [] Added an `ez_metrics` and `ez_metrics_by_chain` model
=> Celestia removed duplicate columns

macros/address_balances/evm_address_balances.sql, macros/stablecoins/stablecoin_balances.sql, macros/stablecoins/stablecoin_metrics_automatic_labels.sql, models/metrics/stablecoins/breakdowns/dim_stablecoin_table_breakdown.sql, models/staging/base/fact_base_address_balances.sql, models/staging/base/fact_base_address_credits.sql, models/staging/base/fact_base_address_debits.sql
1. Update Base balances and switch stablecoin balances to new pipeline
=> Balances pipeline: Fix Incremental Run

macros/flipside/clean_flipside_evm_native_transfers.sql, models/staging/base/fact_base_native_token_transfers.sql
1. Migrate Trace Address to Trace Index
2. Remove traces that do not send any eth
=> c911: Fix Base Native Token Transfers

models/staging/centrifuge/__centrifuge_sources__.yml, models/staging/centrifuge/fact_centrifuge_evm_transactions.sql, models/staging/centrifuge/fact_centrifuge_fundamental_metrics.sql, models/staging/hydration/fact_hydration_fundamental_metrics.sql
=> Fixed Centrifuge and hydration

models/staging/rwa/addresses/fact_ethereum_rwa_addresses.sql
Add tracking for new BUIDL Class I Shares address.
=> new buidl address

macros/address_balances/forward_filled_address_balances.sql, models/dimensions/labeling/_test_dim_all_addresses_labeled_silver.yml, models/dimensions/labeling/dim_global_labeled_addresses.sql, models/projects/jupiter/core/ez_jupiter_metrics.sql, models/staging/jupiter/fact_jupiter_lst_tvl.sql, models/staging/jupiter/fact_jupiter_perps_tvl.sql, models/staging/jupiter/fact_jupitersol_stake_accounts.sql, seeds/manually_added_tokens_seed.csv
created fact_jupiter_perps_tvl, fact_jupitersol_stake_accounts and fact_jupiter_lst_tvl 
added perps and lst tvl
retl
=> Jupiter TVL

models/projects/flare/core/ez_flare_metrics.sql, models/staging/flare/fact_flare_daily_supply_data.sql
- Added back missing gross emissions to Flare supply model
=> add forward filled emissions

models/projects/drift/core/ez_drift_metrics_by_chain.sql
=> Fix ez_drift_metrics_by_chain

macros/standardization/token_transfer_events.sql, models/metrics/stablecoins/breakdowns/dim_stablecoin_table_breakdown.sql, models/staging/celo/__celo__sources.yml, models/staging/celo/fact_celo_address_balances_by_token.sql, models/staging/celo/fact_celo_l1_transactions_31056500.sql, models/staging/celo/fact_celo_transactions.sql
=> Update Celo Pipeline

models/dimensions/labeling/dim_legacy_sigma_tagged_contracts.sql, models/staging/sei/fact_sei_evm_transactions_v2.sql
Set sigma labels timestamp column to static date instead of constant current date. We will assume all labels received from sigma were on 2025-03-31. 
Full refreshed
=> Change sigma labels timestamp

models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Add categories to apps for the onchain explorer datahub. Also added all apps for each chain, so that we can query all apps by category from the frontend.
Ran locally
=> Add category to onchain explorer table as well as all apps

macros/address_balances/evm_address_credits.sql, macros/address_balances/evm_address_debits.sql, macros/contracts/distinct_contract_addresses.sql, macros/p2p/p2p_stablecoin_transfers.sql, macros/stablecoins/agg_chain_stablecoin_transfers.sql, macros/stablecoins/stablecoin_balances.sql, macros/stablecoins/stablecoin_metrics_artemis.sql, models/metrics/stablecoins/contracts/fact_sonic_stablecoin_contracts.sql, models/projects/sonic/core/ez_sonic_stablecoin_metrics_by_address_with_labels.sql, models/staging/sonic/dim_sonic_contract_addresses.sql, models/staging/sonic/fact_sonic_address_balances.sql, models/staging/sonic/fact_sonic_address_credits.sql, models/staging/sonic/fact_sonic_address_debits.sql, models/staging/sonic/fact_sonic_p2p_stablecoin_transfers.sql, models/staging/sonic/fact_sonic_stablecoin_balances.sql, models/staging/sonic/fact_sonic_stablecoin_metrics_all.sql, models/staging/sonic/fact_sonic_stablecoin_metrics_artemis.sql, models/staging/sonic/fact_sonic_stablecoin_metrics_p2p.sql, models/staging/sonic/fact_sonic_stablecoin_transfers.sql, models/staging/sonic/fact_sonic_token_transfers.sql
=> Stablecoins: Create Sonic Stablecoin Pipeline

macros/standardization/token_transfer_events.sql, models/staging/tron/fact_tron_token_transfers.sql
1. Create Tron Token Transfers from SonarX
=> Stablecoins: Create Tron Token Transfers

models/data_hubs/fact_daily_onchainexplorer_datahub.sql
Add all apps to the onchain explorer table -- even ones which have had no activity within the past 30 days.
Ran locally
=> Add all apps to onchain explorer table

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql
1. Add Application Column to Snowflake table
=> Add Application column to final stablecoin table

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql
=> C911: stablecoins

macros/stablecoins/stablecoin_breakdown.sql, models/common/ez_stablecoin_metrics_by_address.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_symbol.sql, models/metrics/stablecoins/breakdowns/custom_charts/agg_daily_custom_charts_breakdown_by_geo.sql, models/metrics/stablecoins/breakdowns/dim_stablecoin_table_breakdown.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql
1. Migrating stablecoin tables to new labeling system
=> Migrating Final Stablecoin Tables

models/staging/jupiter/fact_jupiter_aggregator_metrics.sql
Modified query to remove duplicates.
=> fix query to remove duplicates

models/projects/gmx/core/ez_gmx_metrics.sql, models/projects/gmx/core/ez_gmx_metrics_by_chain.sql, models/projects/gmx/core/ez_gmx_metrics_by_version.sql
=> C911: Fixing GMX Metrics

macros/stablecoins/stablecoin_breakdown.sql, models/common/ez_stablecoin_metrics_by_address.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_chain.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_tiles_breakdown_symbol.sql, models/metrics/stablecoins/breakdowns/agg_stablecoin_transfers_l30d.sql, models/metrics/stablecoins/breakdowns/custom_charts/agg_daily_custom_charts_breakdown_by_geo.sql
1. Fix Stablecoin Metrics need to change from_address to address
=> C911: Fix Stablecoin Breakdowns

macros/bridge/get_decoded_l1_superchain_bridge_events.sql, models/metrics/bridges/agg_daily_bridge_flows_metrics_silver.sql, models/staging/base/fact_base_bridge_transfers.sql, models/staging/unichain/fact_unichain_bridge_flows.sql, models/staging/unichain/fact_unichain_bridge_transfers.sql
=> Added Macro for superchain bridge, supporting unichain first

models/metrics/stablecoins/breakdowns/custom_charts/agg_daily_custom_charts_breakdown_by_geo.sql
1. C911 Fixing Geo stablecoin model
=> Fix Geo Stablecoin Model

models/staging/orca/__orca__sources.yml, models/staging/orca/fact_orca_apy.sql, models/staging/orca/fact_orca_stablecoin_apy.sql, seeds/stablecoin_yields/orca_stablecoin_pool_ids.csv
Added these parts of the pipeline for orca
=> Adding orca apy

models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/save/__save__sources.yml, models/staging/save/fact_save_apy.sql, models/staging/save/fact_save_stablecoin_apy.sql, seeds/stablecoin_yields/save_stablecoin_lending_ids.csv
Add save apy
TVL and APY is the same or roughly the same
=> Adding save apy

models/staging/babylon/fact_babylon_tvl_defillama.sql
Can we approve before the next babylon_job run @11pm today?
@alexwes
=> babylon-data-patch

macros/address_balances/evm_address_credits.sql, macros/address_balances/evm_address_debits.sql, models/staging/tron/fact_tron_token_transfers.sql
1. Fixing tron token transfers to use token address
=> Update Tron Token Transfers

models/metrics/stablecoins/yield/ez_yield_table.sql, models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/drift/fact_drift_stablecoin_apy.sql, models/staging/federal_funds/__federal_funds__source.yml, models/staging/federal_funds/fact_fedfunds_rates.sql, models/staging/kamino/fact_kamino_lending_apy.sql, models/staging/kamino/fact_kamino_stablecoin_apy.sql, models/staging/kamino/fact_kamino_vaults_apy.sql, models/staging/orca/fact_orca_apy.sql, models/staging/orca/fact_orca_stablecoin_apy.sql, models/staging/raydium/fact_raydium_apy.sql, models/staging/raydium/fact_raydium_stablecoin_apy.sql, models/staging/save/fact_save_apy.sql, models/staging/save/fact_save_stablecoin_apy.sql, seeds/stablecoin_yields/drift_stablecoin_pool_ids.csv
Added final piece to the full pipeline, for drift and fedfunds.
materialized it successfully.
Data example:
Drift:
close enough data.
Fedfunds:
=> Adding Drift spot and fedfunds

macros/bridge/get_decoded_l1_superchain_bridge_events.sql, models/projects/bridge_flows/core/ez_bridge_flows.sql, models/staging/across/fact_across_complete_transfers.sql, models/staging/base/fact_base_bridge_flows.sql, models/staging/base/fact_base_bridge_transfers.sql, models/staging/bridge_flows/fact_superchain_bridge_transfers.sql, models/staging/debridge/fact_debridge_transfers_with_price_and_metadata.sql, models/staging/unichain/fact_unichain_bridge_transfers.sql, models/staging/wormhole/fact_wormhole_operations_with_price.sql
Started migrating super chain bridge flows to general macro to clean up code and added skeleton transfer data to eventually share with the optimism team. 
Also fixed protocol fees to all be in usd.
=> Support op l2 flows

models/dimensions/bot_v_human/dim_blast_bots.sql, models/dimensions/current_balances/dim_blast_current_balances.sql, models/projects/blast/raw/ez_blast_address_balances_by_token.sql, models/staging/blast/fact_blast_address_balances_by_token.sql, models/staging/blast/fact_blast_address_credit_by_token.sql, models/staging/blast/fact_blast_address_debit_by_token.sql, models/staging/blast/fact_blast_daily_sleep.sql
=> Disable Additional Blast Models

macros/coingecko/get_coingecko_price_with_latest.sql, models/staging/base/fact_base_bridge_transfers.sql
=> Fix dml and unique test

models/staging/aptos/fact_aptos_token_transfers.sql
=> Fix Aptos Token Transfers

macros/contracts/distinct_contract_addresses.sql, models/projects/kaia/core/ez_kaia_stablecoin_metrics_by_address_with_labels.sql
Add Stablecoin metrics for KAIA
=> Stablecoin Metrics for Kaia

models/staging/kaia/fact_kaia_stablecoin_contracts.sql
1. Fixing the KAIA stablecoin addresses
=> Fixing Tether KAIA address

models/staging/equities/__equities__source.yml, models/staging/equities/fact_equities_price.sql
=> Added Equities Price Data DBT

macros/stablecoins/stablecoin_metrics_by_currency.sql, models/staging/arbitrum/fact_arbitrum_one_bridge_flows.sql
TON
Avalanche
Tron
Ethereum
Optimism
Arbitrum
Polygon
Base
BSC
Solana
=> Fixing currency model and arbitrum one flows

macros/stablecoins/agg_chain_stablecoin_transfers.sql, models/staging/arbitrum/fact_arbitrum_one_bridge_flows.sql
=> Update arbitrum bridge flows

macros/contracts/distinct_contract_addresses.sql, macros/stablecoins/agg_chain_stablecoin_transfers.sql, macros/stablecoins/stablecoin_balances.sql, models/projects/aptos/core/ez_aptos_stablecoin_metrics_by_address_with_labels.sql, models/staging/aptos/dim_aptos_contract_addresses.sql, models/staging/aptos/fact_aptos_p2p_stablecoin_transfers.sql, models/staging/aptos/fact_aptos_stablecoin_balances.sql, models/staging/aptos/fact_aptos_stablecoin_contracts.sql, models/staging/aptos/fact_aptos_stablecoin_metrics_all.sql, models/staging/aptos/fact_aptos_stablecoin_metrics_artemis.sql, models/staging/aptos/fact_aptos_stablecoin_metrics_p2p.sql, models/staging/aptos/fact_aptos_stablecoin_transfers.sql
1. Adding aptos stablecoin models
=> Aptos stablecoins

macros/bridge/get_decoded_l1_superchain_bridge_events.sql, models/staging/base/fact_base_bridge_transfers.sql, models/staging/bridge_flows/fact_superchain_bridge_transfers.sql, models/staging/equities/__equities__source.yml, models/staging/equities/fact_equities_price.sql
=> DBT model for equity prices

models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql, models/staging/hyperliquid/__hyperliquid__sources.yml, models/staging/hyperliquid/fact_hyperliquid_perps_tvl.sql
- add fact_hyperliquid_perps_tvl
- add to ez_hyperliquid_metrics
- add to ez_hyperliquid_metrics table (tvl)
ran RETL
=> Add hyperliquid perps tvl

macros/stablecoins/agg_chain_stablecoin_transfers.sql, macros/stablecoins/stablecoin_metrics_automatic_labels.sql, models/metrics/stablecoins/contracts/fact_aptos_stablecoin_premint_addresses.sql, models/metrics/stablecoins/contracts/fact_kaia_stablecoin_premint_addresses.sql
Add Premint addresses for Kaia and Aptos
=> Add Premint Addresses for kaia and aptos

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_aptos_stablecoin_balances_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_aptos_stablecoin_transfers_standard_8d737a18.sql, models/staging/standard_8d737a18/fact_kaia_stablecoin_transfers_standard_8d737a18.sql, seeds/chain_agnostic_ids.csv
1. Adding KAIA and APTOS to final stablecoin table
=> Add aptos and Kaia to final stablecoin table

models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql
=> Adding USD1

models/__global__sources.yml, models/projects/pancakeswap/core/ez_pancakeswap_metrics.sql, models/staging/pancakeswap/fact_pancakeswap_token_incentives.sql
Added two models to pull pancake swap token incentives. CAD still in progress for documentation.
Testing:
=> feature/pancakeswap token_incentives

models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql
1. Fixing incremental model run on agg_stablecoin_standard modes
=> Fix incremental run on standard model

models/dimensions/labeling/_test_dim_all_addresses_labeled_silver.yml, models/dimensions/labeling/dim_all_addresses_labeled_silver.sql, models/dimensions/labeling/dim_global_labeled_addresses.sql
1. Fix Global Labeled Address model to remove duplicates
=> C911: Fix global label addresses model

macros/wallet_funding/first_funding.sql, macros/wallet_funding/wallet_seeder_funding_recipients.sql, models/staging/arbitrum/fact_arbitrum_first_funding.sql, models/staging/arbitrum/fact_arbitrum_wallet_seeder_funding_recipients.sql
Adding wallet funding macros and models for additional wallet profile datapoints, starting with Arbitrum.
Both compiled queries run successfully; QA'd on limited/narrowed data
=> Add wallet funding models

models/metrics/stablecoins/yield/ez_yield_table.sql
Add qualify row_number() to the ez_yield_table to deduplicate incase there is 1.
=> Add qualify row number so that there is no duplicates in the final table

models/projects/believe/core/__believe__schema.yml, models/projects/believe/core/ez_believe_metrics.sql, models/projects/believe/core/ez_believe_metrics_by_chain.sql, models/staging/believe/fact_believe_coins_minted.sql, models/staging/believe/fact_believe_trades.sql
- add fact_believe_trades and fact_coins_minted
- Believe
ran RETL
=> Add Believe metrics

models/staging/drift/__drift__sources.yml, models/staging/drift/fact_drift_insurance_vault_apy.sql, models/staging/drift/fact_drift_lending_apy.sql, models/staging/drift/fact_drift_stablecoin_apy.sql
Adding Drift main pool lending apy
Now it has both insurance vaults and lending pool
Test example for main pool:
=> Adding drift main pool stablecoin yield

models/staging/vaults_fyi/fact_vaults_fyi_apy.sql
Reducing the rates, changes abit on the response structure.
=> Reduce the rates use on vaults fyi

models/metrics/stablecoins/breakdowns/dim_stablecoin_table_breakdown.sql, models/staging/celo/fact_celo_dau_txns_gas_usd_revenue_avg_txn_fee.sql
=> C911: Fix Celo

models/projects/ostium/core/ez_ostium_metrics.sql, models/projects/ostium/core/ez_ostium_metrics_by_chain.sql, models/staging/ostium/fact_ostium_market_pairs.sql, models/staging/ostium/fact_ostium_metrics.sql, models/staging/ostium/fact_ostium_trades_closures.sql, models/staging/ostium/fact_ostium_trades_open.sql
=> feature/ostium dau, txns, volume, fees

models/staging/stargate/fact_stargate_v2_avalanche_treasury_balance.sql
- missed out on avalanche chain
- reran all the downstream tables as well
- ran RETL
=> Fix for stargate ambiguous column

models/bam_models/all_chains/all_chains_gas_dau_txns_by_application.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_category_v2.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_chain.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_contract_v2.sql, models/bam_models/all_chains/all_chains_gas_dau_txns_by_subcategory.sql, models/projects/celo/raw/ez_celo_metrics_by_application_v2.sql, models/projects/celo/raw/ez_celo_metrics_by_category_v2.sql, models/projects/celo/raw/ez_celo_metrics_by_contract_v2.sql, models/projects/celo/raw/ez_celo_metrics_by_subcategory.sql, models/staging/celo/_test_fact_celo_blocks.yml, models/staging/celo/_test_fact_celo_token_transfers.yml, models/staging/celo/celo_trending_daily_v2.sql, models/staging/celo/celo_trending_weekly_monthly_v2.sql, models/staging/celo/fact_celo_transactions_v2.sql, models/trending/bam_trending_data_v2.sql
1. Create all Celo BAM models
2. Add Celo to upstream Bam mdoels
=> BAM: Create and add celo to BAM models

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ton_stablecoin_contracts.sql
Adding USDe on TON and USD1 on ETH
=> Adding USDe on TON and USD1 on ETH

models/projects/uniswap/core/ez_uniswap_metrics_by_chain.sql
=> Add total_expenses to ez_uniswap_metrics_by_chain

models/metrics/stablecoins/contracts/fact_bsc_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql, models/metrics/stablecoins/contracts/fact_polygon_stablecoin_contracts.sql
=> Adding XUSD and XSGD

models/staging/litecoin/fact_litecoin_blocks.sql, models/staging/litecoin/fact_litecoin_inputs.sql, models/staging/litecoin/fact_litecoin_transactions.sql
=> made litecoin incremental

models/staging/standard_8d737a18/dexs_quote_assets.sql, models/staging/standard_8d737a18/fact_celo_stablecoin_transfers_standard_8d737a18.sql
1. Update Celo to support `transaction_position` 
2. Update Dex Quote Assets
=> C911: Update Celo and Dex Quote Standards

macros/metrics/get_chain_gdp.sql
=> gpr to ecosystem rev

models/staging/eigenpie/fact_eigenpie_restaked_eth_count_with_usd_and_change.sql
All models run + tests pass. Good lesson to learn to use `dbt build` instead of `dbt run` so that tests are also ran.
=> coalesce values to avoid failing test

models/metrics/stablecoins/contracts/fact_ethereum_stablecoin_contracts.sql
=> Adding EURCV and GYEN

macros/wallets/distinct_eoa_addresses.sql, models/dimensions/wallet/dim_tron_eoa_addresses.sql
=> Finalize Tron Migration

models/projects/curve/core/ez_curve_metrics.sql, models/staging/curve/fact_curve_token_incentives.sql
Added:
- curve token_incenvite models
CAD: https://www.notion.so/artemisxyz/Curve-DAO-1e746f0265b480d1bbf9ee5eebed8d93
Validation:
=> feature/curve token_incentives

models/staging/believe/fact_believe_fees.sql
Update fact_believe_fees logic
=> Change incremental logic from 3 days to 1 day

models/projects/vertex/core/ez_vertex_metrics_by_chain.sql
=> Fix Vertex RETL

models/metrics/stablecoins/yield/ez_yield_table.sql
Change the naming convention to risk_score for now
=> Change the naming conventions

models/staging/kamino/fact_kamino_stablecoin_apy.sql
=> fix yield table

models/metrics/stablecoins/yield/ez_yield_table.sql, models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/drift/agg_drift_stablecoin_apy.sql, models/staging/drift/fact_drift_stablecoin_apy.sql, models/staging/kamino/agg_kamino_stablecoin_apy.sql, models/staging/kamino/fact_kamino_stablecoin_apy.sql, models/staging/orca/agg_orca_stablecoin_apy.sql, models/staging/orca/fact_orca_stablecoin_apy.sql, models/staging/raydium/agg_raydium_stablecoin_apy.sql, models/staging/raydium/fact_raydium_stablecoin_apy.sql, models/staging/save/agg_save_stablecoin_apy.sql, models/staging/save/fact_save_stablecoin_apy.sql, models/staging/vaults_fyi/agg_vaults_fyi_stablecoin_apy.sql, models/staging/vaults_fyi/fact_vaults_fyi_stablecoin_apy.sql
Added L7D apy for  Yield table sparkline
=> Adding L7D data for sparkline

macros/goldsky/clean_goldsky_events.sql, models/projects/bridge_flows/core/ez_bridge_flows.sql, models/staging/ink/fact_ink_decoded_events.sql, models/staging/ink/fact_ink_events.sql, models/staging/linea/fact_linea_decoded_events.sql, models/staging/linea/fact_linea_events.sql, models/staging/plume/fact_plume_decoded_events.sql, models/staging/plume/fact_plume_events.sql, models/staging/plume/fact_plume_token_transfers.sql, models/staging/soneium/fact_soneium_decoded_events.sql, models/staging/soneium/fact_soneium_events.sql, models/staging/unichain/fact_unichain_decoded_events.sql, models/staging/unichain/fact_unichain_events.sql, models/staging/worldchain/fact_worldchain_decoded_events.sql, models/staging/worldchain/fact_worldchain_events.sql
=> Updated Decoder Metrics

models/metrics/stablecoins/breakdowns/dim_stablecoin_table_breakdown_precomputed.sql
Forgot to add refs to the precomputed stablecoin table
Ran dbt locally
=> Add refs to precomputed stablecoin table

models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/federal_funds/fact_fedfunds_rates.sql, models/staging/pendle/__pendle_sources.yml, models/staging/pendle/agg_pendle_stablecoin_apy.sql, models/staging/pendle/fact_pendle_apy.sql, models/staging/pendle/fact_pendle_stablecoin_apy.sql, seeds/stablecoin_yields/pendle_stablecoin_pool_ids.csv
=> Adding pendle Pools

macros/across/across_v3_decode_filled_relay.sql
=> Fixed Data Quality with across

macros/bridge/get_decoded_l1_superchain_bridge_events.sql, models/staging/base/fact_base_bridge_transfers.sql, models/staging/bridge_flows/fact_superchain_bridge_transfers.sql, models/staging/soneium/fact_soneium_bridge_transfers.sql, models/staging/unichain/fact_unichain_bridge_transfers.sql, models/staging/worldchain/fact_worldchain_bridge_transfers.sql
=> Fixed Data Quality Issues for superchains

models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/morpho/__morpho__sources.yml, models/staging/morpho/agg_morpho_stablecoin_apy.sql, models/staging/morpho/fact_morpho_apy.sql, models/staging/morpho/fact_morpho_stablecoin_apy.sql, seeds/stablecoin_yields/morpho_stablecoin_vault_ids.csv
=> Adding morpho vaults

models/projects/vertex/core/ez_vertex_metrics_by_chain.sql
Added:
- vertex token incentives fix to by_chain table
=> dataquality/vertex token_incentives fix

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql
Adding Aptos to stablecoin Data
=> Adding Aptos To stablecoin FE

macros/rwa/rwa_balances.sql, models/projects/plume/core/ez_plume_metrics.sql, models/staging/plume/fact_plume_fundamental_metrics.sql, models/staging/plume/fact_plume_rwa_addresses.sql, models/staging/plume/fact_plume_rwa_balances.sql, models/staging/plume/fact_plume_rwa_supply_by_date_and_chain.sql
=> Added plume rwa tvl

models/staging/debridge/fact_debridge_transfers_with_prices.sql
=> Updated Debridge Data

models/staging/synthetix/fact_synthetix_fee_sharing_cashflow_by_token_and_chain.sql
Looks like I had forgotten to save this file and include it in the earnigns PR. This caused synthetix job to fail. Fix was to save my changes, now everything runs well.
**DBT Run**
**Original Error:**
=> identifier

models/metrics/stablecoins/yield/fact_stablecoin_apy.sql, models/staging/falcon_finance/__falcon_finance__source.yml, models/staging/falcon_finance/agg_susdf_apy.sql, models/staging/falcon_finance/fact_susdf_apy.sql, models/staging/falcon_finance/fact_susdf_stablecoin_apy.sql
=> DBT models for susdf vaults

models/staging/coingecko/_coingecko__sources.yml, models/staging/coingecko/_test_fact_coingecko_token_date_adjusted.yml, models/staging/coingecko/fact_coingecko_token.sql, models/staging/coingecko/fact_coingecko_token_date_adjusted.sql, models/staging/coingecko/fact_coingecko_token_date_adjusted_gold.sql
- [ x] `dbt build model_name+` screenshot (must include downstream models)
- [x ] Successful RETL screenshot
=> Add Coingecko Historical Circulating Supply to Snowflake

models/staging/internet_computer/fact_internet_computer_fundamental_metrics_silver.sql
-  [x] Screenshots of changed data **in local frontend**
=> Fix internet computer null revenue values

models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_symbol_chain_standard_8d737a18.sql
1. Update agg symbol and chain to include all stablecoins not just subset.
=> Standard Stablecoin Table

models/staging/debridge/__debridge__sources.yml, models/staging/debridge/fact_debridge_order_metadata.sql
=> Added Debridge Data

models/projects/maple/core/ez_maple_metrics.sql, models/projects/maple/core/ez_maple_metrics_by_chain.sql, models/projects/maple/core/ez_maple_metrics_by_token.sql, models/staging/maple/fact_maple_token_incentives.sql
Figured out the values were not aligned because of pricing data
- edited the pricing data to `get_coingecko_metrics`
- ran RETL
=> Maple token incentives

models/staging/hyperliquid/fact_hyperliquid_perps_trading_volume.sql, models/staging/hyperliquid/fact_hyperliquid_trading_volume.sql
=> Fix duplicated date issues and data quality

macros/p2p/p2p_stablecoin_transfers.sql, macros/stablecoins/stablecoin_metrics_automatic_labels.sql, macros/wallets/distinct_eoa_addresses.sql, models/dimensions/wallet/dim_ripple_eoa_addresses.sql, models/projects/ripple/core/ez_ripple_stablecoin_metrics_by_address_with_labels.sql, models/staging/ripple/fact_ripple_p2p_stablecoin_transfers.sql, models/staging/ripple/fact_ripple_stablecoin_metrics_all.sql, models/staging/ripple/fact_ripple_stablecoin_metrics_artemis.sql, models/staging/ripple/fact_ripple_stablecoin_metrics_p2p.sql
Adding 2nd part of stablecoin pipeline for XRPL
=> Adding the pt2 of the stablecoin pipeline for XRPL

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql, seeds/chain_agnostic_ids.csv
Adding ripple chain to final table
=> Adding to frontend for ripple

macros/bridge/OFTRecieved.sql, macros/bridge/OFTSent.sql, models/staging/hyperliquid/fact_hyperevm_decoded_events.sql, models/staging/hyperliquid/fact_hyperevm_events.sql, models/staging/usdt0/fact_usdt0_OFTReceived.sql, models/staging/usdt0/fact_usdt0_OFTSent.sql, models/staging/usdt0/fact_usdt0_arbitrum_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_arbitrum_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_berachain_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_berachain_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_ethereum_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_ethereum_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_hyperevm_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_hyperevm_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_ink_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_ink_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_optimism_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_optimism_event_OFTSent.sql, models/staging/usdt0/fact_usdt0_transfers.sql, models/staging/usdt0/fact_usdt0_unichain_event_OFTReceived.sql, models/staging/usdt0/fact_usdt0_unichain_event_OFTSent.sql, seeds/stargate_chain_ids.csv
1. Add support for USDT0 Bridge
=> Add USDT0 bridge transfers

.github/workflows/compile.yml, .github/workflows/docs.yml, dbt_scripts/create_complete_queries.sh, dbt_scripts/generate_schema.py, dbt_scripts/show_changed.sh
- Set explicit `prod` target in dbt repo prior to developer schema creation
=> Set Explicit Prod Target in dbt Repo

seeds/stargate_chain_ids.csv
1. update stargate tracked chains
=> Update stargate chains

macros/coingecko/get_coingecko_price_with_latest.sql, macros/euler/euler_VaultStatus.sql
Tick the following only after PR has been approved and before it is merged: 
Fixing a data quality issue with DML and tested a bunch of different assets that use core macro so should be good to merge.
=> Fix Euler DML Action

macros/rwa/stablecoin_balances_from_addresses.sql, macros/rwa/stablecoin_supply_by_date_and_chain.sql, models/projects/plume/core/__plume__schema.yml, models/projects/plume/core/ez_plume_metrics.sql, models/staging/plume/fact_plume_fundamental_metrics.sql, models/staging/plume/fact_plume_rwa_addresses.sql, models/staging/plume/fact_plume_stablecoin_addresses.sql, models/staging/plume/fact_plume_stablecoin_balances.sql, models/staging/plume/fact_plume_stablecoin_supply_by_date_and_chain.sql
=> Added Plume Stablecoin Supply data and updated rwa

models/staging/eigenpie/fact_eigenpie_restaked_eth_count_with_usd_and_change.sql
=> Fixed EigenPie Data Model

.github/CODEOWNERS
- Remove CODEOWNERS
- Removed from branch protections
=> Delete CODEOWNERS file

models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql, models/projects/hyperliquid/core/ez_hyperliquid_metrics_by_chain.sql
=> Coalesce hyperliquid chain fees

macros/decentralized_exchanges/fact_curve_dex_swaps.sql
=> Fixed Curve DML Data

models/data_hubs/fact_protocol_datahub_by_chain_gold.sql, models/data_hubs/fact_protocol_datahub_gold.sql
Casting price to float in datahub tables
=> cast price to float

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_breakdown_with_labels_silver.sql, seeds/chain_agnostic_ids.csv
=> Adding Stellar to FE

models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_balances.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_bridge_supply_standard_8d737a18.sql
1. Update stablecoin balances to be incremental
2. Update standard bridge data to be incremental
=> Update agg stablecoin balances table snowflake

models/staging/stellar/fact_stellar_issued_supply_and_float_dbt.sql
Adding date range to stellar issued supply & float
=> updated stellar issued supply dates

.github/workflows/docs.yml
=> Revert change that intentionally breaks docs workflow

macros/address_balances/address_debits.sql, models/metrics/stablecoins/breakdowns/agg_daily_stablecoin_balances.sql
1. Fix Stablecoin Job
2. Fix polygon job
=> Update stablecoin and polygon job

models/staging/coingecko/fact_coingecko_token_metadata.sql
Remove nulls from fact_coingecko_token_metadata to fix failing test
- [ x] Internal only (check this box this PR should not appear in external facing docs/changelog)
- [x ] `dbt build model_name+` screenshot (must include downstream models)
=> Remove NULLs from fact_coingecko_token_metadata

macros/bridge/OFTRecieved.sql, macros/bridge/OFTSent.sql, macros/stablecoins/agg_chain_stablecoin_transfers.sql
=> Fix amount column

models/staging/hyperliquid/fact_hyperliquid_spot_trading_volume.sql, models/staging/hyperliquid/fact_hyperliquid_trading_volume.sql
`dbt build fact_hyperliquid_spot_trading_volume`
`dbt build fact_hyperliquid_trading_volume`
=> #Customer911 - Hyperliquid Trading Volume

macros/address_balances/evm_address_credits.sql, macros/address_balances/evm_address_debits.sql, macros/contracts/distinct_contract_addresses.sql, macros/stablecoins/agg_chain_stablecoin_transfers.sql, macros/stablecoins/stablecoin_balances.sql, macros/stablecoins/stablecoin_metrics_automatic_labels.sql, models/projects/katana/core/ez_katana_stablecoin_metrics_by_address_with_labels.sql, models/staging/katana/dim_katana_contract_addresses.sql, models/staging/katana/fact_katana_address_balances.sql, models/staging/katana/fact_katana_address_credits.sql, models/staging/katana/fact_katana_address_debits.sql, models/staging/katana/fact_katana_decoded_events.sql, models/staging/katana/fact_katana_events.sql, models/staging/katana/fact_katana_p2p_stablecoin_transfers.sql, models/staging/katana/fact_katana_stablecoin_balances.sql, models/staging/katana/fact_katana_stablecoin_contracts.sql, models/staging/katana/fact_katana_stablecoin_metrics_all.sql, models/staging/katana/fact_katana_stablecoin_metrics_artemis.sql, models/staging/katana/fact_katana_stablecoin_metrics_p2p.sql, models/staging/katana/fact_katana_stablecoin_premint_addresses.sql, models/staging/katana/fact_katana_stablecoin_transfers.sql, models/staging/katana/fact_katana_token_transfers.sql, models/staging/standard_8d737a18/agg_daily_stablecoin_breakdown_bridge_supply_standard_8d737a18.sql
Adding Katana stablecoins, USDC, AUSD, USDT
=> Adding Katana stablecoins

models/staging/standard_8d737a18/perp_quote_assets.sql
Support perp Quote Assets for Hyperliquid
=> Support perp quote assets for hyperliquid

models/projects/drift/core/ez_drift_metrics.sql, models/staging/drift/__drift__sources.yml, models/staging/drift/fact_drift_open_interest.sql
=> Added drift OI

models/projects/mento/core/ez_mento_metrics.sql
=> Update mento model

models/projects/bonk/core/__bonk__schema.yml, models/projects/bonk/core/ez_bonk_metrics.sql, models/staging/bonk/__bonk__sources.yml, models/staging/bonk/__test_fact_bonk_fundamental_metrics.yml, models/staging/bonk/fact_bonk_coins_minted.sql, models/staging/bonk/fact_bonk_fees.sql, models/staging/bonk/fact_bonk_fundamental_metrics.sql, models/staging/bonk/fact_bonk_swaps.sql
Added Bonks Fundamental Metrics:
1. Number of Tokens Deployed (coins minted)
2. Trading Volume
3. DAUs
4. Number of Transactions
=> Added Bonk Changes

models/projects/hyperliquid/raw/fact_hyperliquid_trades.sql
- [ x] Internal only (check this box this PR should not appear in external facing docs/changelog)
=> Fix Parquet File Parsing for fact_hyperliquid_trades

models/projects/solana/core/ez_solana_metrics_by_application_v2.sql
Remove comma to fix table
Ran model locally
=> Fix Solana Ez Metrics Application Table

models/staging/bonk/fact_bonk_swaps.sql, models/staging/drift/__drift__sources.yml, models/staging/drift/fact_drift_markets.sql, models/staging/drift/fact_drift_open_interest.sql
1. Used a new endpoint to pull drift contract markets data easier (will also be helpful with getting the index and all the new market data). 
=> Added Drift OI via Drift Contract API

models/projects/hyperliquid/core/ez_hyperliquid_metrics.sql
- Fix various bugs in `ez_hyperliquid_metrics` dbt model
- [ x] Internal only (check this box this PR should not appear in external facing docs/changelog)
- [x ] `dbt build model_name+` screenshot (must include downstream models)
=> Fix ez_hypeliquid_metrics sql

models/projects/bonk/core/ez_bonk_metrics.sql, models/staging/bonk/fact_bonk_fundamental_metrics.sql
Fixed bonk fees, added unique tokens traded, avg swap size usd, fee to volume ratio
- [] Internal only (check this box this PR should not appear in external facing docs/changelog)
=> fixed bonk fees, added launchpad trading metrics
